MetaMask/snaps

- package.json
- yarn.lock
Lerna is meant to be added as as `devDependency`. This makes it easier to setup the project, and ensures we're using the correct version.
> Add `lerna` as a devDependency

- packages/controllers/src/services/WebWorkerExecutionEnvironmentService.ts
- packages/workers/execution-environment-openrpc.json
- packages/workers/src/PluginWorker.ts
preview in playground: https://playground.open-rpc.org/?url=https://raw.githubusercontent.com/MetaMask/snaps-skunkworks/79c2110d758c8194cc525c44776f2967e1878919/packages/workers/execution-environment-openrpc.json
> add snaps execution environment OpenRPC spec

- .github/workflows/create-release-pr.yml
- .prettierrc.js
- package.json
- packages/controllers/.eslintrc.js
- packages/controllers/src/plugins/PluginController.test.ts
- packages/controllers/src/resource/ExternalResourceController.ts
- packages/controllers/src/services/WebWorkerExecutionEnvironmentService.test.ts
- packages/controllers/src/services/WebWorkerExecutionEnvironmentService.ts
- packages/rpc-methods/src/utils.ts
- packages/workers/src/PluginWorker.ts
- yarn.lock
Updates TypeScript and ESLint dependencies, adds default `prettierrc.js`, and lints all files.
> Update TypeScript and ESLint dependencies

- package.json
> add current version to package.json

- packages/controllers/package.json
- yarn.lock
Add `@metamask/controllers@14.2.0`.
> @metamask/controllers@14.2.0

- packages/controllers/package.json
- packages/controllers/src/plugins/PluginController.ts
- yarn.lock
Bumps `@metamask/controllers` to the latest version.
> @metamask/controllers@17.0.0

- packages/controllers/src/plugins/PluginController.test.ts
- packages/controllers/src/plugins/PluginController.ts
This adds enable/disable functionality to the `PluginController`.
fixes #113
> PluginController: Allow enabling / disabling plugins

- packages/controllers/src/snaps/SnapController.ts
> Fixed issue with cleanup of lastRequestMap after stopping

- packages/example-snap/package.json
- packages/example-snap/snap.manifest.json
Fixes a bug in the build script of the `example-snap` package.
> Fix example-snap build issue

- packages/controllers/src/services/AbstractExecutionService.ts
- packages/controllers/src/services/ExecutionService.ts
- packages/controllers/src/services/WebWorkerExecutionEnvironmentService.ts
- packages/controllers/src/services/WebWorkerExecutionService.test.ts
- packages/controllers/src/services/WebWorkerExecutionService.ts
- packages/controllers/src/services/index.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/iframe-execution-environment-service/src/IframeExecutionEnvironmentService.test.ts
- packages/iframe-execution-environment-service/src/IframeExecutionEnvironmentService.ts
- packages/iframe-execution-environment-service/src/IframeExecutionService.ts
- packages/iframe-execution-environment-service/src/index.ts
- packages/iframe-execution-environment-service/src/testHelpers/fixJSDOMPostMessageEventSource.ts
- packages/types/index.d.ts
> Extracted common code from ExecutionEnvironmentServices into an abstract class

- packages/controllers/src/permissions/PermissionController.test.ts
- packages/controllers/src/permissions/PermissionController.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
> Added PermissionsController actions that are used in SnapController

- packages/controllers/src/index.ts
- packages/rpc-methods/src/restricted/manageState.ts
Used a bad import/export that fails in production, but not in tests 😅
> Fix snap controller utils export

- packages/controllers/jest.config.js
Updates controller coverage minimums to their current actuals.
See also: #284
> Update controller coverage minimums

- .eslintrc.js
Updates the root ESLint config to ignore generated files.
> Fix root .eslintrc

- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/src/snaps/utils.ts
- packages/controllers/src/utils.test.ts
- packages/controllers/src/utils.ts
> Add updateSnap function to SnapController

- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
> Fix issue where installation errors were repeatedly thrown

- packages/controllers/src/snaps/default-endowments.ts
- packages/execution-environments/src/common/endowments/index.ts
- packages/execution-environments/src/common/endowments/interval.test.ts
- packages/execution-environments/src/common/endowments/interval.ts
- packages/execution-environments/src/common/endowments/timeout.ts
> Add setInterval and clearInterval as default endowments

- .github/workflows/build-lint-test.yml
> Add CodeCov action

- packages/cli/src/cmds/eval/eval-worker.ts
Unifies with the current endowments available in the execution environment
> Add self to mock endowments

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/iframe-execution-environment-service/package.json
This PR now has additional user approval that is not implemented in metamask-extension yet
> Added ability to update snaps when installing them

- README.md
> its public

- packages/cli/src/cmds/build/bundle.test.ts
- packages/cli/src/cmds/build/bundle.ts
- packages/cli/src/cmds/eval/eval-worker.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/examples/examples/bls-signer/snap.manifest.json
- packages/examples/examples/bls-signer/src/index.js
- packages/examples/examples/ethers-js/snap.manifest.json
- packages/examples/examples/ethers-js/src/index.js
- packages/examples/examples/ipfs/snap.manifest.json
- packages/examples/examples/ipfs/src/index.js
- packages/examples/examples/notifications/snap.manifest.json
- packages/examples/examples/notifications/src/index.js
- packages/examples/examples/rollup/package.json
- packages/examples/examples/rollup/snap.manifest.json
- packages/examples/examples/rollup/src/snap.ts
- packages/examples/examples/typescript/snap.manifest.json
- packages/examples/examples/typescript/src/index.ts
- packages/examples/examples/wasm/snap.manifest.json
- packages/examples/examples/wasm/src/index.js
- packages/examples/examples/webpack/package.json
- packages/examples/examples/webpack/snap.manifest.json
- packages/examples/examples/webpack/src/snap.ts
- packages/examples/examples/webpack/webpack.config.ts
- packages/execution-environments/jest.config.js
- packages/execution-environments/package.json
- packages/execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/execution-environments/src/common/BaseSnapExecutor.ts
- packages/types/src/types.d.ts
> BREAKING: Moved Snaps to be based on CommonJS

- packages/controllers/jest.config.js
- packages/controllers/package.json
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- yarn.lock
Fixes #358 
This will be a breaking change.
> BREAKING: Add state encryption

- packages/execution-environments/src/common/BaseSnapExecutor.test.ts
> Added test that checks for unbound this escape

- package.json
- packages/cli/src/cmds/build/bundle.ts
- packages/examples/examples/typescript/package.json
- packages/examples/examples/typescript/snap.manifest.json
- packages/examples/examples/typescript/src/index.ts
- packages/examples/examples/typescript/src/message.ts
- yarn.lock
resolves #521 
https://github.com/babel/babelify#customizing-extensions
P.S. added verbose flag when running commands on all workspaces, let me know if I should remove it (I find it useful to see from which workspace log is coming from).
> Fix importing local files in typescript snaps

- packages/controllers/package.json
- packages/rpc-methods/package.json
- packages/types/package.json
- yarn.lock
Updates `@metamask/controllers` to `30.0.0`
> @metamask/controllers@30.0.0

- packages/types/package.json
- packages/types/src/types.d.ts
- yarn.lock
Improve `onRpcMessageHandler` type by using `JsonRpcRequest`.
> Update `onRpcMessageHandler` type

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/plugin-webpack/src/__snapshots__/plugin.test.ts.snap
> Fix update snap request object

- packages/execution-environments/jest.config.js
- packages/execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/execution-environments/src/common/BaseSnapExecutor.ts
- packages/execution-environments/src/common/endowments/index.test.ts
- packages/execution-environments/src/common/endowments/network.test.ts
- packages/execution-environments/src/common/endowments/network.ts
- packages/execution-environments/src/common/utils.ts
Fix: https://github.com/MetaMask/snaps-skunkworks/issues/574
> Make improvements so teardown cannot be escaped by late returning promises

- packages/utils/src/default-endowments.ts
> Added AbortSignal to default endowments

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/src/snaps/keyring.test.ts
- packages/controllers/src/snaps/keyring.ts
Adds matching logic to match requested namespaces with existing keyring snaps.
> Add matching logic for keyring snaps

- packages/execution-environments/jest.config.js
- packages/execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/execution-environments/src/common/BaseSnapExecutor.ts
- packages/execution-environments/src/common/commands.ts
- packages/execution-environments/src/common/keyring.ts
- packages/execution-environments/src/common/validation.ts
- packages/execution-environments/src/openrpc.json
- packages/types/src/types.d.ts
- packages/utils/jest.config.js
- packages/utils/src/types.ts
Adds basic Keyring support to the execution environment, allowing snaps to expose a keyring class and allowing others to call functions on that class.
> Add Snap Keyring support to execution environment

- packages/controllers/package.json
- packages/rpc-methods/package.json
- packages/rpc-methods/src/restricted/getBip32Entropy.ts
- packages/rpc-methods/src/restricted/getBip32PublicKey.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.ts
- yarn.lock
Bump `@metamask/controllers` to `31.0.0`.
> Bump `@metamask/controllers` to `31.0.0`

- packages/provider/src/client/MultiChainProvider.ts
- packages/provider/src/wallet/MultiChainController.ts
- packages/provider/src/wallet/middleware.ts
Proposed change to a hacky way of allowing multichain requests via the existing MetaMask provider.
> MultiChain request hack proposal

- packages/provider/jest.config.js
- packages/provider/package.json
- packages/provider/src/MultiChainProvider.test.ts
- packages/provider/src/MultiChainProvider.ts
- packages/provider/tsconfig.json
- packages/utils/jest.config.js
- packages/utils/src/namespace.ts
- packages/utils/src/test-utils/manifest.ts
- yarn.lock
This adds tests for the `MultiChainProvider` to achieve 100% test coverage, and fixes some small issues in the provider.
> Add tests for MultiChainProvider and some small fixes

- packages/provider/src/MultiChainProvider.test.ts
- packages/provider/src/MultiChainProvider.ts
- packages/utils/jest.config.js
- packages/utils/src/index.ts
- packages/utils/src/json-rpc.test.ts
- packages/utils/src/json-rpc.ts
- packages/utils/src/namespace.ts
This improves the multichain provider error messaging ,tests and documentation, as per the feedback in #700.
> Improve provider error messaging, tests, docs

- packages/controllers/src/multichain/MultiChainController.ts
This adds JSDoc comments to all functions of the multichain controller functions, and changes some existing documentation comments.
> Improve multichain controller documentation

- packages/controllers/package.json
- packages/rpc-methods/package.json
- yarn.lock
Bumps `@metamask/controllers` to `32.0.2` to allow for better deduping in the extension.
> `@metamask/controllers@32.0.2`

- packages/controllers/jest.config.js
- packages/controllers/src/cronjob/index.ts
- packages/controllers/src/index.ts
> Add missing cronjob exports

- packages/controllers/jest.config.js
- packages/controllers/src/cronjob/CronjobController.test.ts
- packages/controllers/src/cronjob/CronjobController.ts
Add some optimizations to the Cronjob Controller tests in order to run that suite faster.
> Add some optimizations for Cronjob tests

- jest.config.base.js
- packages/snap-controllers/jest.config.js
This fixes the coverage in the controllers package.
> Ignore `.test.ts` files in coverage

- .github/dependabot.yml
Re-add Dependabot now that it supports Yarn 3.
> Re-add Dependabot

- packages/snaps-cli/package.json
- packages/snaps-execution-environments/package.json
- packages/snaps-utils/package.json
- yarn.lock
Update SES version to the latest (0.18.1).
> Update SES to 0.18.1

- packages/snaps-cli/README.md
- packages/snaps-cli/src/cli.ts
updates the `mm-snap init` command examples to reflect the actual implementation.
> Update the `mm-snap init` examples

- packages/rpc-methods/src/permitted/requestSnaps.test.ts
- packages/rpc-methods/src/permitted/requestSnaps.ts
- packages/rpc-methods/src/restricted/index.ts
- packages/rpc-methods/src/restricted/invokeSnap.test.ts
- packages/rpc-methods/src/restricted/invokeSnap.ts
- packages/snaps-controllers/jest.config.js
- packages/snaps-controllers/package.json
- packages/snaps-controllers/src/cronjob/CronjobController.test.ts
- packages/snaps-controllers/src/multichain/MultiChainController.test.ts
- packages/snaps-controllers/src/multichain/MultiChainController.ts
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/test-utils/controller.ts
- packages/snaps-controllers/src/test-utils/multichain.ts
- packages/snaps-utils/jest.config.js
- packages/snaps-utils/package.json
- packages/snaps-utils/src/snaps.test.ts
- packages/snaps-utils/src/snaps.ts
- packages/snaps-utils/src/test-utils/manifest.ts
- packages/snaps-utils/src/test-utils/snap.ts
- yarn.lock
Closes #1105
Closes #1106 
Please see parent issue: https://github.com/MetaMask/MetaMask-planning/issues/297
> Update snap controllers to use caveats

- packages/snaps-cli/README.md
Fixed a few tiny issues with the CLI README following a docs PR that changed similar issues.
> Small CLI README changes

- packages/snaps-utils/src/handlers.ts
Fixes some problems with the transaction insights documentation and typing.
> Fix transaction insights docs

- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
- packages/snaps-execution-environments/src/common/test-utils/endowments.ts
- packages/snaps-execution-environments/src/common/utils.test.ts
- packages/snaps-execution-environments/src/common/utils.ts
Disallow requesting of certain dynamic RPC methods.
Fixes #1250
> Disallow requesting dynamic RPC methods

- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
Add types to the install/update result approval.
> Add types to result approvals

- README.md
This updates the preview build documentation to include steps for Yarn 2 (Berry)
> Update preview build documentation

- packages/examples/examples/signer/package.json
Adds a version to the signer example package.json.
> Add version to signer example

- packages/snaps-controllers/src/snaps/SnapController.ts
Added `snapId` to certain logs that could benefit from the extra information.
> Add `snapId` to select logs

- package.json
- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/location/npm.ts
- packages/snaps-simulator/src/App.tsx
- packages/snaps-simulator/src/features/builder/components/NodeRenderer.tsx
- packages/snaps-simulator/src/features/configuration/Configuration.tsx
- packages/snaps-simulator/src/features/configuration/slice.ts
- packages/snaps-simulator/src/features/handlers/components/Response.tsx
- packages/snaps-simulator/src/features/polling/sagas.ts
- packages/snaps-simulator/src/features/simulation/sagas.ts
- packages/snaps-simulator/src/features/status/StatusIndicator.tsx
- packages/snaps-simulator/src/theme.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/snaps.test.ts
- packages/snaps-utils/src/snaps.ts
Adds support for fetching and simulating NPM snaps in the simulator.
Fixes #1414
> Add support for NPM snaps to simulator

- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-execution-environments/lavamoat/browserify/iframe/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-process/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-thread/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/offscreen/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/policy-override.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-executor/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-pool/policy.json
- packages/snaps-utils/coverage.json
- packages/snaps-utils/package.json
- packages/snaps-utils/src/icon.test.ts
- packages/snaps-utils/src/icon.ts
- packages/snaps-utils/src/index.browser.ts
- packages/snaps-utils/src/index.ts
- packages/snaps-utils/src/npm.ts
- packages/snaps-utils/src/snaps.ts
- packages/snaps-utils/src/test-utils/manifest.ts
- packages/snaps-utils/src/validation.test.ts
- packages/snaps-utils/src/validation.ts
- yarn.lock
Adds validation of the snap SVG icon.
Fixes #1397
> Add SVG validation

- .eslintrc.js
- package.json
- packages/snaps-simulator/.eslintrc.js
- packages/snaps-simulator/src/features/builder/components/NodeRenderer.tsx
- packages/snaps-simulator/src/features/builder/components/NodeTree.tsx
- packages/snaps-simulator/src/features/configuration/Configuration.tsx
- packages/snaps-simulator/src/features/handlers/components/ResetTab.tsx
- packages/snaps-simulator/src/features/handlers/components/ResetUserInterfaceTab.tsx
- packages/snaps-simulator/src/features/handlers/components/Response.tsx
- packages/snaps-simulator/src/features/handlers/components/UserInterface.tsx
- packages/snaps-simulator/src/features/notifications/Notifications.tsx
- packages/snaps-simulator/src/features/renderer/components/Copyable.tsx
- packages/snaps-simulator/src/features/status/StatusIndicator.tsx
The ESLint configuration was not properly set up for TSX linting. I've fixed that in this PR.
Related to #1431.
> Fix linting of snaps-simulator

- packages/snaps-simulator/jest.config.js
- packages/snaps-simulator/package.json
- packages/snaps-simulator/src/features/configuration/slice.test.ts
- packages/snaps-simulator/src/features/polling/sagas.test.ts
- packages/snaps-simulator/src/features/simulation/hooks.test.ts
- packages/snaps-simulator/src/features/simulation/sagas.test.ts
- scripts/child-workspace-package-names-as-json.ts
Run tests for `snaps-simulator` which wasn't included in CI before due to the workspace being private.
> Run tests in CI for `snaps-simulator`

- packages/snaps-simulator/package.json
This fixes a build error in CI.
> Build simulator vendor before main build

- .github/workflows/publish-release.yml
Fixes the deployment path for test-snaps.
> Fix deployment path for test-snaps

- package.json
- packages/snaps-execution-environments/CHANGELOG.md
- packages/snaps-execution-environments/package.json
- packages/test-snaps/CHANGELOG.md
- packages/test-snaps/package.json
This release fixes a deployment issue with the iframe execution environment and fixes a test snaps bug.
> Release 2.0.0

- package.json
- packages/snaps-execution-environments/CHANGELOG.md
- packages/snaps-execution-environments/package.json
> Release 4.0.0

- packages/snaps-execution-environments/package.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
- packages/snaps-execution-environments/src/common/lockdown/lockdown-more.ts
- packages/snaps-execution-environments/src/common/lockdown/lockdown.ts
- packages/snaps-utils/package.json
- yarn.lock
Update SES to `0.18.7` to resolve a vulnerability issue.
> deps: ses@0.18.1->0.18.7

- .github/workflows/create-release-pr.yml
Cherry picks a release action update to the RC, this is needed for release.
> Cherry pick release action update to RC

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/registry/json.test.ts
- packages/snaps-controllers/src/snaps/registry/json.ts
Fixes an issue where multiple calls to the registry at once would spam requests to the registry.
> Fix parallel usage of registry

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/rpc-methods/jest.config.js
- packages/rpc-methods/src/restricted/getLocale.test.ts
- packages/rpc-methods/src/restricted/getLocale.ts
- packages/rpc-methods/src/restricted/index.ts
- packages/rpc-methods/src/restricted/notify.test.ts
- packages/snaps-controllers/src/snaps/permission.test.ts
Implements an RPC method that snaps can use to get the users chosen locale.
> Implement `snap_getLocale`

- packages/snaps-simulator/README.md
Add link to deployed simulator
> Update README.md with link to simulator on GH Pages

- packages/snaps-execution-environments/src/common/endowments/endowments.test.browser.ts
- packages/snaps-execution-environments/src/common/endowments/network.ts
Cherry-picks a hotfix to the RC
> Cherry-pick hotfix to RC

- packages/snaps-cli/README.md
Update example proposedName and permissions in README.md
Fixes #1676
> Correct documentation for proposedName and permissions

- packages/rpc-methods/src/restricted/manageAccounts.ts
Include account name in success message for demo.
> Remove unnecessary end approval flow

- package.json
- packages/create-snap/CHANGELOG.md
- packages/create-snap/package.json
- packages/examples/packages/name-lookup/CHANGELOG.md
- packages/examples/packages/name-lookup/package.json
- packages/examples/packages/name-lookup/snap.manifest.json
- packages/snaps-cli/CHANGELOG.md
- packages/snaps-cli/package.json
- packages/snaps-controllers/CHANGELOG.md
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/CHANGELOG.md
- packages/snaps-execution-environments/package.json
- packages/snaps-utils/CHANGELOG.md
- packages/snaps-utils/package.json
- packages/test-snaps/CHANGELOG.md
- packages/test-snaps/package.json
> Release 10.0.0

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/cronjob/CronjobController.test.ts
- packages/snaps-controllers/src/cronjob/CronjobController.ts
Fix an issue where in some cases a cronjob would be executed on every init of the controller.
> Fix an issue where cronjobs would continually be executed on init

- package.json
- packages/create-snap/CHANGELOG.md
- packages/create-snap/package.json
- packages/snaps-cli/CHANGELOG.md
- packages/snaps-cli/package.json
- packages/snaps-controllers/CHANGELOG.md
- packages/snaps-controllers/package.json
- packages/snaps-webpack-plugin/CHANGELOG.md
- packages/snaps-webpack-plugin/package.json
This release is mainly for bug fixes.
> Release 11.0.0

- packages/examples/packages/name-lookup/package.json
- packages/examples/packages/name-lookup/snap.manifest.json
- packages/examples/packages/name-lookup/src/index.test.ts
- packages/examples/packages/name-lookup/src/index.ts
- yarn.lock
The current example snap is not inline with SIP-12, see https://github.com/MetaMask/snaps/pull/1768#discussion_r1334399505
> Fix name lookup example snap

- packages/snaps-controllers/wdio.config.js
- packages/snaps-execution-environments/wdio.config.js
- packages/snaps-utils/wdio.config.js
Tweaks the WDIO config, reducing the number of workers to 1 and disables running tests in FF locally.
> Tweak WDIO config

- package.json
- scripts/install-chrome.sh
- yarn.lock
This adds support for Chrome 118.
> Bump Chromedriver to `^118.0.1`

- package.json
- packages/snaps-controllers/CHANGELOG.md
- packages/snaps-controllers/package.json
> Release 14.0.0

- package.json
- packages/examples/package.json
- packages/examples/packages/get-file/CHANGELOG.md
- packages/examples/packages/get-file/package.json
- packages/examples/packages/get-file/snap.manifest.json
- packages/snaps-controllers/CHANGELOG.md
- packages/snaps-controllers/package.json
- packages/snaps-jest/CHANGELOG.md
- packages/snaps-jest/package.json
- packages/snaps-rpc-methods/CHANGELOG.md
- packages/snaps-rpc-methods/package.json
- packages/snaps-simulator/CHANGELOG.md
- packages/snaps-simulator/package.json
- packages/snaps-ui/CHANGELOG.md
- packages/snaps-ui/package.json
- packages/snaps-utils/CHANGELOG.md
- packages/snaps-utils/package.json
- packages/test-snaps/CHANGELOG.md
- packages/test-snaps/package.json
> Release 15.0.0

- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/examples/packages/transaction-insights/src/index.ts
Updating the example snap to work with tx insight v2.
> Update example insight snap

- package.json
- packages/create-snap/CHANGELOG.md
- packages/create-snap/package.json
- packages/examples/package.json
- packages/examples/packages/home-page/CHANGELOG.md
- packages/examples/packages/home-page/package.json
- packages/examples/packages/home-page/snap.manifest.json
- packages/examples/packages/localization/CHANGELOG.md
- packages/examples/packages/localization/package.json
- packages/examples/packages/localization/snap.manifest.json
- packages/examples/packages/manage-state/CHANGELOG.md
- packages/examples/packages/manage-state/package.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/transaction-insights/CHANGELOG.md
- packages/examples/packages/transaction-insights/package.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/snaps-controllers/CHANGELOG.md
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/CHANGELOG.md
- packages/snaps-execution-environments/package.json
- packages/snaps-rpc-methods/CHANGELOG.md
- packages/snaps-rpc-methods/package.json
- packages/snaps-simulator/CHANGELOG.md
- packages/snaps-simulator/package.json
- packages/snaps-types/CHANGELOG.md
- packages/snaps-types/package.json
- packages/snaps-utils/CHANGELOG.md
- packages/snaps-utils/package.json
- packages/test-snaps/CHANGELOG.md
- packages/test-snaps/package.json
> Release 17.0.0

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/home-page/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/lifecycle-hooks/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/snaps-ui/src/builder.test.ts
- packages/snaps-ui/src/builder.ts
- packages/snaps-ui/src/nodes.ts
This adds a new optional parameter to the `copyable` component.
> Add `sensitive` parameter to `copyable`

- package.json
- packages/examples/packages/localization/CHANGELOG.md
- packages/examples/packages/localization/package.json
- packages/examples/packages/localization/snap.manifest.json
- packages/test-snaps/CHANGELOG.md
- packages/test-snaps/package.json
Tiny release to fix a problem with an example snap.
> Release 19.0.0

- package.json
- packages/snaps-execution-environments/CHANGELOG.md
- packages/snaps-execution-environments/package.json
- packages/snaps-sdk/CHANGELOG.md
- packages/snaps-sdk/package.json
- packages/snaps-utils/CHANGELOG.md
- packages/snaps-utils/package.json
> Release 20.0.0

- package.json
- packages/snaps-cli/CHANGELOG.md
- packages/snaps-cli/package.json
This is the release candidate for version 22. It bumps just the CLI package.
> Release 22.0.0

- package.json
- packages/snaps-controllers/CHANGELOG.md
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/CHANGELOG.md
- packages/snaps-execution-environments/package.json
- packages/snaps-rpc-methods/CHANGELOG.md
- packages/snaps-rpc-methods/package.json
- packages/snaps-sdk/CHANGELOG.md
- packages/snaps-sdk/package.json
- packages/snaps-simulator/CHANGELOG.md
- packages/snaps-simulator/package.json
- packages/snaps-utils/CHANGELOG.md
- packages/snaps-utils/package.json
This release is mainly maintenance changes and performance improvements.
> Release 24.0.0

- package.json
- packages/examples/package.json
- packages/examples/packages/wasm/CHANGELOG.md
- packages/examples/packages/wasm/package.json
- packages/examples/packages/wasm/snap.manifest.json
- packages/snaps-cli/CHANGELOG.md
- packages/snaps-cli/package.json
- packages/snaps-controllers/CHANGELOG.md
- packages/snaps-controllers/package.json
- packages/snaps-utils/CHANGELOG.md
- packages/snaps-utils/package.json
- packages/test-snaps/CHANGELOG.md
- packages/test-snaps/package.json
> Release 25.0.0

- package.json
- packages/snaps-rpc-methods/CHANGELOG.md
- packages/snaps-rpc-methods/package.json
- yarn.lock
Hotfix release for a potential problem with middleware.
> Release 26.0.0

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/home-page/snap.manifest.json
- packages/examples/packages/images/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/lifecycle-hooks/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/snaps-execution-environments/lavamoat/browserify/iframe/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-process/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-thread/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/offscreen/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-executor/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-pool/policy.json
- packages/snaps-sdk/src/index.ts
Export error wrappers from the SDK to be used in Snaps.
> Export error wrappers

- package.json
- packages/snaps-sdk/CHANGELOG.md
- packages/snaps-sdk/package.json
- yarn.lock
Tiny release to fix a missing export in the Snaps SDK.
> Release 27.0.0

- package.json
- packages/snaps-controllers/CHANGELOG.md
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/CHANGELOG.md
- packages/snaps-execution-environments/package.json
- packages/snaps-rpc-methods/CHANGELOG.md
- packages/snaps-rpc-methods/package.json
- packages/snaps-utils/CHANGELOG.md
- packages/snaps-utils/package.json
> Release 28.0.0

- package.json
- packages/snaps-cli/CHANGELOG.md
- packages/snaps-cli/package.json
- packages/snaps-controllers/CHANGELOG.md
- packages/snaps-controllers/package.json
- packages/snaps-sdk/CHANGELOG.md
- packages/snaps-sdk/package.json
- packages/snaps-utils/CHANGELOG.md
- packages/snaps-utils/package.json
- yarn.lock
> Release 29.0.0

- package.json
- packages/snaps-controllers/CHANGELOG.md
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/CHANGELOG.md
- packages/snaps-execution-environments/package.json
- packages/snaps-rpc-methods/CHANGELOG.md
- packages/snaps-rpc-methods/package.json
- packages/snaps-sdk/CHANGELOG.md
- packages/snaps-sdk/package.json
- packages/snaps-simulator/CHANGELOG.md
- packages/snaps-simulator/package.json
- packages/snaps-utils/CHANGELOG.md
- packages/snaps-utils/package.json
Reverts MetaMask/snaps#2106 as the release failed.
> Revert "Release 30.0.0"

- packages/snaps-jest/README.md
This updates the `snaps-jest` documentation to accurately reflect the latest changes.
> Update `snaps-jest` docs

- packages/examples/packages/bip32/package.json
- packages/examples/packages/bip44/package.json
- packages/examples/packages/browserify-plugin/package.json
- packages/examples/packages/browserify/package.json
- packages/examples/packages/client-status/package.json
- packages/examples/packages/cronjobs/package.json
- packages/examples/packages/dialogs/package.json
- packages/examples/packages/errors/package.json
- packages/examples/packages/ethereum-provider/package.json
- packages/examples/packages/ethers-js/package.json
- packages/examples/packages/get-entropy/package.json
- packages/examples/packages/get-file/package.json
- packages/examples/packages/home-page/package.json
- packages/examples/packages/images/package.json
- packages/examples/packages/invoke-snap/packages/consumer-signer/package.json
- packages/examples/packages/invoke-snap/packages/core-signer/package.json
- packages/examples/packages/json-rpc/package.json
- packages/examples/packages/lifecycle-hooks/package.json
- packages/examples/packages/localization/package.json
- packages/examples/packages/manage-state/package.json
- packages/examples/packages/name-lookup/package.json
- packages/examples/packages/network-access/package.json
- packages/examples/packages/notifications/package.json
- packages/examples/packages/rollup-plugin/package.json
- packages/examples/packages/signature-insights/package.json
- packages/examples/packages/transaction-insights/package.json
- packages/examples/packages/wasm/package.json
- packages/examples/packages/webpack-plugin/package.json
Forgot to remove the icons from the `files` field in the package.jsons. This PR rectifies that.
> Remove icons from package.json

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/ui.test.ts
- packages/snaps-utils/src/ui.ts
Adds validation to text that is contained in rows.
> Validate links contained in rows

- packages/examples/packages/interactive-ui/README.md
Removes some unnecessary code formatting in the interactive UI example README.
> Fix interactive-ui example README

- package.json
- scripts/install-chrome.sh
- yarn.lock
Bumps Chromedriver and Chrome version used in CI to latest. Letting me run browser tests locally again.
> Bump Chromedriver

- packages/snaps-jest/src/internals/simulation/interface.test.ts
- packages/snaps-jest/src/internals/simulation/interface.ts
Fixes two issues with the latest version of `snaps-jest`:
- Errors thrown when handling `onUserInput` were not unwrapped properly.
- `ButtonClickEvent` was not triggered when submitting a form. This is a divergence from the client implementation.
> Improve correctness of `clickElement`

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/consumer-signer/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- yarn.lock
Dedupe yarn.lock after merging #2331
> Dedupe yarn.lock

- packages/snaps-controllers/src/cronjob/CronjobController.ts
- packages/snaps-controllers/src/insights/SnapInsightsController.ts
- packages/snaps-controllers/src/interface/SnapInterfaceController.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
> Add missing types for `getState` action & `stateChange` event

- .eslintrc.js
- constraints.pro
- packages/examples/README.md
- packages/examples/packages/preinstalled/.depcheckrc.json
- packages/examples/packages/preinstalled/.eslintrc.js
- packages/examples/packages/preinstalled/CHANGELOG.md
- packages/examples/packages/preinstalled/LICENSE.APACHE2
- packages/examples/packages/preinstalled/LICENSE.MIT0
- packages/examples/packages/preinstalled/README.md
- packages/examples/packages/preinstalled/jest.config.js
- packages/examples/packages/preinstalled/package.json
- packages/examples/packages/preinstalled/scripts/generate-json.mts
- packages/examples/packages/preinstalled/snap.config.ts
- packages/examples/packages/preinstalled/snap.manifest.json
- packages/examples/packages/preinstalled/src/components/dialog.tsx
- packages/examples/packages/preinstalled/src/components/index.ts
- packages/examples/packages/preinstalled/src/index.test.ts
- packages/examples/packages/preinstalled/src/index.tsx
- packages/examples/packages/preinstalled/tsconfig.json
- packages/test-snaps/package.json
- packages/test-snaps/src/features/snaps/index.ts
- packages/test-snaps/src/features/snaps/preinstalled/Preinstalled.tsx
- packages/test-snaps/src/features/snaps/preinstalled/constants.ts
- packages/test-snaps/src/features/snaps/preinstalled/index.ts
- yarn.lock
This adds an example demonstrating preinstalled Snaps.
> Add preinstalled example Snap

- packages/examples/packages/preinstalled/scripts/generate-json.mts
- packages/snaps-cli/src/webpack/plugins.ts
- packages/snaps-cli/src/webpack/utils.ts
- packages/snaps-jest/src/environment.ts
- packages/snaps-jest/src/helpers.ts
- packages/snaps-rpc-methods/src/permitted/experimentalProviderRequest.test.ts
- packages/snaps-rpc-methods/src/permitted/getFile.test.ts
- packages/snaps-rpc-methods/src/permitted/invokeKeyring.test.ts
- packages/snaps-rpc-methods/src/permitted/invokeSnapSugar.test.ts
- packages/snaps-rpc-methods/src/permitted/requestSnaps.test.ts
- packages/snaps-rpc-methods/src/restricted/dialog.test.tsx
- packages/snaps-rpc-methods/src/restricted/invokeSnap.test.ts
- packages/snaps-sdk/src/internals/jsx.ts
- packages/snaps-sdk/src/ui/builder.ts
- packages/snaps-simulation/src/simulation.ts
- packages/snaps-simulator/src/contexts/SnapInterface.tsx
- packages/snaps-simulator/src/features/simulation/sagas.ts
- packages/snaps-simulator/src/features/status/StatusIndicator.tsx
- packages/snaps-utils/src/virtual-file/toVirtualFile.test.ts
- packages/snaps-webpack-plugin/src/plugin.ts
This fixes lint violations caused by the `prettier/prettier` rule.
This PR does not contain any functional changes, only formatting changes.
> Fix `prettier/prettier` errors

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/images/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/signature-insights/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/snaps-browserify-plugin/src/plugin.ts
- packages/snaps-browserify-plugin/src/types/vendor/readable-stream.d.ts
- packages/snaps-controllers/coverage.json
- packages/snaps-jest/src/internals/server.test.ts
- packages/snaps-jest/src/matchers.ts
- packages/snaps-jest/src/test-utils/response.ts
- packages/snaps-jest/src/test-utils/snap/snap.manifest.json
- packages/snaps-simulation/src/files.test.ts
- packages/snaps-simulator/package.json
- packages/snaps-simulator/src/features/builder/utils.ts
- yarn.lock
This fixes some tests that are failing after ESLint 9 changes, and updates example shasums.
> Fix tests and other minor issues

- package.json
- packages/test-snaps/CHANGELOG.md
- packages/test-snaps/package.json
This reverts commit c557f074faadcd455efb63429829fba3c7d55eee.
> Revert "Release 92.0.0 (#3190)"

- package.json
- packages/test-snaps/package.json
> chore: revert "release: `101.0.0`"

- README.md
Update the graph in the README following https://github.com/MetaMask/snaps/pull/3372
> chore: Update README graph

- packages/snaps-controllers/src/websocket/WebSocketService.ts
- packages/snaps-rpc-methods/src/endowments/keyring.test.ts
> fix: typos in function and comments

- packages/snaps-controllers/src/multichain/MultichainRouter.ts
- packages/snaps-utils/src/base64.ts
Description:
This pull request corrects minor typos in code comments and documentation:
- Fixed "procotol" to "protocol" in MultichainRouter.ts
- Fixed "coercable" to "coercible" in base64.ts
> fix: Fix typos in documentation and code comments

- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/location/npm.ts
Description:  
This pull request corrects minor typos in code comments for improved clarity and accuracy.
> fix: Minor Typo Fixes in Comments
