- package.json
- packages/controllers/package.json
- packages/rpc-methods/package.json
- packages/workers/package.json
The `prepare` scripts would cause `yarn lint` and `yarn build` to run in each project when installing dependencies. This is pointless and frustrating. They have been replaced by `prepublishOnly` scripts that run before publishing each package, ensuring that they are all properly built.
> Replace `prepare` scripts with `prepublishOnly`

- packages/controllers/src/plugins/PluginController.test.ts
- packages/controllers/src/plugins/PluginController.ts
`_startPlugin` is the private wrapper function used to start plugins in the `PluginController`. This PR moves the check for whether the requested plugin is already running from the public `startPlugin` to `_startPlugin`, so that this check is always done. A test case is added to test this check.
While we're here, also fixes plugin controller state initialization and makes the state constructor argument property optional.
> Move `isRunning` check from startPlugin to _startPlugin

- packages/controllers/src/plugins/PluginController.test.ts
- packages/controllers/src/services/WebWorkerExecutionEnvironmentService.test.ts
- packages/controllers/src/services/WebWorkerExecutionEnvironmentService.ts
#19 removed the plugin metadata parameter from `setupWorkerConnection`. That function is actually used to setup to plugin provider connection (it ultimately calls `setupUntrustedCommunication` in the extension background, see [here](https://github.com/MetaMask/metamask-snaps-beta/blob/f069030/app/scripts/metamask-controller.js/#L1752-L1757)), and it needs at least the plugin name in order to do that.
This PR renames `setupWorkerConnection` to `setupPluginProvider` – which actually describes what it does – and adds a `pluginName` parameter.
> Fix plugin provider setup function

- .github/workflows/build-lint-test.yml
- package.json
- packages/controllers/package.json
- packages/iframe-execution-environment-service/CHANGELOG.md
- packages/iframe-execution-environment-service/package.json
- packages/rpc-methods/package.json
- packages/types/package.json
- packages/workers/package.json
- yarn.lock
Makes the following changelog-related fixes:
- Adds changelog lint scripts to the root manifest and all packages
- Adds changelog linting to CI
- Adds an empty changelog to the `iframe-execution-environment-service` package
> Add changelog linting to CI, fix changelog issues

- package.json
- packages/controllers/package.json
- packages/iframe-execution-environment-service/package.json
- packages/rpc-methods/package.json
- packages/types/package.json
- packages/workers/package.json
Adds a `publish` script with prepublish steps to the root manifest, and aliases for `npm publish` to all packages.
> Add publish scripts to all packages

- package.json
The root manifest publish script can't be `publish` because `yarn` will hit the builtin `publish` command. This PR renames the script.
> Fix root manifest publish script

- packages/controllers/package.json
- packages/iframe-execution-environment-service/package.json
- packages/rpc-methods/package.json
- packages/types/package.json
- packages/workers/package.json
The `publishConfig` of all packages has been updated to point to the npm registry.
> Fix publishConfig of all packages

- packages/iframe-execution-environment-service/src/IframeExecutionEnvironmentService.test.ts
- packages/iframe-execution-environment-service/src/IframeExecutionEnvironmentService.ts
- scripts/test-ci.sh
- yarn.lock
This PR adds a bit of cleanup to the lifecycle of the plugin and handles errors across the wire for `executePlugin`.
depends on: https://github.com/MetaMask/iframe-execution-environment/pull/19
> Added JSON-RPC error support for iframe execution environment `executePlugin`

- packages/controllers/package.json
- packages/controllers/src/plugins/PluginController.ts
- yarn.lock
Adds the latest `@metamask/controllers`. This version adds the controller messenger type as a generic to `BaseControllerV2`, so the `PluginController` had to be updated to be made compatible.
As a follow-up, we should also do #65.
> @metamask/controllers@15.0.0

- README.md
- package.json
- packages/controllers/README.md
- packages/controllers/package.json
- packages/controllers/src/plugins/PluginController.test.ts
- packages/controllers/src/plugins/PluginController.ts
- packages/controllers/src/services/ExecutionEnvironmentService.ts
- packages/controllers/src/services/WebWorkerExecutionEnvironmentService.test.ts
- packages/controllers/src/services/WebWorkerExecutionEnvironmentService.ts
- packages/iframe-execution-environment-service/README.md
- packages/iframe-execution-environment-service/package.json
- packages/iframe-execution-environment-service/src/IframeExecutionEnvironmentService.ts
- packages/rpc-methods/README.md
- packages/rpc-methods/package.json
- packages/rpc-methods/src/permitted/common/pluginInstallation.ts
- packages/rpc-methods/src/permitted/enable.ts
- packages/rpc-methods/src/permitted/getPlugins.ts
- packages/rpc-methods/src/permitted/invokePluginSugar.ts
- packages/rpc-methods/src/restricted/invokePlugin.ts
- packages/rpc-methods/src/restricted/manageAssets.ts
- packages/types/README.md
- packages/types/package.json
- packages/workers/README.md
- packages/workers/package.json
- packages/workers/src/PluginWorker.ts
- scripts/test-ci.sh
- yarn.lock
This scopes packages under the `@metamask` npm org and renames them so that their names make sense under this org (e.g., `@mm-snap/controllers` becomes `@metamask/snap-controllers`).
> Rename and scope packages under @metamask npm org

- packages/controllers/src/services/WebWorkerExecutionEnvironmentService.ts
- packages/iframe-execution-environment-service/package.json
- packages/iframe-execution-environment-service/src/IframeExecutionEnvironmentService.test.ts
- packages/iframe-execution-environment-service/src/IframeExecutionEnvironmentService.ts
- yarn.lock
This adds out of band error support to the IframeExecutionEnvironmentService and WebWorkerEnvironmentService via the `onError` constructor argument.
Note: I'm unable to add the tests for this, I'm hitting this issue around handling uncaught/unhandled errors: https://github.com/facebook/jest/issues/5620
> Added out of band error support

- packages/controllers/package.json
- packages/iframe-execution-environment-service/package.json
- packages/rpc-methods/package.json
- packages/snap-examples/package.json
- packages/snaps-cli/package.json
- packages/types/package.json
- packages/workers/package.json
- scripts/publish-package.sh
Package `prepublishOnly` scripts were not being run since we switched to using the `./scripts/publish-packages.sh` script to publish packages. This PR renames `prepublishOnly` scripts to `publish:prep`, and explicitly calls it in the `publish` script we define in each package manifest, much like we do with e.g. `build` and `build:prep`.
> Fix publish scripts

- package.json
- packages/controllers/package.json
- packages/controllers/test-ci.sh
- packages/iframe-execution-environment-service/package.json
- packages/rpc-methods/package.json
- packages/snap-examples/package.json
- packages/snaps-cli/package.json
- packages/types/package.json
- packages/workers/package.json
This PR fixes our CI test scripts to ensure that we in fact run all unit tests in CI, which is probably a good thing to do as professional software developers.
> Fix CI test scripts

- packages/controllers/src/plugins/PluginController.test.ts
- packages/controllers/src/plugins/PluginController.ts
- packages/controllers/src/services/WebWorkerExecutionEnvironmentService.test.ts
- packages/controllers/src/services/WebWorkerExecutionEnvironmentService.ts
- packages/iframe-execution-environment-service/src/IframeExecutionEnvironmentService.test.ts
- packages/iframe-execution-environment-service/src/IframeExecutionEnvironmentService.ts
- packages/types/index.d.ts
This adds a feature to the `PluginController` to stop unresponsive plugins, currently each `Service` defaults to polling every 5s to see if `ping` returns within 30s and will fire an `unresponsive` event if not fulfilled.
> Add poll for status webworker

- packages/controllers/src/plugins/PluginController.test.ts
- packages/controllers/src/plugins/PluginController.ts
- packages/controllers/src/services/WebWorkerExecutionEnvironmentService.ts
This adds a timer to check if a plugin has been idling too long. defaults to checking every 5 seconds if any plugins have been idle for 30 seconds.
Also adds `status` to the plugin state, which can be `idle`, `running`, `stopped`, or `crashed`.
> Added max idle time

- packages/controllers/src/plugins/PluginController.test.ts
- packages/controllers/src/plugins/PluginController.ts
This adds the ability to start a plugin on-demand by calling its RpcMessageHandler. It also stores the handlers in a map as a cache to not create too many anonymous functions.
Fixes #111
> Added start on-demand inside rpcMessageHandler

- packages/rpc-methods/package.json
- packages/rpc-methods/src/restricted/getBip44Entropy.ts
- yarn.lock
This PR changes the return value `wallet_getBip44Entropy_*` to a `@metamask/key-tree@^3.0.0` wrapper object, instead of sending just the key material over the wire. This will allow consumers to derive their keys in a safer manner.
`@metamask/key-tree` has been updated to the latest version.
> rpc-methods: Make wallet_getBip44Entropy_* implementation safer

- packages/rpc-methods/tsconfig.json
This PR fixes an incorrectly configured `typeRoots` property in the `tsconfig.local.json` of `@metamask/rpc-methods`.
> rpc-methods: Fix tsconfig.local.json

- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/src/utils.ts
This PR fixes two bugs related to installing and executing snaps:
1. When a snap was installed, we would return `null` from `getSerializable` inside `processRequestedPlugin` instead of going through the installation flow.
2. An error in the boolean expression used to determine whether to stop "idle" plugins in `_stopSnapsLastRequestPastMax` caused plugins to be terminated under incorrect conditions.
> Fix Snap execution and installation bugs

- packages/controllers/CHANGELOG.md
- packages/iframe-execution-environment-service/CHANGELOG.md
Some entries in the 0.3.0 were in fact breaking, but weren't marked as such. This PR marks them as breaking.
> Fix 0.3.0 changelog entries

- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
This guards against a snap being able to get on-demand booted from the `idle` state.
One note is that `idle` should maybe be renamed to `added` in the future.
> Changed on demand boot to not boot when idle

- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
This PR changes the "initial" snap state (per the snap status state machine config) from `idle` to `installing`, and changes the state of rehydrated snaps to `stopped`.
When the Snap controller is initialized on application startup, no snap will be running. This state of "not running" is no different from that of a snap that has been shut down after not processing any requests for too long, and it is therefore appropriate to use `stopped` in both case.
This leaves the only case for the "initial" state as the period between the serialized snap object being added to controller state and it being started for the first time after its initial permissions have been approved. The snap is not "idle" during this time, but the application is making the necessary changes to execute it. Therefore, …
> Refactor Snap initial states

- packages/controllers/src/services/WebWorkerExecutionEnvironmentService.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/iframe-execution-environment-service/src/IframeExecutionEnvironmentService.ts
This adds the feature of having a max request time for RPC requests going to snaps as an option to the SnapsController. If they take too long (60s by default), they will be shut down.
This also somewhat unrelated cleans up the timeouts happening in the Execution Environment Services.
Closes #58
> Added max request time + clean up ExecutionEnvironmentService timeouts on terminate

- packages/rpc-methods/src/permitted/common/snapInstallation.ts
- packages/rpc-methods/src/permitted/enable.ts
- packages/rpc-methods/src/permitted/getAppKey.ts
- packages/rpc-methods/src/permitted/getSnaps.ts
- packages/rpc-methods/src/permitted/installSnaps.ts
- packages/rpc-methods/src/permitted/invokeSnapSugar.ts
- packages/rpc-methods/src/restricted/clearState.ts
- packages/rpc-methods/src/restricted/confirm.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.ts
- packages/rpc-methods/src/restricted/getState.ts
- packages/rpc-methods/src/restricted/invokeSnap.ts
- packages/rpc-methods/src/restricted/manageAssets.ts
- packages/rpc-methods/src/restricted/updateState.ts
- packages/rpc-methods/types/index.d.ts
The `methodDescription` and `permissionDescription` properties of the RPC method handler exports are a UX antipattern in that they are difficult to localize. This PR replaces them with docstrings for each handler export instead.
> Replace RPC method description properties with docstrings

- .github/workflows/build-lint-test.yml
- packages/snaps-cli/package.json
Adds a CI job to build and test `snaps-cli` on Windows and MacOS. Also changes the Ubuntu version for other jobs to `-latest`.
> Add platform compatibility tests to CI

- packages/controllers/src/index.ts
- packages/controllers/src/subject-metadata/SubjectMetadataController.test.ts
- packages/controllers/src/subject-metadata/SubjectMetadataController.ts
- packages/controllers/src/subject-metadata/index.ts
The extension permission metadata functionality is currently housed within its local permissions controller. This PR extracts this functionality into a new "subject" (previously known as "domain") metadata controller, per [the extension implementation](https://github.com/MetaMask/metamask-extension/blob/0d63aa04021142a18b7e1aefce9d060ece364340/app/scripts/controllers/permissions/index.js/#L521-L563).
> Add SubjectMetadataController

- packages/controllers/src/permissions/Caveat.ts
- packages/controllers/src/permissions/Permission.ts
Adds missing permission controller docstrings and removes a redundant caveat-related type. Also makes some miscellaneous documentation touch-ups.
> Finish permission controller docstrings, remove redundant type

- .eslintrc.js
- packages/controllers/src/permissions/Caveat.ts
- packages/controllers/src/permissions/Permission.ts
- packages/iframe-execution-environment-service/src/IframeExecutionEnvironmentService.ts
- packages/rpc-methods/src/index.ts
- packages/rpc-methods/src/permitted/common/snapInstallation.ts
- packages/rpc-methods/src/permitted/enable.ts
- packages/rpc-methods/src/permitted/getAppKey.ts
- packages/rpc-methods/src/permitted/getSnaps.ts
- packages/rpc-methods/src/permitted/installSnaps.ts
- packages/rpc-methods/src/restricted/confirm.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.ts
- packages/rpc-methods/src/restricted/index.ts
- packages/rpc-methods/src/restricted/invokeSnap.ts
- packages/rpc-methods/src/restricted/manageState.ts
- packages/rpc-methods/types/index.d.ts
- packages/snaps-cli/src/cli.ts
- packages/snaps-cli/src/cmds/build/bundleUtils.test.ts
- packages/snaps-cli/src/cmds/build/bundleUtils.ts
- packages/snaps-cli/src/cmds/eval/workerEval.test.ts
- packages/snaps-cli/src/cmds/init/initUtils.test.ts
- packages/snaps-cli/src/cmds/serve/serve.test.ts
- packages/snaps-cli/src/cmds/watch/watch.test.ts
- packages/snaps-cli/src/types/package.d.ts
- packages/snaps-cli/src/types/yargs.d.ts
- packages/snaps-cli/src/utils/readline.ts
- packages/types/index.d.ts
- packages/workers/src/SnapWorker.ts
Updates all methods in `packages/rpc-methods/src/restricted` to match the new permissions system. Instead of "handlers", each method now exports a permission specification "builder", which contains the permission target key of the method, a specification builder function that returns a specification object for the permission, and the names of hooks used by the permission method implementation, validator, and / or factory functions. Types for the builders have been added to the permissions controller for both permissions and caveats, although no caveat builders are added at this time.
So, tl;dr, "builders" are much like "handlers" except compatible with the new permissions system.
Finally, I ran into trouble with some `interface` types in dependencies and locally, so the ESLint config now …
> Update restricted RPC methods per new permissions system

- packages/controllers/package.json
- packages/iframe-execution-environment-service/package.json
- yarn.lock
Use `@metamask/obs-store@7.0.0` everywhere. We already listed it as a dependency in the iframe execution environment, but it wasn't used. The only remaining usage is in `@metamask/snap-controllers`, which is now updated.
> @metamask/obs-store@7.0.0

- packages/controllers/src/subject-metadata/SubjectMetadataController.test.ts
- packages/controllers/src/subject-metadata/SubjectMetadataController.ts
Makes the subject metadata `name` property optional. We already decided to treat it this way in the extension.
> Make subject metadata "name" optional

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
This PR increases `SnapController` test readability and succinctness by adding test helper functions similar to those used in the `PermissionController` tests.
> Clean up SnapController tests

- packages/controllers/jest.config.js
- packages/controllers/src/permissions/Caveat.ts
- packages/controllers/src/permissions/Permission.ts
- packages/controllers/src/permissions/PermissionController.test.ts
- packages/controllers/src/permissions/PermissionController.ts
- packages/controllers/src/permissions/README.md
- packages/controllers/src/permissions/errors.test.ts
- packages/controllers/src/permissions/errors.ts
- packages/rpc-methods/src/restricted/confirm.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.ts
- packages/rpc-methods/src/restricted/invokeSnap.ts
- packages/rpc-methods/src/restricted/manageState.ts
Introduces the notion of permission types to the `PermissionController`, and adds "Endowment" permissions. Invoking these permissions required a new method and action, `PermissionController.getEndowments` and `PermissionController:getEndowments`, respectively. See the updated `PermissionController` README and linked issue for details.
Here is the description of endowment permissions, from said README:
The name "endowment" comes from the endowments that you may provide to a [Secure EcmaScript (SES) `Compartment`](https://github.com/endojs/endo/tree/26d991afb01cf824827db0c958c50970e038112f/packages/ses#compartment) when it is constructed.
SES endowments are simply names that appear in the compartment's global scope.
In the context of the `PermissionController`, endowments are simply …
> Add "Endowment" permissions

- packages/rpc-methods/src/restricted/confirm.ts
During review of the implementation, we discovered some issues with the naming of the parameters for `snap_confirm` method. This PR converts the parameters to an object format, updates their names and descriptions, and adds validation for each field. Each field remains a string, and the maximum length of each field was chosen after experimenting with various text lengths in the extension UI. The `textAreaContent` length of 1800 was chosen because this is roughly the character count of a single, U.S. letter-sized page of double-spaced 12pt Times New Roman, i.e. way more than anyone is going to read in practice anyway.
> Update `snap_confirm` parameters

- packages/snaps-cli/package.json
- packages/snaps-cli/src/cmds/eval/eval-worker.ts
- packages/workers/bundle.js
- packages/workers/package.json
- packages/workers/src/SnapWorker.ts
- yarn.lock
Bumps `ses` to the latest version, `0.15.3`, and updates the `lockdown` configuration per [the extension](https://github.com/MetaMask/metamask-extension/blob/f9ea9e4b432176d940001365938aa88253d54024/app/scripts/lockdown-run.js#L4-L10). This necessitated refactoring how the `SnapWorker` is bundled, as part of which the `--watch` mode for bundling was removed. It's unclear if that ever worked anyway.
> ses@0.15.3

- packages/controllers/src/permissions/endowments/index.ts
- packages/controllers/src/permissions/index.test.ts
- packages/controllers/src/permissions/index.ts
- packages/rpc-methods/src/index.ts
This renames the permission specification builder exports. Especially the endowment permission builder export was previously in an awkward format (had to be imported as `endowmentBuilders.builders`).
> Rename permission builder exports

- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
This PR removes the `svgIcon` property from the `Snap` interface and stops storing it in state. Instead, the `svgIcon` is emitted with the `snapAdded` event. This change is to avoid storing potentially large SVG icons in state in multiple places (in our usage, both the `SnapController` and `SubjectMetadataController`).
> Remove svgIcon property from Snap state

- .gitattributes
- .github/workflows/build-lint-test.yml
- packages/example-snap/snap.manifest.json
- packages/snaps-cli/scripts/publish-prep.sh
- scripts/publish-all.sh
- scripts/publish-package.sh
This PR fixes the git working tree checks made in building and publishing scripts. These checks are supposed to cause CI and publishing to npm to fail if any working tree file has changed during building / publishing preparations. `$(git diff --quiet) != ''`  is unreliable for this purpose, while checking the exit code via `! git diff --exit-code` is much more (completely?) reliable, and logs the offending diff as well. Also updates the repository-wide `.gitattributes` file to force `LF` as the line break character in all files, to prevent us from getting different Snap checksums on different OS's. (I'm not entirely sure why that works but, it certainly stopped CI from failing!)
> Fix git working tree checks

- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
Previously, `disableSnap` would error because if called on a stopped snap, because it called `stopSnap` without checking if it was running first. `stopSnap` errors if the Snap is already running so that we fail early if we abuse it, as we did in this case.
> Added guard for stop error in disableSnap

- packages/snap-examples/examples/bls-signer/snap.manifest.json
- packages/snap-examples/examples/ethers-js/snap.manifest.json
- packages/snaps-cli/package.json
- packages/snaps-cli/src/cmds/build/bundleUtils.ts
- yarn.lock
Original comment by @MakMuftic:
Based on the discussion https://github.com/ChainSafe/filsnap/pull/88 and some further investigation, I realized that the problem origin is inside the library used for stripping comments. The problem occurs if there are double quotes inside the comment, and this issue has been created inside `strip-comments` lib (https://github.com/jonschlinkert/strip-comments/pull/49). Unfortunately, this PR with the fix is stale for some time now, so inside our fork of snaps-cli we used a forked version of `strip-comments` library.
In this PR I replaced `strip-comments` with our [fork](https://github.com/NodeFactoryIo/strip-comments) that:
- fixes a bug with double quotes inside the comment
- already contains types, so no need for importing them
> Fix strip-comments

- packages/example-snap/snap.manifest.json
- packages/snap-examples/examples/bls-signer/snap.manifest.json
- packages/snap-examples/examples/ethers-js/snap.manifest.json
- packages/snap-examples/examples/ipfs/snap.manifest.json
- packages/snaps-cli/package.json
- packages/snaps-cli/src/cmds/build/bundle.test.ts
- packages/snaps-cli/src/cmds/build/bundle.ts
- yarn.lock
Enables the use of ESM modules in Snap source code by adding `babelify` to the Browserify bundle call, which transpiles `import`/`export` statements down to their CommonJS equivalents.
Closes #77
> Enable bundling ESM source code with `mm-snap build`

- packages/snaps-cli/package.json
- patches/init-package-json+1.10.3.patch
- yarn.lock
The `src` value (i.e. `packageJson.main`) should default to `src/index.js`, however we were defaulting to `index.js` because that is the default in the package we use to build the `package.json` file, `init-package-json`. This PR ensures that this value defaults to `src/index.js` by means of a one-line patch to `init-package-json`. `patch-package` was added as a `devDependency` to support this.
> Fix `mm-snap init` `src` default value

- packages/controllers/src/permissions/PermissionController.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
Adds `SnapController` actions for methods that are used by other controllers. Adds unit tests for the same.
> Add SnapController actions

- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/src/snaps/utils.test.ts
- packages/controllers/src/snaps/utils.ts
Changes the hardcoded npm registry to be configurable. We need to use cf registry as a param only in firefox to avoid CORs errors on firefox. see https://github.com/npm/feedback/discussions/117#discussioncomment-1925610 for more information.
> Changed npm registry to be configurable

- packages/controllers/src/snaps/SnapController.ts
Returns `null` from `getSnapState` if the snap has no state. Previously it returned `undefined`, which we'd then have to convert to `null` when we return it to snaps that get their persisted state.
> Return `null` from `getSnapState` if there is no state

- packages/snaps-cli/src/cmds/build/bundle.test.ts
- packages/snaps-cli/src/cmds/build/bundle.ts
As reported in #206, `mm-snap build` fails with an error reporting that `babelify` cannot be found if the CLI is installed globally. In local testing, I can reproduce this behavior with both `yarn` and `npm`. The cause of this error has something to do with the way Browserify and / or Babel resolve dynamically imports their various transforms, presets, and plugins. By importing all of these statically using `require` instead of passing their names as string literals, the "module not found" error disappears.
I considered bundling the CLI as an alternative, but that appears to be difficult precisely due to the dynamic imports that caused the problem in the first place.
To test this manually, build this branch, run `npm pack`, install the resulting tarball globally using `npm install -g …
> Fix `mm-snap build` command when CLI is installed globally

- packages/controllers/package.json
- packages/controllers/src/permissions/rpc-methods/requestPermissions.test.ts
- packages/iframe-execution-environment-service/package.json
- packages/rpc-methods/package.json
- packages/snap-examples/examples/bls-signer/snap.manifest.json
- packages/types/package.json
- yarn.lock
Bumps `@metamask/controllers` to cersion `25.1.0` in all packages. Also removes an unused dependency, `rpc-cap`.
This update required changing two permission RPC method test cases because `@metamask/controllers` changed its error serialization to preserve `error.stack`.
> @metamask/controllers@25.1.0

- packages/controllers/src/snaps/SnapController.ts
Combines the several maps used to keep track of information in `SnapsController` into a single map.
Closes #208
> Snap Runtime Management refactor

- packages/snaps-cli/src/builders.ts
- packages/snaps-cli/src/cmds/build/bundleUtils.test.ts
- packages/snaps-cli/src/cmds/build/bundleUtils.ts
- packages/snaps-cli/src/cmds/build/index.ts
- packages/snaps-cli/src/cmds/watch/index.ts
- packages/snaps-cli/src/types/yargs.d.ts
A user recently reported that their snap bundle was rejected by SES due to HTML-like comments appearing in a transitive dependency. This PR restores our aggressive handling of this problem by default, with an option of disabling it. We will follow up this PR with the ability to add user-specified transforms to the `mm-snap build` process.
> Restore HTML comment transform

- packages/snaps-cli/src/builders.ts
Sets the `--stripComments` option to `true` by default for `mm-snap build` and `watch`. Comments often contain problematic stuff and there's no reason not to do this by default.
> Remove comments by default

- packages/snap-examples/examples/wasm/snap.manifest.json
- packages/snap-examples/examples/wasm/src/index.js
This change lets you call wasm methods from the snaps api:
> Changed wasm snap to pass through to call wasm methods

- packages/rpc-methods/src/restricted/index.ts
- packages/rpc-methods/src/restricted/notify.ts
Add `snap_notify`  to be used with `RateLimitController` for native browser notifications
> Snap Notification RPC method

- packages/snaps-cli/jest.config.js
- packages/snaps-cli/src/cmds/build/utils.test.ts
- packages/snaps-cli/src/cmds/build/utils.ts
While working with a snap locally I discovered that `@nodefactory/strip-comments` fails to handle block comments of the form `/**/`. When it encounters this string, it will remove the `/**/` token and the entire remainder of the string being operated on. This PR fixes this bugs by manually stripping block comments of this form.
> Fix comment stripping bug

- packages/execution-environments/package.json
It was missing the `publish` command, which is necessary for the monorepo-wide publishing workflow.
> Add missing publish command to execution-environments

- packages/execution-environments/package.json
- packages/execution-environments/src/common/BaseSnapExecutor.ts
- packages/types/index.d.ts
- packages/types/package.json
- yarn.lock
Removes the deprecated `@metamask/inpage-provider` in favor of the latest `@metamask/providers` package. The functionality should be identical.
> @metamask/providers@8.1.1

- packages/snaps-cli/package.json
- packages/snaps-cli/src/cmds/build/utils.test.ts
- packages/snaps-cli/src/cmds/build/utils.ts
- yarn.lock
Bumps `@nodefactory/strip-comments` to version `1.0.4`. This allows us to remove our janky handling of empty block comments of the form `/**/` during comment stripping in the `snaps-cli` build process.
> @nodefactory/strip-comments@1.0.4

- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/src/snaps/utils.test.ts
- packages/controllers/src/snaps/utils.ts
Fixes a number of issues that were found when using the latest build with the Filecoin Snap.
- Adds backwards compatibility for versions defined as `latest` (do we want that?)
- Fixes a recently introduced issue with fetching NPM packages via `cross-fetch`
- Fixes a bug where Snaps couldn't be completely removed and got stuck in limbo if you cancelled while being in the process of adding a snap
- This happened because `RevokeAllPermissions` throws if permissions haven't been added yet
> Latest build bug fixes

- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
This PR ensures that the `jsonrpc` field of JSON-RPC request objects is valid before forwarding the object to the Snap via its RPC handler. If the field is missing entirely, we simply populate it with the string `2.0`. If the field exists and has any other value than the string `2.0`, we throw an error.
This is change is due to more stringent validation of these requests added to execution environments in #231. This is probably a good thing, so we update the `SnapController` to match.
> Populate `jsonrpc` field in Snap RPC requests

- packages/execution-environments/package.json
Removes a `postinstall` script in `snaps-cli` that causes installation to break for consumers due to its reliance on a development dependency.
> Remove faulty postinstall script

- packages/execution-environments/jest.config.js
- packages/execution-environments/src/common/endowments/index.test.ts
- packages/execution-environments/src/common/endowments/index.ts
This PR fixes function endowments with properties in our Snap execution environments. Previously, values with a type of `"function"` would be added to the endowments object as `value.bind(globalThis)`. We failed to realize that this would erase the own properties of values like `Date`, leading to e.g. `Date.now` being undefined inside the child Compartment. We really should `harden` the entire endowments object, but this causes tests to fail. In order to resolve the immediate problem, we simply add all global values to the endowments object as-is for now.
> Stop binding function endowments to root globalThis

- packages/cli/jest.config.js
- packages/cli/src/cmds/eval/mock.ts
- packages/execution-environments/jest.config.js
- packages/execution-environments/src/common/endowments/index.ts
As it turns out, we don't want to `.bind` constructors, but we _do_ want to bind plain functions. This turned out to be a more interesting problem than any reasonable person would expect, but we think we have a working solution.
cc: @FrederikBolding
> Bind functions but not constructors

- packages/cli/src/cmds/eval/mock.ts
- packages/controllers/src/services/WebWorkerExecutionService.test.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/src/snaps/default-endowments.ts
- packages/controllers/src/snaps/index.ts
This PR moves the default endowments constant into its own file. This will allow us to easily reference the default endowments and use that file as our single source of truth, for example in documentation.
> Move default endowments into own file

- packages/execution-environments/jest.config.js
- packages/execution-environments/src/common/endowments/index.test.ts
- packages/execution-environments/src/common/endowments/wasm.test.ts
- packages/execution-environments/src/common/endowments/wasm.ts
Closes #333 
Ensures that our `WebAssembly` endowment factory includes non-enumerable properties from the root `WebAssembly` global and updates our tests to cover this case.
> Fix WebAssembly endowment

- packages/cli/CHANGELOG.md
- packages/controllers/CHANGELOG.md
- packages/examples/CHANGELOG.md
- packages/execution-environments/CHANGELOG.md
- packages/iframe-execution-environment-service/CHANGELOG.md
- packages/rpc-methods/CHANGELOG.md
- packages/types/CHANGELOG.md
The 10.7.0 changelogs were missing "breaking" notices. The meaning of one entry was also clarified.
> Fix 10.7.0 changelogs

- package.json
- packages/cli/package.json
- packages/cli/src/cmds/eval/workerEval.test.ts
- packages/controllers/package.json
- packages/examples/package.json
- packages/execution-environments/package.json
- packages/iframe-execution-environment-service/package.json
- packages/rpc-methods/package.json
- tsconfig.packages.json
- yarn.lock
This is needed for preparation of upgrading `@metamask/controllers` to version `27.x`. It upgraded it's dependency of `@ethereumjs/common` to a version which includes typing not supported by TS 4.3, resulting in `TS1336 (An index signature parameter type cannot be a type alias)` error during compilation.
Upgrading to TS 4.4 (4.6.3 in yarn.lock) fixes this issue
> Upgraded TypeScript version to minimum 4.4

- packages/controllers/src/snaps/SnapController.ts
Closes #255
The Snap Controller didn't have many `console.logs` (only two).
> changed console.logs to console.info

- packages/controllers/jest.config.js
- packages/controllers/package.json
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/src/snaps/utils.ts
- packages/iframe-execution-environment-service/package.json
- packages/rpc-methods/package.json
- packages/types/package.json
- yarn.lock
To be merged alongside https://github.com/MetaMask/controllers/pull/764
> Use PermissionController:revokePermissionForAllSubjects

- packages/examples/examples/wasm/snap.config.js
- packages/examples/examples/wasm/snap.config.json
The WASM example was not using the new snap config format
> Fix WASM example config

- packages/rpc-methods/src/permitted/getAppKey.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.ts
Waits for unlock before fetching entropy, because the entropy is unavailable when the extension is locked. Potentially other RPC methods need the same functionality.
Fixes #355
> Wait for unlock on some RPC methods

- packages/rpc-methods/src/permitted/enable.ts
Fixes #348
Removes unnecessary prompt for permissions by checking whether existing permissions satisfy the requested permissions
> Fix prompting for existing permissions

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.ts
Fixes #384 
Fixes an issue with the current idle time out implementation where a snap could be terminated while executing a request. This is fixed by keeping track of how many requests are currently being executed and only updating the `lastRequest` value once the final request has finished.
> Fix idle timeout implementation

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.ts
Adds a `snapTerminated` event that we can use for teardown. It is emitted whenever we terminate the snap, either because it is unresponsive or has failed to initialize. We decided to implemented this event instead of `snapStopped` because we aren't confident that a snap cannot cause side effects during initialization, before its state has transitioned.
Progresses https://github.com/MetaMask/metamask-extension/issues/14494
> Emit `snapTerminated` event

- packages/controllers/jest.config.js
- packages/controllers/src/services/AbstractExecutionService.ts
- packages/controllers/src/services/iframe/IframeExecutionService.ts
Fixes #394 
Removes an unnecessary timeout, since we are now timing out if initialization takes too long.
> Remove `_createWindowTimeout`

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- Reset `pendingRequests` to prevent an issue where snaps would never be terminated due to inactivity
- Small refactor of `_executeWithTimeout` to stop using `stopSnap` because this does nothing on install
> Reset `pendingRequests` and refactor `_executeWithTimeout`

- packages/controllers/src/services/AbstractExecutionService.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
Renames the `endowmentPermissionNames` constructor argument to `environmentEndowmentPermissions`. Also renames the underlying private property to match. Finally, adds docstrings to constructor arguments.
> BREAKING: Rename SnapController constructor argument

- package.json
- yarn.lock
Closes #362.
This adds a pre-commit hook using `simple-git-hooks` which calls `lint-staged`. It will then lint any staged files using the appropriate lint tools. It has been configured to match the behaviour of the `yarn lint:fix` command.
> Add pre-commit lint hook

- packages/controllers/jest.config.js
- packages/controllers/package.json
- packages/controllers/src/services/WebWorkerExecutionService.test.ts
- packages/controllers/src/services/iframe/IframeExecutionService.test.ts
- packages/controllers/src/services/iframe/testHelpers/server.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/execution-environments/package.json
- packages/execution-environments/src/iframe/index.html
- packages/execution-environments/webpack.config.js
- yarn.lock
- **BREAKING:** Changes the structure of the output of the `execution-environments` build process, to among other things include the `index.html`.
- Spins up a local server to run `IframeExecutionService` tests
> BREAKING: Run `IframeExecutionService` tests locally + `execution-environment` build changes

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/src/snaps/endowments/constants.ts
- packages/controllers/src/snaps/endowments/index.ts
- packages/controllers/src/snaps/endowments/long-running.test.ts
- packages/controllers/src/snaps/endowments/long-running.ts
Adds a permission for endowing snaps with infinite request processing time.
Fixes #430
> Add long-running endowment permission

- packages/rpc-methods/package.json
- packages/rpc-methods/src/restricted/getBip44Entropy.ts
- yarn.lock
This bumps `@metamask/key-tree` to the latest version. The format of `JsonBIP44CoinTypeNode` has changed, so this is a breaking change.
> BREAKING: Bump `@metamask/key-tree` to 4.0.0

- packages/examples/examples/bls-signer/package.json
- packages/examples/examples/bls-signer/snap.manifest.json
- packages/examples/examples/bls-signer/yarn.lock
- packages/examples/examples/ethers-js/package.json
- packages/examples/examples/ethers-js/snap.manifest.json
- packages/examples/examples/ethers-js/yarn.lock
- packages/examples/examples/ipfs/package.json
- packages/examples/examples/ipfs/snap.manifest.json
- packages/examples/examples/ipfs/yarn.lock
- packages/examples/examples/notifications/package.json
- packages/examples/examples/notifications/snap.manifest.json
- packages/examples/examples/notifications/yarn.lock
- packages/examples/examples/wasm/package.json
- packages/examples/examples/wasm/snap.manifest.json
- packages/examples/examples/wasm/yarn.lock
- packages/examples/scripts/buildExamples.js
Closes #445.
This changes how examples are built using the `buildExamples.js` script. Rather than calling the CLI directly using `node ../path/to/cli.js`, it runs `yarn build` in each example folder. The CLI is installed locally through a local `file:` dependency (since the examples aren't part of the workspace).
Unfortunately we have to install the dependencies for the examples sequentially, which slows down CI a little bit. Otherwise the Yarn cache would get corrupted.
> Build examples by running yarn build in each example

- packages/controllers/package.json
- packages/execution-environments/package.json
- packages/plugin-browserify/package.json
- packages/plugin-rollup/package.json
- packages/plugin-webpack/package.json
- packages/utils/package.json
Yarn 3 does not support pre and post scripts and as such has broken our usage of `jest-it-up`. This PR fixes this.
> Fix `jest-it-up` after Yarn 3 upgrade

- packages/cli/package.json
- packages/examples/examples/ethers-js/snap.manifest.json
- packages/utils/package.json
- yarn.lock
Fixes #432 
Rewrote quoted string regex to prevent issues with very large strings.
See: https://github.com/ChainSafe/strip-comments/pull/9
> @chainsafe/strip-comments@1.0.7

- packages/cli/package.json
- packages/controllers/package.json
- packages/examples/examples/bls-signer/package.json
- packages/examples/examples/ethers-js/package.json
- packages/examples/examples/ipfs/package.json
- packages/examples/examples/notifications/package.json
- packages/examples/examples/typescript/package.json
- packages/examples/examples/wasm/package.json
- packages/execution-environments/package.json
- packages/plugin-browserify/package.json
- packages/plugin-rollup/package.json
- packages/plugin-webpack/package.json
- packages/rpc-methods/package.json
- packages/utils/package.json
yarn build:clean wouldn't work because it expands globs like `*.tsbuildinfo`
automatically inside it's shell before passing it down into the program provided
in script. If the expanded glob is empty, it would return an exit code of 1 and
not run the script. This would cause build:clean to only try to clean (and fail)
and not run build at all.
> Fix yarn clean / build:clean not working on yarn 3

- packages/execution-environments/jest.config.js
- packages/execution-environments/src/common/endowments/timeout.ts
This PR picks up https://github.com/MetaMask/snaps-skunkworks/pull/475
Kris Kowal from Agoric suggested that our current implementation violates POLA. With this change, we no longer return the platform handle, but instead return an opaque token. An analogous change will be made for interval endowments.
> Fix timer leak

- packages/execution-environments/jest.config.js
- packages/execution-environments/src/common/endowments/interval.ts
This PR addresses a concern brought up by Kris Kowal from Agoric in #475 for timeouts. Platform handles are also leaked in our current implementation of interval, this updates it to instead return opaque tokens.
> Fix interval handle leak

- packages/cli/package.json
- yarn.lock
This is now included via `utils` and therefore doesn't need to be specified as a direct dependency.
> Remove strip-comments as a direct dependency of the CLI

- .github/workflows/build-lint-test.yml
Thanks to helpful people in https://github.com/yarnpkg/berry/issues/2389, I found a way to speed up our CLI platform compatibility tests by only building the CLI and its dependents, as opposed to every package in the repository.
With a sample size of one, this appears to shave 2 minutes off of the build time on Windows and 1 minute on macOS. The tl;dr is that the platform tests are no longer the bottleneck in CI.
> Only build the CLI and its dependents for platform tests

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/src/snaps/utils.test.ts
- packages/controllers/src/snaps/utils.ts
Fixes #504 
Allows version ranges to include prereleases, moves more semver handling to tested utility functions, use prerelease versions if no other matching versions are found.
> Allow matching with prerelease versions

- packages/examples/examples/typescript/package.json
- packages/examples/examples/typescript/snap.manifest.json
- packages/examples/examples/typescript/src/index.ts
- packages/types/src/types.d.ts
- yarn.lock
Updates TypeScript example to use exported type `OnMessageHandler`.
Fixes #524
> Update TypeScript example to use `OnMessageHandler`

- packages/cli/src/cmds/eval/eval-worker.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/examples/.eslintrc.js
- packages/examples/examples/bls-signer/snap.manifest.json
- packages/examples/examples/bls-signer/src/index.js
- packages/examples/examples/ethers-js/snap.manifest.json
- packages/examples/examples/ethers-js/src/index.js
- packages/examples/examples/ipfs/snap.manifest.json
- packages/examples/examples/ipfs/src/index.js
- packages/examples/examples/notifications/snap.manifest.json
- packages/examples/examples/notifications/src/index.js
- packages/examples/examples/rollup/snap.manifest.json
- packages/examples/examples/rollup/src/snap.ts
- packages/examples/examples/typescript/snap.manifest.json
- packages/examples/examples/typescript/src/index.ts
- packages/examples/examples/wasm/snap.manifest.json
- packages/examples/examples/wasm/src/index.js
- packages/examples/examples/webpack/snap.manifest.json
- packages/examples/examples/webpack/src/snap.ts
- packages/execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/execution-environments/src/common/BaseSnapExecutor.ts
- packages/types/src/types.d.ts
Fixes #532 
Renames `onMessage` to `onRpcMessage` and uses named parameters instead of positional ones.
> BREAKING: Rename `onMessage` to `onRpcMessage` and use named parameters

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/utils.test.ts
- packages/controllers/src/snaps/utils.ts
Strips the leading `./` from the values of path fields in `snap.manifest.json` of npm snaps. Although this is not [according to spec](https://github.com/MetaMask/specifications/blob/main/snaps/publishing.md#filepath), we do it by the principle of "be lenient about what you receive and stringent about what you send out". We do no extend this courtesy for locally developed snaps because it's better for the issues to be caught and addressed.
> Strip leading `./` from paths in npm snap manifests

- packages/cli/src/cmds/eval/eval-worker.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/examples/examples/bls-signer/snap.manifest.json
- packages/examples/examples/bls-signer/src/index.js
- packages/examples/examples/ethers-js/snap.manifest.json
- packages/examples/examples/ethers-js/src/index.js
- packages/examples/examples/ipfs/snap.manifest.json
- packages/examples/examples/ipfs/src/index.js
- packages/examples/examples/notifications/snap.manifest.json
- packages/examples/examples/notifications/src/index.js
- packages/examples/examples/rollup/snap.manifest.json
- packages/examples/examples/rollup/src/snap.ts
- packages/examples/examples/typescript/snap.manifest.json
- packages/examples/examples/typescript/src/index.ts
- packages/examples/examples/wasm/snap.manifest.json
- packages/examples/examples/wasm/src/index.js
- packages/examples/examples/webpack/snap.manifest.json
- packages/examples/examples/webpack/src/snap.ts
- packages/execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/execution-environments/src/common/BaseSnapExecutor.ts
- packages/types/src/types.d.ts
Renames the Snap `onRpcMessage` export to `onRpcRequest`. The underlying type, `SnapRpcHandler` takes a single named parameter object with two properties, `origin` and `request`. Since the "message" is a "request" both by the parameter name and the JSON-RPC 2.0 specification (even if the request is technically a notification), we should use "request" for the export name as well.
> Rename `onRpcMessage` to `onRpcRequest`

- packages/cli/src/cmds/build/bundle.test.ts
- packages/cli/src/cmds/build/bundle.ts
@david0xd discovered that the bundle commands were broken with a globally installed `mm-snap`, because `browserify` couldn't resolve our plugin. This PR fixes that issue.
> Fix bundle command when running globally installed mm-snap

- packages/cli/package.json
- packages/controllers/package.json
- packages/execution-environments/package.json
- packages/plugin-browserify/package.json
- packages/plugin-rollup/package.json
- packages/plugin-webpack/package.json
- packages/rpc-methods/package.json
- packages/types/package.json
- packages/utils/package.json
- scripts/publish-all.sh
Since the Yarn v3 migration, `yarn` and/or `npm` has run the `publish` script twice whenever `publish:all` is run from the root. The first time it succeeds, the second time it fails due to the `OTP` positional variable not being specified, leading me to believe that this is occurring due to some lifecycle / naming collision issue.
This PR renames the `publish` script in workspace `package.json` files to `publish:package` in order to stop `yarn` from running the script twice. I haven't tested this, but it (1) can't hurt, (2) is less confusing because there's no naming collision with the `yarn` / `npm` CLI `publish` command, and (3) follows the convention established by the monorepo root `publish:all` script.
> Rename package `publish` command to `publish:package`

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/rpc-methods/src/restricted/invokeSnap.ts
In the future we may not be able to return a function via `ControllerMessenger` actions. For this reason we should stop exposing `getRpcMessageHandler` and instead expose a handle function such as `handleRpcMessage`.
> BREAKING: Replace `getRpcMessageHandler` action with `handleRpcMessage`

- packages/cli/src/cmds/eval/mock.ts
- packages/controllers/src/services/AbstractExecutionService.ts
- packages/controllers/src/services/ExecutionService.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/rpc-methods/src/restricted/invokeSnap.ts
We recently decided to use "request" instead "message" terminology for the Snap `onRpcRequest` export, and this PR ensures that we use this preferred terminology everywhere. This PR contains no functional changes.
> Rename "rpcMessage" to "rpcRequest"

- packages/examples/examples/bls-signer/snap.manifest.json
- packages/examples/examples/bls-signer/src/index.js
- packages/examples/examples/browserify/gulpfile.ts
- packages/examples/examples/browserify/src/snap.ts
- packages/examples/examples/ethers-js/src/index.js
- packages/examples/examples/ipfs/snap.manifest.json
- packages/examples/examples/ipfs/src/index.js
- packages/examples/examples/ipfs/src/ipfs.js
- packages/examples/examples/notifications/src/index.js
- packages/examples/examples/rollup/rollup.config.js
- packages/examples/examples/rollup/snap.manifest.json
- packages/examples/examples/rollup/src/index.ts
- packages/examples/examples/rollup/src/snap.ts
- packages/examples/examples/typescript/src/index.ts
- packages/examples/examples/typescript/src/message.ts
- packages/examples/examples/wasm/assembly/program.ts
- packages/examples/examples/wasm/snap.manifest.json
- packages/examples/examples/wasm/src/index.js
- packages/examples/examples/webpack/snap.manifest.json
- packages/examples/examples/webpack/src/index.ts
- packages/examples/examples/webpack/src/snap.ts
This adds a JSDoc comment to all functions in the `packages/examples` folder. There were a few minor typos in some examples as well, which I fixed.
> Add JSDoc documentation to all examples

- packages/plugin-browserify/src/plugin.test.ts
- packages/plugin-browserify/src/plugin.ts
- packages/plugin-rollup/src/plugin.ts
- packages/plugin-webpack/src/plugin.ts
This adds JSDoc comments to the bundler plugins (Rollup, Webpack, Browserify). Some functions were already documented in @rekmarks' PR (#560), so I skipped those.
> Add JSDoc documentation to bundler plugins

- packages/rpc-methods/src/permitted/common/snapInstallation.ts
- packages/rpc-methods/src/permitted/getAppKey.ts
- packages/rpc-methods/src/permitted/getSnaps.ts
- packages/rpc-methods/src/permitted/installSnaps.ts
- packages/rpc-methods/src/permitted/invokeSnapSugar.ts
- packages/rpc-methods/src/restricted/confirm.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.ts
- packages/rpc-methods/src/restricted/invokeSnap.ts
- packages/rpc-methods/src/restricted/manageState.ts
- packages/rpc-methods/src/restricted/notify.ts
Add JSDoc strings for all functions in `rpc-methods` except for `enable` which is covered by another PR.
> Add JSDoc strings to `rpc-methods`

- packages/controllers/scripts/transpileSchemaTypes.js
- packages/controllers/src/services/AbstractExecutionService.ts
- packages/controllers/src/services/iframe/IframeExecutionService.ts
- packages/controllers/src/services/iframe/test/server.ts
- packages/controllers/src/snaps/RequestQueue.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/src/snaps/endowments/long-running.ts
- packages/controllers/src/snaps/endowments/network-access.ts
- packages/controllers/src/utils.ts
Add JSDoc strings for all functions in `controllers` except for `utils.ts` which is covered by another PR.
> Add JSDoc strings to `controllers`

- packages/execution-environments/src/common/endowments/interval.ts
- packages/execution-environments/src/common/endowments/network.ts
- packages/execution-environments/src/common/endowments/timeout.ts
- packages/execution-environments/src/common/lockdown/lockdown-more.ts
- packages/execution-environments/src/common/lockdown/lockdown.ts
- packages/execution-environments/src/common/sortParams.ts
- packages/execution-environments/src/common/utils.ts
- packages/execution-environments/src/iframe/IFrameSnapExecutor.ts
- packages/execution-environments/src/web-workers/WebWorkerSnapExecutor.ts
- packages/execution-environments/src/web-workers/index.ts
This adds JSDoc comments to the `execution-environments` package. Some functions were already documented in @rekmarks' PR (https://github.com/MetaMask/snaps-skunkworks/pull/560), so I skipped those.
> Add JSDoc documentation to execution-environments

- packages/cli/package.json
- packages/cli/src/cmds/eval/eval-worker.ts
- packages/cli/src/cmds/eval/workerEval.test.ts
- packages/cli/src/cmds/eval/workerEval.ts
- yarn.lock
This PR switches the eval functionality to use `child_process` instead of `worker_threads`, this alleviates a problem where Node.js segfaults when using `mm-snap watch`. This needs testing on other machines than mine and perhaps all the operating systems we support 😅 
Fixes #555
> Fix segfault when using `mm-snap watch`

- packages/cli/src/cmds/build/bundle.test.ts
- packages/cli/src/cmds/build/bundle.ts
- packages/examples/examples/bls-signer/snap.manifest.json
- packages/examples/examples/browserify/snap.manifest.json
- packages/examples/examples/ethers-js/snap.manifest.json
- packages/examples/examples/ipfs/snap.manifest.json
- packages/examples/examples/notifications/snap.manifest.json
- packages/examples/examples/rollup/snap.manifest.json
- packages/examples/examples/typescript/snap.manifest.json
- packages/examples/examples/wasm/snap.manifest.json
- packages/examples/examples/webpack/snap.manifest.json
- packages/plugin-browserify/src/plugin.test.ts
- packages/plugin-rollup/src/__snapshots__/plugin.test.ts.snap
- packages/plugin-webpack/src/__snapshots__/plugin.test.ts.snap
- packages/utils/package.json
- packages/utils/src/post-process.test.ts
- packages/utils/src/post-process.ts
- packages/utils/src/strip.ts
- yarn.lock
Strips comments from the bundle by using the Babel AST instead of `strip-comments`.
> Add potential AST solution for `strip-comments`

- packages/examples/examples/bls-signer/snap.manifest.json
- packages/examples/examples/browserify/snap.manifest.json
- packages/examples/examples/ipfs/snap.manifest.json
- packages/examples/examples/notifications/snap.manifest.json
- packages/examples/examples/rollup/snap.manifest.json
- packages/examples/examples/typescript/snap.manifest.json
- packages/examples/examples/webpack/snap.manifest.json
- packages/utils/src/ast.test.ts
- packages/utils/src/ast.ts
This is a small optimisation to how we process template literals. Rather than always breaking up everything in a template literal if replacement is necessary, this only breaks up the actual parts of the template string that need to be broken up.
For example:
```js
const foo = `<!-- foo ${bar} baz`;
```
Before this change:
```js
const foo = `${"<!"}${"--"}${" "}${bar}${" baz"}`;
```
After this change:
```js
const foo = `${"<!"}${"--"} ${bar} baz`;
```
> Only process template literal quasis if necessary

- packages/utils/src/ast.test.ts
- packages/utils/src/ast.ts
This changes how we create new template elements. Rather than using the same value for `cooked` and `raw`, the raw value is now derived from the cooked value. This ensures that certain characters are interpreted properly in the template element.
> Properly provide template element raw value

- packages/controllers/jest.config.js
- packages/controllers/src/services/AbstractExecutionService.ts
- packages/controllers/src/services/ExecutionService.ts
- packages/controllers/src/services/iframe/IframeExecutionService.test.ts
- packages/controllers/src/services/iframe/IframeExecutionService.ts
- packages/controllers/src/services/node/NodeProcessExecutionService.test.ts
- packages/controllers/src/services/node/NodeThreadExecutionService.test.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/types/src/types.d.ts
Remove all functions passed to the `SnapController` constructor. This PR replaces all of these functions with use of the messenger system. Most constructor functions have been added to the `ExecutionService` and a few will have to be added to the MetaMaskController in the extension.
Fixes #484
> BREAKING: Remove ExecutionService actions from constructor arguments

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
Removes permission revoking etc from `authorize` which is not used since all permissions logic is handled by `updateSnap`. Furthermore, changes the shape of the snap update approval `requestData` to be closer to snap installation, by doing this we can simplify our UI implementation.
> Refactor Update Snap slightly

- packages/controllers/package.json
- packages/execution-environments/package.json
- packages/execution-environments/webpack.config.js
- yarn.lock
Bump `post-message-stream` to `6.0.0`. The previous version had problems building in Browserify and would be a problem in the extension.
> Bump `post-message-stream`

- packages/controllers/jest.config.js
- packages/controllers/package.json
- packages/controllers/src/services/browser.test.ts
- packages/controllers/src/services/browser.ts
Adds a browser entrypoint for execution services that omits Node.js execution services.
Fixes #627
> BREAKING: Add browser entrypoint for execution services

- packages/controllers/src/services/node/NodeProcessExecutionService.test.ts
- packages/controllers/src/services/node/NodeThreadExecutionService.test.ts
- packages/execution-environments/jest.config.js
- packages/execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/execution-environments/src/common/BaseSnapExecutor.ts
Fixes issues with error serialization by partly reverting back to old implementation but with a few tweaks to fix issues with unhandled promise rejections. Furthermore, adds tests for the BaseSnapExecutor error handling.
> Fix error serialization issues

- packages/cli/src/cmds/serve/serve.test.ts
- packages/cli/src/cmds/serve/serveHandler.ts
When we try to install a snap on localhost metamask tries to fetch the snap.manifest.json file. Since the request comes from Metamask to a server that doesn’t respond with "Acces-Control-Allow-Origin" header the request is not allowed by the CORS browser policy.
I think that it should be fine to set 'Access-Control-Allow-Origin' to '*', becasue the cli and the serve command are intended for developer use and it shouldn’t be seen as a security issue.
fixes https://github.com/MetaMask/snaps-skunkworks/issues/635
> Add 'Access-Control-Allow-Origin': * to serve

- packages/controllers/jest.config.js
- packages/controllers/src/services/AbstractExecutionService.test.ts
- packages/controllers/src/services/AbstractExecutionService.ts
- packages/controllers/src/services/iframe/IframeExecutionService.ts
- packages/execution-environments/jest.config.js
- packages/execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/execution-environments/src/common/BaseSnapExecutor.ts
- packages/execution-environments/src/common/commands.ts
`BaseSnapExecutor.notify()` was sending invalid [JSON-RPC notifications](https://www.jsonrpc.org/specification#notification) to the execution service over the command stream. This PR ensures that only valid notifications are sent.
> Send valid JSON-RPC notifications from executors

- packages/rpc-methods/package.json
- packages/rpc-methods/src/restricted/manageState.ts
- yarn.lock
The main goal of this PR is to enforce JSON serializability of the Snap state and limit its size. 
This PR will introduce new utility functions for JSON sizing and validation implemented here: https://github.com/MetaMask/utils/pull/14
Fix: https://github.com/MetaMask/snaps-skunkworks/issues/209
Fixes: #571
> Add new validation and limit for storage

- packages/utils/src/manifest.test.ts
- packages/utils/src/manifest.ts
Fixes an issue in the manifest handling that would cause `mm-snap manifest --fix` to only fix the first error it found.
Fixes #647
> Fix manifest with multiple errors

- packages/controllers/jest.config.js
- packages/controllers/src/services/AbstractExecutionService.test.ts
- packages/controllers/src/services/AbstractExecutionService.ts
- packages/controllers/src/services/ExecutionService.ts
- packages/controllers/src/services/iframe/IframeExecutionService.test.ts
- packages/controllers/src/services/node/NodeProcessExecutionService.test.ts
- packages/controllers/src/services/node/NodeThreadExecutionService.test.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
This PR will refactor `SnapsController` and `Execution` services in order to remove reliance on `getRpcRequestHandler`.
Fixes: https://github.com/MetaMask/snaps-skunkworks/issues/609
> Remove reliance on getRpcRequestHandler

- .gitignore
The 0.19.0 release of @metamask/snaps-cli is missing dist/utils/snap-config.__GENERATED__.js file,
this is because it's in .gitignore which `npm publish` uses.
> Fix mm-snap releasing without generated .js files

- packages/rpc-methods/jest.config.js
- packages/rpc-methods/src/caveats.ts
- packages/rpc-methods/src/restricted/getBip32Entropy.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.test.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.ts
- packages/rpc-methods/src/restricted/getBip44EntropyLegacy.ts
- packages/rpc-methods/src/restricted/index.ts
This adds a new RPC method `snap_getBip44Entropy`. Similar to `snap_getBip32Entropy`, it's implemented using permission caveats, rather than the wildcard permission. This means that one or more coin types must be explicitly requested in the snap manifest like this:
```json
{
"initialPermissions": {
"snap_getBip44Entropy": {
"caveats": [
{
"type": "permittedCoinTypes",
"value": [
{
"coinType": 60
}
]
}
]
}
}
}
```
The method can be used like this:
```ts
await wallet.request({
method: 'snap_getBip44Entropy',
params: {
coinType: 60 // `m/44'/60'`
},
})
```
The old implementation for `snap_getBip44Entropy_*` was moved to `getBip44EntropyLegacy` (while the RPC method name remains the same, for compatibility). A deprecation message will be logged when this method is used, though probably …
> Add `snap_getBip44Entropy` RPC method and deprecate `snap_getBip44Entropy_*`

- packages/controllers/src/fsm.ts
- packages/controllers/tsconfig.json
- packages/utils/jest.config.js
- packages/utils/src/flatMap.test.ts
- packages/utils/src/flatMap.ts
- packages/utils/src/index.ts
The TypeScript compilation target of `snap-controllers` was set to ES2020 which currently clashes with the minimum supported Chrome versions of the MetaMask extension. The extension minimum Chrome version is 66.
This PR also replaces `flatMap` since it is not implemented before ES2019.
> Reduce TypeScript compilation target for `snap-controllers`

- packages/controllers/jest.config.js
- packages/controllers/package.json
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/tsconfig.json
- packages/rpc-methods/jest.config.js
- packages/rpc-methods/package.json
- packages/rpc-methods/src/index.ts
- packages/rpc-methods/src/permitted/common/snapInstallation.ts
- packages/rpc-methods/src/permitted/enable.ts
- packages/rpc-methods/src/permitted/getSnaps.ts
- packages/rpc-methods/src/restricted/getBip32Entropy.test.ts
- packages/rpc-methods/src/restricted/getBip32Entropy.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.test.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.ts
- packages/rpc-methods/src/restricted/index.ts
- packages/rpc-methods/src/restricted/invokeSnap.ts
- packages/rpc-methods/tsconfig.json
- packages/utils/jest.config.js
- packages/utils/package.json
- packages/utils/src/index.ts
- packages/utils/src/object.test.ts
- packages/utils/src/object.ts
- packages/utils/src/snaps.ts
- yarn.lock
This PR adds support for caveat mapping functions, i.e., functions which can take a raw value from the `initialPermissions` as defined in a Snap manifest, and process it to something that can be understood by the `PermissionsController`. This makes it possible to simplify the caveat format as used by `getBip32Entropy` and `getBip44Entropy`. For example, instead of something like this:
```json
{
"initialPermissions": {
"snap_getBip44Entropy": {
"caveats": [
{
"type": "permittedCoinTypes",
"value": [
{
"coinType": 60
}
]
}
]
}
}
}
```
You can now do this instead (open to feedback):
```json
{
"initialPermissions": {
"snap_getBip44Entropy": [
{
"coinType": 60
}
]
}
}
```
Additionally, to remove a dependency on `snap-controllers` from `rpc-methods`, I had to move some stuff around. Most types …
> BREAKING: Simplify manifest format for permission caveats

- packages/types/package.json
- yarn.lock
Update `snap-types` dependencies to be current to what is exported. Removes unused `@metamask/controllers` dependency and moves some dev dependencies to be regular dependencies.
> Fix snap-types dependencies

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.ts
Fixes #726 
Fixes an issue where we would throw when trying to track outbound requests for long-running snaps.
> Only pause running timers

- packages/execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/execution-environments/src/common/commands.ts
- packages/types/src/types.d.ts
Removes `origin` from the parameters exposed to the `onTransaction` export, since the origin of the request always will be MetaMask and not a DApp.
> BREAKING: Remove origin from TX insight payload

- packages/rpc-methods/jest.config.js
- packages/rpc-methods/src/restricted/getBip32Entropy.ts
- packages/rpc-methods/src/restricted/getBip32PublicKey.test.ts
- packages/rpc-methods/src/restricted/getBip32PublicKey.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.ts
- packages/rpc-methods/src/restricted/index.ts
This adds an RPC-method for Snaps to get a public key for a BIP-32 derivation path. The implementation is based on `getBip32Entropy`, and it uses the same permission caveat. Rather than returning the entire SLIP-10 node, it returns the public key, making it safer to use in situations where the private key is not necessary.
Closes #688.
> Add `snap_getBip32PublicKey` RPC method

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
Fixes an issue where Snap permissions wouldn't be processed before snap update, causing invalid caveats.
> Process snap permissions before snap update

- packages/rpc-methods/src/restricted/getBip32Entropy.test.ts
- packages/rpc-methods/src/restricted/getBip32Entropy.ts
This makes it possible to derive child nodes from the specified derivation path in the Snap manifest. For example, if the Snap manifest specifies `m/44'/60'` as a derivation path, it's now possible to derive `m/44'/60'/0'/...` directly with `getBip32Entropy`.
Closes #747.
> Allow deriving child nodes with `getBip32Entropy`

- packages/rpc-methods/src/permitted/getSnaps.ts
The `getSnaps` returns a `Promise`, but since we weren't awaiting it, this resulted in a race condition. In some situations, the `wallet_getSnaps` method would return `{}` before, which is a serialised unresolved Promise.
> Fix race condition in `wallet_getSnaps`

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
Reworks the snap install logic to use a similar pattern to updating snaps. It now uses the ApprovalController directly and grants permissions based on the outcome of the ApprovalController promise.
Fixes #748
> BREAKING: Rework snap install logic

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/utils/jest.config.js
- packages/utils/src/snaps.ts
This PR stops us from including snaps that are in the installing state in the return value of `wallet_getSnaps`. It also introduces a separate `updating` such that updating snaps are included in the return value.
Fixes #764
> Stop including `installing` snaps in `wallet_getSnaps`

- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
Fix: https://github.com/MetaMask/snaps-skunkworks/issues/620
This PR will add changes that are going to extend existing blocklist feature by making possible to block snaps by shasum of their source code.
In the `SnapController.ts` changes are made to the types and arguments that are now containing additional info for `shasum`.
Added type is the `SnapInfo`:
```typescript
type SnapInfo = { version: SemVerVersion; shasum: string };
```
Changed argument `CheckSnapBlockListArg`:
```typescript
type CheckSnapBlockListArg = Record<SnapId, SnapInfo>;
```
`updateBlockedSnaps` and `isBlocked` methods are updated in order to make a new data structure for `CheckSnapBlockListArg` and accept different type of arguments.
`_assertIsUnblocked` is updated as well to match only the argument change.
Example …
> BREAKING: Add changes to support blocking snaps by shasum

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
Adds support for keyring session tracking, allowing snaps with open sessions not to be terminated by the idle timeout.
> Add support for keyring session tracking

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/test-utils/controller.ts
- packages/controllers/src/test-utils/execution-environment.ts
- packages/controllers/src/test-utils/index.ts
- packages/plugin-browserify/src/__snapshots__/plugin.test.ts.snap
- packages/plugin-rollup/src/plugin.test.ts
- packages/plugin-webpack/src/__snapshots__/plugin.test.ts.snap
- packages/utils/jest.config.js
- packages/utils/src/test-utils/snap.ts
This PR does a couple of things:
1. It moves some test utils in the Snap controller tests to a separate file. This makes it possible to re-use them to test other controllers, e.g., the upcoming multi chain controller.
2. It merges test utils used by the Snap controller with test utils in the `utils` package. Most test utils now live inside the `utils` package, and the same ones are used across packages.
3. It simplifies a lot of tests inside the Snap controller, by making use of the new test utils.
> Merge test utils and simplify controller tests

- packages/controllers/src/snaps/SnapController.test.ts
- packages/provider/package.json
- packages/provider/src/MultiChainProvider.ts
- packages/provider/src/Provider.ts
- packages/utils/jest.config.js
- packages/utils/src/assert.test.ts
- packages/utils/src/assert.ts
- packages/utils/src/index.ts
- packages/utils/src/namespace.test.ts
- packages/utils/src/namespace.ts
- packages/utils/src/notification.test.ts
- packages/utils/src/notification.ts
- packages/utils/src/test-utils/manifest.ts
- yarn.lock
`window.ethereum` was untyped (meaning it was `any`), so some things weren't properly type checked in the provider. I added a definition for `window.ethereum`, and fixed any type issues following that. This also adds a struct to validate the notification types, and a new `assertStruct` utility to make the error messages thrown by `superstruct` slightly easier to understand.
> Fix multi chain provider types

- packages/utils/jest.config.js
- packages/utils/src/namespace.test.ts
This adds tests for the previously untested namespace utils (`utils/src/namespace.ts`). The coverage for that file is now at 100%.
> Add tests for namespace utils

- packages/controllers/jest.config.js
- packages/controllers/src/multichain/MultiChainController.ts
- packages/controllers/src/snaps/endowments/keyring.test.ts
- packages/controllers/src/snaps/endowments/keyring.ts
As mentioned by @ritave in #700, there could be possible regression bugs if we change the keyring caveat validation logic. This adds a getter function which does basic validation of the caveat value, to catch any regression bugs.
> Add getter function to validate the keyring caveat

- packages/utils/src/flatMap.ts
The `flatten` and `flatMap` functions were typed using `any` previously, making them not type-safe to use, without casting the value afterwards. This changes it to use generic params, so the proper type is inferred from the input type.
Before this change:
```ts
const foo = flatten([1, [2], 3]);
type Foo = typeof foo; // any
```
After this change:
```ts
const foo = flatten([1, [2], 3]);
type Foo = typeof foo; // number[]
```
This does not change the actual implementation of these functions.
> Improve types and documentation of `flatten` and `flatMap`

- .yarn/patches/init-package-json-npm-1.10.3-83a0bc1ff1.patch
- package.json
- packages/cli/package.json
- yarn.lock
Closes #800.
This removes the need for `patch-package`, by making use of the patch functionality in Yarn 3.
> Replace `patch-package` with Yarn 3 patch

- packages/cli/package.json
- packages/controllers/jest.config.js
- packages/controllers/package.json
- packages/controllers/src/fsm.test.ts
- packages/controllers/src/fsm.ts
- packages/controllers/src/multichain/MultiChainController.ts
- packages/controllers/src/multichain/middleware.ts
- packages/controllers/src/services/AbstractExecutionService.test.ts
- packages/controllers/src/services/AbstractExecutionService.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/src/snaps/Timer.ts
- packages/controllers/src/snaps/endowments/keyring.ts
- packages/execution-environments/jest.config.js
- packages/execution-environments/package.json
- packages/execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/execution-environments/src/common/BaseSnapExecutor.ts
- packages/execution-environments/src/common/commands.ts
- packages/provider/package.json
- packages/rpc-methods/package.json
- packages/utils/jest.config.js
- packages/utils/package.json
- packages/utils/src/assert.test.ts
- packages/utils/src/assert.ts
- yarn.lock
Bumps `@metamask/utils` to `3.1.0`. Includes the new `superstruct` types and validation for JSON-RPC. Also removes `assert` as that has been added to the utils package.
> Bump `@metamask/utils` to `3.1.0`

- packages/rpc-methods/jest.config.js
- packages/rpc-methods/package.json
- packages/rpc-methods/src/index.ts
- packages/rpc-methods/src/restricted/confirm.ts
- packages/rpc-methods/src/restricted/dialog.test.ts
- packages/rpc-methods/src/restricted/dialog.ts
- packages/rpc-methods/src/restricted/index.ts
- yarn.lock
Adds a new restricted RPC method, `snap_dialog`, which is a superset of `snap_confirm` by virtue of supporting:
- alerts, i.e. dialogs with a message and a single OK button
- confirmations, i.e. dialogs with a message and yes/no buttons
- prompts, i.e. dialogs with a text input field and cancel/submit buttons
Once we have an API for creating custom UIs, we can either add a new type, `custom`, or replace these methods completely.
> Add `snap_dialog` method

- packages/controllers/jest.config.js
- packages/controllers/src/multichain/MultiChainController.ts
Asserts that requested RPC methods are actually available in the session before usage.
fixes #812
> Assert that multichain RPC methods are supported before usage

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/src/test-utils/controller.ts
This PR fixes an issue with installing snaps that request `eth_accounts`. 
To create the `eth_accounts` permission, we need the selected accounts from the UI, these are normally passed back in the result of the approval (see https://github.com/MetaMask/metamask-extension/blob/develop/ui/components/app/permission-page-container/permission-page-container.component.js#L90-L109).
`grantPermissions` expects the selected accounts to be in `requestData`, to fix this we can mirror the logic from the PermissionController (what we were using previously): https://github.com/MetaMask/controllers/blob/main/src/permissions/PermissionController.ts#L1861-L1877
This will also need a small change in the extension.
> Fix an issue with installing snaps that request `eth_accounts`

- packages/execution-environments/jest.config.js
- packages/execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/execution-environments/src/common/BaseSnapExecutor.ts
Previously, when a Snap would attempt to send an unserializable response, the stream would close with a cryptic error:
```
Error: PortDuplexStream - disconnected
at PortDuplexStream._write (common-7.js:32090:23)
at doWrite (common-8.js:42947:64)
```
This is because streams cannot serialize non-JSON-compatible values. I've added a check to make sure a response is serializable, and throw an error otherwise. Now, when a Snap tries to send an unserializable response, it will result in a more understandable JSON-RPC error:
```json
{
"code": -32603,
"message": "JSON-RPC responses must be JSON serializable objects"
}
```
> Throw an error when response is unserializable

- packages/rpc-methods/jest.config.js
- packages/rpc-methods/package.json
- packages/rpc-methods/src/restricted/invokeSnap.test.ts
- packages/rpc-methods/src/restricted/invokeSnap.ts
- yarn.lock
Add JSON-RPC request validation for `wallet_invokeSnap`
> Add JSON-RPC validation for invokeSnap

- packages/execution-environments/jest.config.js
- packages/execution-environments/src/common/endowments/network.ts
Fixes missing properties on WebSocket MessageEvent. We were spreading the object instead of navigating the prototype chain to look for the properties, as such, not all properties were correctly copied to the event.
Fixes #836
> Fix missing properties on WebSocket MessageEvent

- .gitignore
- package.json
- packages/examples/examples/bls-signer/index.html
- packages/examples/examples/browserify/index.html
- packages/examples/examples/ethers-js/index.html
- packages/examples/examples/insights/README.md
- packages/examples/examples/insights/index.html
- packages/examples/examples/insights/package.json
- packages/examples/examples/insights/snap.config.js
- packages/examples/examples/insights/snap.manifest.json
- packages/examples/examples/insights/src/index.ts
- packages/examples/examples/insights/src/insights.ts
- packages/examples/examples/insights/tsconfig.json
- packages/examples/examples/ipfs/index.html
- packages/examples/examples/notifications/index.html
- packages/examples/examples/rollup/index.html
- packages/examples/examples/typescript/index.html
- packages/examples/examples/wasm/index.html
- packages/examples/examples/webpack/src/index.html
- yarn.lock
This adds a basic transaction insights example snap, which looks at the transaction data of an arbitrary transaction, and attempts to decode it.
I've also fixed some linting issues on other HTML files.
> Add transaction insights example snap

- packages/utils/package.json
We use `@babel/types` for bundle post processing, but currently it's listed as `devDependency`, meaning it's not installed when installing `@metamask/snap-utils`. I've moved it to the regular dependencies to fix this issue.
Closes #850.
> Make `@babel/types` a regular dependency

- .github/workflows/build-lint-test.yml
- .github/workflows/create-release-pr.yml
- .github/workflows/publish-release.yml
- .github/workflows/require-additional-reviewer.yml
This PR bumps the GitHub actions that we we use to the latest version, removing deprecation notices from our CI.
One thing left to solve is CodeCov, but this is ongoing.
Reference: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> Bump GitHub actions

- packages/provider/src/MultiChainProvider.test.ts
- packages/provider/src/MultiChainProvider.ts
This fixes an issue that breaks the `MultiChainProvider`. Previously it would assume that the responses from MetaMask would be wrapped in the JSON-RPC wrapper, but that is not the case. This PR stops assuming that the responses are wrapped and treats the return value as a direct return value.
> Stop assuming wrapped responses from MetaMask provider

- packages/provider/src/MultiChainProvider.ts
- packages/provider/src/index.ts
Re-exports types used in the MultiChainProvider for easier access by consumers.
Fixes #819
> Export `MultiChainProvider` types

- packages/plugin-webpack/package.json
- packages/plugin-webpack/src/plugin.ts
- yarn.lock
Fixes an issue where already built files would be ignored by the Webpack plugin. This was fixed by using another hook to capture the emit (`afterEmit`), since the previous hook would not be called if the output file already existed.
Fixes #811
> Fix Webpack plugin issue with existing files

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/utils/src/snaps.ts
- packages/utils/src/test-utils/snap.ts
Stops storing the snap source code in the state of the controller, since this causes the source code to be piped to the extension UI every 200ms. With this PR, the source code is instead kept alongside other runtime data, being loaded when the controller spins up and persisted when it spins down.
This will also make it easier for us to store the sourceCode in another format in the near future.
Fixes #859
> Stop including source code in state

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/endowments/keyring.test.ts
- packages/controllers/src/snaps/endowments/keyring.ts
- packages/utils/jest.config.js
- packages/utils/src/assert.test.ts
- packages/utils/src/assert.ts
- packages/utils/src/namespace.test.ts
- packages/utils/src/namespace.ts
Previously, if a Snap would specify an invalid keyring namespace object, we would throw an error like:
```
Expected a valid namespaces object.
```
This does not explain exactly what the issue is. This changes it to throw more descriptive errors, i.e., the errors thrown by Superstruct, but wrapped in a JSON-RPC error. For example:
```
Invalid namespaces object: Expected an object, but received: undefined.
```
> Improve keyring endowment error messaging

- packages/controllers/jest.config.js
- packages/controllers/src/multichain/MultiChainController.test.ts
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
- packages/controllers/src/test-utils/controller.ts
- packages/controllers/src/test-utils/multichain.ts
This PR turns `SnapController.add()` into a private method `_add()` and removes its associated action. Due to the extensive use of this method in tests, a new `SnapController` persisted state factory is added to our test utilities and used instead of `add()`. Overall unit tests coverage has decreased slightly due to the removal of tested code.
> Make `SnapController.add()` private

- packages/controllers/jest.config.js
- packages/controllers/package.json
- packages/controllers/src/cronjob/CronjobController.test.ts
- packages/controllers/src/cronjob/CronjobController.ts
- packages/controllers/src/snaps/endowments/cronjob.test.ts
- packages/controllers/src/snaps/endowments/cronjob.ts
- packages/controllers/src/snaps/endowments/enum.ts
- packages/controllers/src/snaps/endowments/index.ts
- packages/controllers/src/test-utils/controller.ts
- packages/execution-environments/jest.config.js
- packages/execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/execution-environments/src/common/commands.ts
- packages/execution-environments/src/common/validation.ts
- packages/plugin-webpack/src/__snapshots__/plugin.test.ts.snap
- packages/types/src/types.d.ts
- packages/utils/jest.config.js
- packages/utils/package.json
- packages/utils/src/caveats.test.ts
- packages/utils/src/caveats.ts
- packages/utils/src/cronjob.test.ts
- packages/utils/src/cronjob.ts
- packages/utils/src/index.ts
- packages/utils/src/types.ts
- yarn.lock
Fixes: https://github.com/MetaMask/snaps-skunkworks/issues/353
Cronjob feature will add new possibility to periodically run specific Snap RPC methods. Cronjob feature is implemented as a new permission with caveats that are used to specify job methods, parameters and schedule using CRON syntax.
For interpretation of a CRON syntax, cron-parser library is added: https://www.npmjs.com/package/cron-parser
`cron-parser` is added as the dependency to the `snap-utils` and `snap-controllers` packages.
New caveat specification is added under the `snap-utils` package inside `cronjob.ts`.
Cronjob feature's core is implemented as the Controller inside CronjobController.ts which is part of `snap-controllers` package.
CronjobController is supposed to be registered in the extension within MetaMask …
> Add snap cronjobs

- packages/controllers/jest.config.js
- packages/controllers/src/snaps/SnapController.test.ts
- packages/controllers/src/snaps/SnapController.ts
Stops including snap state in controller state so it isn't piped to the extension UI. Instead it is stored with runtime information.
> Stop including snap state in controller state

- .github/workflows/publish-release.yml
Use latest major versions of MetaMask CI actions instead of specific versions. This also fixes some deprecation warnings in these actions.
> Bump MetaMask CI actions

- packages/rpc-methods/package.json
- packages/rpc-methods/src/restricted/getBip32Entropy.test.ts
- packages/rpc-methods/src/restricted/getBip32PublicKey.test.ts
- packages/rpc-methods/src/restricted/getBip32PublicKey.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.test.ts
- yarn.lock
`@metmask/key-tree@6.0.0` has a few improvements:
- All hexadecimal values always start with `0x`.
- The package does not use `Buffer` anymore.
This is breaking when working with `[...]Buffer` fields, as these have been renamed to `[...]Bytes`, and are now `Uint8Array`s rather than `Buffer`s. It does not affect typical usage using `getBIP44AddressKeyDeriver`.
> BREAKING: Bump `@metamask/key-tree` to 6.0.0

- yarn.lock
Fixes a dependabot alert by bumping a dev dependency `loader-utils`: https://github.com/advisories/GHSA-76p3-8jx3-jpfq
> Bump `loader-utils` to fix a Dependabot warning

- packages/controllers/package.json
- packages/execution-environments/package.json
- packages/types/package.json
- yarn.lock
Bumps a few MetaMask packages that we rely on. This should allow for better deduplication in the extension.
> Bump a few MetaMask packages

- packages/utils/src/eval-worker.ts
This changes the warning displayed if `onRpcRequest` is not exported to a warning if an invalid export is found.
Fixes: #924
> Add warning if an invalid export is detected

- packages/types/src/types.d.ts
This changes the `onTransactionResponse` type to allow the `insights` object to be null.
Fixes: #901
See: https://github.com/MetaMask/metamask-extension/pull/16416
> Allow insights object to be null in `onTransactionResponse`

- packages/snaps-execution-environments/jest.config.js
- packages/snaps-execution-environments/src/common/endowments/index.test.ts
- packages/snaps-execution-environments/src/common/endowments/index.ts
- packages/snaps-execution-environments/src/common/endowments/math.test.ts
- packages/snaps-execution-environments/src/common/endowments/math.ts
Closes #948.
This adds an endowment factory for `Math`, which replaces the implementation of `Math.random`.
> Add `Math` endowment factory

- packages/snaps-browserify-plugin/src/plugin.test.ts
- packages/snaps-browserify-plugin/src/plugin.ts
- packages/snaps-rollup-plugin/src/plugin.test.ts
- packages/snaps-rollup-plugin/src/plugin.ts
- packages/snaps-utils/src/post-process.test.ts
- packages/snaps-utils/src/post-process.ts
- packages/snaps-webpack-plugin/src/plugin.test.ts
- packages/snaps-webpack-plugin/src/plugin.ts
This adds a `warnings` property to the result of post processing, and adds a warning when `Math.random` is detected in the bundle.
> Show warning when using `Math.random`

- packages/examples/examples/bls-signer/index.html
- packages/examples/examples/browserify/index.html
- packages/examples/examples/ethers-js/index.html
- packages/examples/examples/insights/index.html
- packages/examples/examples/ipfs/index.html
- packages/examples/examples/notifications/index.html
- packages/examples/examples/rollup/src/index.ts
- packages/examples/examples/typescript/index.html
- packages/examples/examples/wasm/index.html
- packages/examples/examples/webpack/src/index.ts
- packages/rpc-methods/src/permitted/requestSnaps.test.ts
Removes usage of `wallet_enable` from the examples.
> Remove `wallet_enable` from examples

- packages/snaps-controllers/jest.config.js
- packages/snaps-controllers/src/services/AbstractExecutionService.test.ts
- packages/snaps-controllers/src/services/AbstractExecutionService.ts
- packages/snaps-controllers/src/services/iframe/IframeExecutionService.ts
- packages/snaps-controllers/src/services/iframe/test/fixJSDOMPostMessageEventSource.ts
- packages/snaps-controllers/src/services/node/NodeProcessExecutionService.ts
- packages/snaps-controllers/src/services/node/NodeThreadExecutionService.ts
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
Stops prefixing a bunch of functions and properties with `_`. Replacing some of them with `#` where possible.
Fixes #887
> Stop prefixing private functions and properties with `_`

- packages/rpc-methods/jest.config.js
- packages/rpc-methods/src/permitted/invokeSnapSugar.test.ts
- packages/rpc-methods/src/permitted/invokeSnapSugar.ts
- packages/rpc-methods/src/restricted/invokeSnap.test.ts
- packages/rpc-methods/src/restricted/invokeSnap.ts
- packages/rpc-methods/src/restricted/manageState.test.ts
- packages/rpc-methods/src/restricted/manageState.ts
- packages/rpc-methods/src/restricted/notify.test.ts
- packages/rpc-methods/src/restricted/notify.ts
This PR will update the way of passing RPC method parameters.
All parameters will now be following the new convention where object-like named parameters are required.
All RPC methods that were accepting parameters as an array `[]` are updated and appropriate tests are added.
Updated are the following methods:
- wallet_snap_*
- snap_manageState
- snap_notify
- wallet_invokeSnap
All of these mentioned and the rest of the untouched methods in this PR require a plain object structure `{}` for passing parameters. 
Fixes: https://github.com/MetaMask/snaps-monorepo/issues/870
> BREAKING: Refactor RPC method params and add tests

- packages/examples/.eslintrc.js
- packages/examples/examples/bls-signer/snap.manifest.json
- packages/examples/examples/bls-signer/src/index.js
- packages/examples/examples/browserify/snap.manifest.json
- packages/examples/examples/browserify/src/snap.ts
- packages/examples/examples/ethers-js/snap.manifest.json
- packages/examples/examples/ethers-js/src/index.js
- packages/examples/examples/notifications/snap.manifest.json
- packages/examples/examples/notifications/src/index.js
- packages/examples/examples/rollup/snap.manifest.json
- packages/examples/examples/rollup/src/snap.ts
- packages/examples/examples/typescript/snap.manifest.json
- packages/examples/examples/typescript/src/index.ts
- packages/examples/examples/webpack/snap.manifest.json
- packages/examples/examples/webpack/src/snap.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/snaps-execution-environments/src/common/endowments/index.test.ts
- packages/snaps-execution-environments/src/common/endowments/index.ts
- packages/snaps-types/global.d.ts
- packages/snaps-utils/src/mock.test.ts
- packages/snaps-utils/src/mock.ts
As per request of @rekmarks we are renaming `snaps` to `snap`.
> BREAKING: Rename `snaps` global object to `snap`

- packages/rpc-methods/jest.config.js
- packages/rpc-methods/src/restricted/getBip32Entropy.test.ts
- packages/rpc-methods/src/restricted/getBip32PublicKey.test.ts
- packages/rpc-methods/src/restricted/getBip32PublicKey.ts
- packages/snaps-utils/src/manifest/validation.ts
`snap_getBip32PublicKey` and `snap_getBip32Entropy` use the same caveat, meaning that the permissions in the Snap manifest should be validated the same. Before, we would validate the `snap_getBip32PublicKey` JSON-RPC params, rather than the caveat.
> Fix `snap_getBip32PublicKey` manifest validation

- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-execution-environments/jest.config.js
- packages/snaps-execution-environments/package.json
- packages/snaps-execution-environments/src/common/endowments/math.ts
- packages/snaps-utils/jest.config.js
- packages/snaps-utils/src/manifest/manifest.test.ts
- packages/snaps-utils/src/manifest/manifest.ts
- packages/snaps-utils/src/object.ts
This is based on some suggestions from @Gudahtt. It simplifies the reducer types in some files, and removes the need for disabling an ESLint rule.
> Simplify reduce types in some files

- packages/snaps-ui/src/builder.test.ts
- packages/snaps-ui/src/builder.ts
- packages/snaps-ui/src/nodes.ts
- packages/snaps-ui/src/validation.test.ts
This implements the base UI types `Parent` and `Literal`, in addition to `Node`.
> Implement base UI types

- package.json
- packages/snaps-controllers/jest.config.js
- packages/snaps-controllers/package.json
- packages/snaps-controllers/src/multichain/MultiChainController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/endowments/enum.ts
- packages/snaps-controllers/src/snaps/endowments/index.ts
- packages/snaps-controllers/src/snaps/endowments/rpc.test.ts
- packages/snaps-controllers/src/snaps/endowments/rpc.ts
- packages/snaps-controllers/src/test-utils/controller.ts
- packages/snaps-utils/src/caveats.ts
- packages/snaps-utils/src/json-rpc.test.ts
- packages/snaps-utils/src/json-rpc.ts
- packages/snaps-utils/src/manifest/validation.ts
- yarn.lock
This adds a new permission `endowment:rpc`, which Snaps need in order to use the `onRpcRequest` handler. It takes an object in order to specify if the Snap can receive JSON-RPC requests from other Snaps, Dapps, or both.
```ts
{
initialPermissions: {
'endowment:rpc': {
snaps: true,
dapps: false, // Default value
}
}
}
```
Closes #855.
> BREAKING: Add JSON-RPC handler permission

- packages/snaps-controllers/jest.config.js
- packages/snaps-controllers/src/snaps/endowments/index.ts
Adds a missing export for `getTransactionOriginCaveat` which will be used in the extension.
> Add transaction origin caveat export

- packages/snaps-ui/src/builder.test.ts
- packages/snaps-ui/src/builder.ts
- packages/snaps-ui/src/nodes.ts
- packages/snaps-ui/src/validation.test.ts
We've decided that the `spacer` component is not in scope for v1 of the custom UI.
> Remove UI spacer

- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
Reverts snap permission processing change that broke non-snap permissions. Also adds a test to catch a potential regression in the future.
Fixes #1043
> Fix non-snap permission processing

- packages/snaps-utils/package.json
Fixes the browser export on `snaps-utils`. Without this change Browserify would pull in our normal bundle in the extension.
> Fix utils browser export

- packages/examples/examples/bls-signer/snap.manifest.json
- packages/examples/examples/browserify/snap.manifest.json
- packages/examples/examples/ethers-js/snap.manifest.json
- packages/examples/examples/insights/snap.manifest.json
- packages/examples/examples/ipfs/snap.manifest.json
- packages/examples/examples/notifications/snap.manifest.json
- packages/examples/examples/rollup/snap.manifest.json
- packages/examples/examples/typescript/snap.manifest.json
- packages/examples/examples/wasm/snap.manifest.json
- packages/examples/examples/webpack/snap.manifest.json
- packages/snaps-browserify-plugin/src/__snapshots__/plugin.test.ts.snap
- packages/snaps-execution-environments/.c8rc.json
- packages/snaps-execution-environments/.gitignore
- packages/snaps-execution-environments/ava.config.js
- packages/snaps-execution-environments/jest.config.js
- packages/snaps-execution-environments/package.json
- packages/snaps-execution-environments/src/common/endowments/timeout.ava.test.ts
- packages/snaps-rollup-plugin/src/plugin.test.ts
- packages/snaps-utils/src/post-process.test.ts
- packages/snaps-webpack-plugin/src/__snapshots__/plugin.test.ts.snap
- yarn.lock
This PR will add tools and configurations which will provide a new way of unit testing using AVA test runner which is primarily added because of testing SES functionalities.
Fixes: https://github.com/MetaMask/snaps-monorepo/issues/1016
`ava` - AVA test runner.
`@ava/typescript` - TypeScript support for AVA test runner.
`c8` - Test coverage reporter recommended for AVA, using v8.
`mkdirp` - Cross platform `mkdir`. Used to merge and regenerate coverage report.
`nyc` - Used to merge and regenerate coverage report.
`shx` - Cross platform solution for `cp` used when copying files is needed to merge coverage report.
`test:ava` - This will run only AVA tests. This script is used in the main `test` script. It can be useful when working only on AVA tests or testing security (SES) related parts of …
> Add AVA test runner integration

- packages/snaps-controllers/jest.config.js
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/location/http.test.ts
- packages/snaps-controllers/src/snaps/location/http.ts
- packages/snaps-controllers/src/snaps/location/local.test.ts
- packages/snaps-controllers/src/snaps/location/npm.test.ts
- packages/snaps-controllers/src/snaps/location/npm.ts
- packages/snaps-controllers/src/test-utils/location.ts
- packages/snaps-controllers/src/utils.test.ts
- packages/snaps-controllers/src/utils.ts
- packages/snaps-utils/src/index.browser.ts
- packages/snaps-utils/src/index.ts
- packages/snaps-utils/src/manifest/validation.test.ts
- packages/snaps-utils/src/manifest/validation.ts
- packages/snaps-utils/src/path.test.ts
- packages/snaps-utils/src/path.ts
This PR stops prefixing paths internally with `./`. It also adds SnapManifest coercing that normalizes the bundle and icon paths to be non-prefixed.
> Hotfix for SnapLocation paths being wrongly normalized

- packages/snaps-execution-environments/src/common/endowments/index.test.ts
- packages/snaps-execution-environments/src/common/endowments/index.ts
In production we were accidentally using `globalThis.ethereum` instead of our limited EIP-1193 provider. This PR fixes that by moving an if-statement.
> Fix usage of wrong `ethereum` object for `ethereum` endowment

- .github/workflows/build-lint-test.yml
This doesn't seem necessary anymore now that we can test the CLI without building it first.
> Remove platform compatibility build

- .github/workflows/build-lint-test.yml
- jest.config.base.js
- packages/rpc-methods/jest.config.js
- packages/snaps-cli/jest.config.js
- packages/snaps-controllers/jest.config.js
- packages/snaps-execution-environments/jest.config.js
- packages/snaps-utils/jest.config.js
Change coverage provider to hopefully improve reliability of code coverage numbers.
The previously selected coverage provider seemed to be counting type information as lines covered.
Also add CodeCov reporting for controllers and ignore test-utils in coverage.
> Prefer Babel for Jest coverage

- packages/examples/examples/insights/package.json
- packages/examples/examples/insights/snap.manifest.json
- packages/examples/examples/insights/src/index.ts
- packages/snaps-ui/tsconfig.build.json
- packages/snaps-ui/tsconfig.json
- packages/snaps-utils/package.json
- packages/snaps-utils/src/handlers.ts
- packages/snaps-utils/tsconfig.build.json
- packages/snaps-utils/tsconfig.json
- yarn.lock
Prerequisite for https://github.com/MetaMask/metamask-extension/issues/16523
> BREAKING: Use custom UI in transaction insights

- packages/rpc-methods/src/restricted/manageState.ts
Fix missing `snap_manageState` method hooks.
> Fix `snap_manageState` method hooks

- packages/rpc-methods/src/restricted/manageState.test.ts
- packages/rpc-methods/src/restricted/manageState.ts
Fixes `snap_manageState` throwing in case of empty state.
> Fix `snap_manageState` with empty state

- packages/snaps-execution-environments/jest.config.js
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
Add proxy for `ethereum` global so a snap cannot access the internals of the object. We instead only allow access to our custom `request` function as well as EIP-1193 defaults.
> Add proxy for `ethereum` global

- packages/rpc-methods/package.json
- yarn.lock
Pulls in update to `@metamask/key-tree` in which BIP-39 implementation is updated from `@scure/bip39` to MetaMask fork version `@metamask/scure-bip39`. The `@metamask/scure-bip39` fork accepts secret recovery phrases in `Uint8Array` format making it possible to use more secure patterns of passing secret recovery phrases around. This change is non-breaking however, as the mnemonicToSeed function used in this package still accepts secret recovery phrases in string format.
Even before Snaps switches to passing SRPs as Uint8Arrays this change will be useful by unifying the extension on one BIP-39 implementation reducing redundant code.
> Bump `@metamask/key-tree` version

- packages/snaps-controllers/src/snaps/location/npm.ts
Adds safety measure for large tarballs, reduces recursion limit for `gunzip` and adds some comments regarding tarball security. 
Also restores error handling for errors that occur in the tarball stream.
Fixes https://github.com/MetaMask/MetaMask-planning/issues/272
> Add safety measures for malicious tarballs 

- packages/snaps-controllers/jest.config.js
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/location/location.test.ts
- packages/snaps-controllers/src/snaps/location/location.ts
Disallows `local` snaps by default, requiring a feature flag to be enabled for them to be installable.
Fixes #896
> BREAKING: Disallow local snaps by default

- packages/snaps-controllers/jest.config.js
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
Require `location` for calls to `updateSnap` to reduce code duplication. Also prevents an issue with the correct configuration not being passed to `detectSnapLocation`
> Require `location` for `SnapController.updateSnap`

- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
Required for: #1103 & #990
Uses a record of permissions with their associated error to forbid usage of according permissions. The list is passed to the controller params for ease of use between Flask and other versions.
> Make `authorize()` throw on excluded permissions

- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
Progresses: #1103
`console.warn()` a deprecation warning if a snap with `endowment:long-running` is started.
> Add `endowment:long-running` deprecation warning

- packages/snaps-utils/src/index.browser.ts
Somehow between versions we were missing the export for the cronjob utilities, this fixes that. It was not missing in the currently released version of Flask.
> Fix missing cronjob export

- packages/rpc-methods/package.json
- packages/rpc-methods/src/restricted/getBip32Entropy.test.ts
- packages/rpc-methods/src/restricted/getBip32Entropy.ts
- packages/rpc-methods/src/restricted/getBip32PublicKey.test.ts
- packages/rpc-methods/src/restricted/getBip32PublicKey.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.test.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.ts
- packages/rpc-methods/src/restricted/getEntropy.test.ts
- packages/rpc-methods/src/restricted/getEntropy.ts
- packages/rpc-methods/src/restricted/manageState.test.ts
- packages/rpc-methods/src/restricted/manageState.ts
- packages/rpc-methods/src/utils.test.ts
- packages/rpc-methods/src/utils.ts
- packages/snaps-utils/package.json
- packages/snaps-utils/src/test-utils/common.ts
- yarn.lock
This bumps `key-tree` to the latest version, and replaces any usage of secret recovery phrase strings with `Uint8Array`s.
- The `getMnemonic` hook has been changed everywhere to only accept `Uint8Array`s as return value.
> BREAKING: Bump `key-tree` to 6.2.0 and use `Uint8Array` for secret recovery phrases

- packages/snaps-execution-environments/jest.config.js
- packages/snaps-execution-environments/src/common/endowments/date.test.ts
- packages/snaps-execution-environments/src/common/endowments/date.ts
- packages/snaps-execution-environments/src/common/endowments/index.test.ts
- packages/snaps-execution-environments/src/common/endowments/index.ts
- packages/snaps-execution-environments/src/common/endowments/interval.ts
- packages/snaps-execution-environments/src/common/endowments/timeout.ts
Added a custom Date endowment where:
- The Date.now() function has added noise as to limit its precision (down to 1 ms) and prevent potential timing attacks.
- The Date constructor uses this now() function to seed itself if no arguments are given to the constructor.
Also set a minimum value for `setTimeout` and `setInterval` to be at least `10` ms.
Fixes #211
> Constrain Date and timeouts

- packages/rpc-methods/src/restricted/invokeSnap.ts
Apologies for the one-line doc PR 😬
> Fix typo in documentation

- packages/rpc-methods/package.json
- packages/rpc-methods/src/restricted/getBip32Entropy.test.ts
- packages/snaps-utils/package.json
- yarn.lock
This bumps `@metamask/key-tree` to the latest version, to fix a regression bug introduced in version 6.2.0.
> Bump `@metamask/key-tree` to 6.2.1

- packages/snaps-rollup-plugin/src/plugin.test.ts
The `sources` part of a source map can change depending on the environment, causing instability in the test in some cases. Since it's not an important part of the test, it can be removed from the snapshot.
> Improve Rollup test stability

- package.json
- packages/snaps-controllers/package.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/registry/json.test.ts
- packages/snaps-controllers/src/snaps/registry/json.ts
- packages/snaps-controllers/src/snaps/registry/registry.ts
- packages/snaps-controllers/src/test-utils/controller.ts
- packages/snaps-controllers/src/test-utils/registry.ts
- yarn.lock
This adds a new function `getRegistryMetadata` to the `SnapController` in order to get metadata for verified snaps.
Prerequisite for MetaMask/MetaMask-planning#298.
> Add method to get metadata from the Snaps registry

- packages/rpc-methods/src/restricted/manageState.test.ts
- packages/rpc-methods/src/restricted/manageState.ts
Closes #1207.
To make the JSON-RPC methods easier to work with, we allow both enums and plain string values where applicable. Unfortunately, `snap_manageState` was not changed to allow this before, so I have fixed it.
> Accept string operation for `snap_manageState`

- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
- packages/snaps-execution-environments/src/common/test-utils/endowments.ts
Fixes a problem where it was possible to trick the separation of concern measures in `snap.request` and `ethereum.request`
Fixes #1213
> Properly secure `snap` and `ethereum` request functions

- packages/snaps-controllers/src/snaps/endowments/enum.ts
- packages/snaps-controllers/src/snaps/endowments/index.ts
- packages/snaps-controllers/src/snaps/endowments/web-assembly.test.ts
- packages/snaps-controllers/src/snaps/endowments/web-assembly.ts
- packages/snaps-utils/src/default-endowments.ts
- packages/snaps-utils/src/manifest/validation.ts
Fixes: https://github.com/MetaMask/snaps-monorepo/issues/1150
This PR will add new endowment permission for `WebAssembly`.
`metamask-extension` PR: https://github.com/MetaMask/metamask-extension/pull/17694
> Add WebAssembly permission

- packages/snaps-controllers/src/snaps/location/http.test.ts
- packages/snaps-controllers/src/snaps/location/http.ts
- packages/snaps-controllers/src/snaps/location/npm.test.ts
- packages/snaps-controllers/src/snaps/location/npm.ts
Throw errors if `fetch` fails when trying to fetch snaps, for example if a snap URL results in 404. Previously these functions would return garbage data by trying to parse 404 responses.
Fixes #1226
> Throw errors on failed `fetch`

- packages/snaps-execution-environments/nyc.config.js
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
Different JavaScript runtimes have different global objects, browsers have `self`, `window` and `globalThis`, while Node has `globalThis` and `global`.
All of them are self-referential. `self.self === self` and so on.
This fixes how we injected those globals to all point to the same object and add self-referential properties.
Fixes issue 3 from #1160
> Snaps globalThis now has proper self-referential properties

- packages/rpc-methods/src/restricted/invokeSnap.ts
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-utils/jest.config.js
- packages/snaps-utils/src/snaps.test.ts
- packages/snaps-utils/src/snaps.ts
- packages/snaps-utils/src/test-utils/snap.ts
Replaces existing validation of snap IDs with Superstruct-based validation that leverages existing structs. Also adds a base struct to the existing snap ID structs that enforces strictly printable ASCII characters to be part of the ID string. This enforces no whitespaces or otherwise invisible characters.
Fixes https://github.com/MetaMask/MetaMask-planning/issues/351
> Improve validation and sanitizing of snap IDs

- .github/workflows/build-lint-test.yml
Rather than uploading coverage after each test run, we now only upload it after all tests have completed. Hopefully this helps with Codecov's processing time.
Depends on #1254.
> Upload coverage results in a single job

- packages/snaps-controllers/package.json
- packages/snaps-controllers/src/services/iframe/IframeExecutionService.test.browser.ts
- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/jest.config.js
- packages/snaps-execution-environments/package.json
- packages/snaps-execution-environments/src/common/lockdown/lockdown-events.test.browser.ts
- packages/snaps-execution-environments/src/common/lockdown/lockdown-events.ts
- packages/snaps-execution-environments/src/iframe/index.ts
- packages/snaps-execution-environments/src/offscreen/index.ts
- packages/snaps-utils/package.json
- yarn.lock
Fixes: https://github.com/MetaMask/snaps-monorepo/issues/1132
This PR will add utility functions with procedures for hardening Event related objects.
New lockdown procedure file is added exclusively for events `lockdown-events.ts` exporting function `executeLockdownEvents` that is called in `packages/snaps-execution-environments/src/iframe/index.ts` before other lockdown functions to ensure that this one will be executed before SES disallows further changes.
Currently blocked by (depends on): https://github.com/MetaMask/post-message-stream/pull/79
> Add harden events utilities

- packages/rpc-methods/jest.config.js
- packages/rpc-methods/src/permitted/getSnaps.ts
- packages/rpc-methods/src/permitted/requestSnaps.ts
- packages/rpc-methods/src/restricted/dialog.ts
- packages/rpc-methods/src/restricted/getBip32Entropy.ts
- packages/rpc-methods/src/restricted/getBip32PublicKey.ts
- packages/rpc-methods/src/restricted/getBip44Entropy.ts
- packages/rpc-methods/src/restricted/getEntropy.ts
- packages/rpc-methods/src/restricted/invokeSnap.ts
- packages/rpc-methods/src/restricted/manageState.ts
- packages/rpc-methods/src/restricted/notify.ts
- packages/rpc-methods/src/utils.ts
By using a new type `MethodHooksObject`, we can ensure that the `methodHooks` and `hookNames` specified match the ones specified in the type. For example, using the following type:
```ts
type GetBip32EntropyMethodHooks = {
getMnemonic: () => Promise<Uint8Array>;
getUnlockPromise: (shouldShowUnlockRequest: boolean) => Promise<void>;
};
```
This will work:
```ts
const methodHooks: MethodHooksObject<GetBip32EntropyMethodHooks> = {
getMnemonic: true,
getUnlockPromise: true,
};
```
This will not:
```ts
// TS2741: Property 'getUnlockPromise' is missing in type '{ getMnemonic: true; }' but required
// in type 'MethodHooksObject<GetBip32EntropyMethodHooks>'.
const methodHooks: MethodHooksObject<GetBip32EntropyMethodHooks> = {
getMnemonic: true,
};
```
This solves issues where we may forget to …
> Ensure that same method hooks are used in type and builder

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-utils/src/manifest/validation.ts
Require snaps to request at least one handler permission. 
Fixes #899
> BREAKING: Require snaps to request at least one handler permission

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
Fix a few issues related to installation and updating:
- Fixes an issue where rollback would sometimes leave snaps stuck in an updating state with no way to recover
- Fixes a lack of checking that the installed version of a snap matches the provided version range
Fixes #1307
> Fix a few issues with installation and updating

- packages/rpc-methods/src/restricted/invokeSnap.test.ts
- packages/rpc-methods/src/restricted/invokeSnap.ts
Currently, the way the `PermissionController` is setup, we're required to merge caveat values for subsequent `wallet_requestPermissions` calls. In the case of `wallet_snap`, we end up re-installing already installed snaps in addition to the newly requested snaps. Dedupe logic was added  to prevent re-installation of already installed snaps when those snaps haven't been requested (to be installed).
**Note:** The `SnapController:getPermitted`(`${this.snapController.name}:getPermitted`) action should be added to the `PermissionController`'s messenger's `allowedActions` in the extension.
> Fix `handleSnapInstall` side-effect

- packages/snaps-controllers/src/snaps/registry/json.test.ts
- packages/snaps-controllers/src/snaps/registry/json.ts
This pull request consists of two changes:
- Fixing a test in JsonSnapsRegistry class that had the wrong signature.
- Adding the `async` keyword to the `verify` method in JsonSnapsRegistry class.
One of the tests in the JsonSnapsRegistry class had a wrong signature that resulted in a test failure. This commit fixes
the signature to match the JSON response obtained during the test execution. Additionally, a new test case was added
to check situations where an invalid signature is present. 
The `verify` method in JsonSnapsRegistry class returns a Promise. The missing `async` keyword would result in the method
not being awaited, and it would not resolve. The `async` keyword is added to ensure that the `verify` method is resolved.
This change leads to better code readability and ensures that …
> Properly handle Promise in `JsonSnapsRegistry` signature verification

- .yarn/patches/clet-npm-1.0.1-8523231bdc.patch
- package.json
- packages/examples/examples/typescript/package.json
- packages/examples/examples/typescript/snap.manifest.json
- packages/examples/examples/typescript/src/index.ts
- packages/examples/examples/typescript/tsconfig.json
- packages/snaps-cli/.eslintrc.js
- packages/snaps-cli/babel.config.js
- packages/snaps-cli/jest.config.js
- packages/snaps-cli/package.json
- packages/snaps-cli/src/cmds/build/build.e2e.test.ts
- packages/snaps-cli/src/cmds/eval/__test__/eval-2.js
- packages/snaps-cli/src/cmds/eval/__test__/eval.js
- packages/snaps-cli/src/cmds/eval/eval.e2e.test.ts
- packages/snaps-cli/src/cmds/init/init.e2e.test.ts
- packages/snaps-cli/src/cmds/init/initHandler.ts
- packages/snaps-cli/src/cmds/init/initUtils.test.ts
- packages/snaps-cli/src/cmds/init/initUtils.ts
- packages/snaps-cli/src/cmds/manifest/manifest.e2e.test.ts
- packages/snaps-cli/src/cmds/serve/serve.e2e.test.ts
- packages/snaps-cli/src/cmds/watch/watch.e2e.test.ts
- packages/snaps-cli/src/test-utils/e2e.ts
- packages/snaps-cli/src/test-utils/index.ts
- packages/snaps-utils/src/eval-worker.js
- packages/snaps-utils/tsconfig.build.json
- yarn.lock
This adds E2E tests for the Snaps CLI, using `clet` as framework.
Tests are run on Linux, macOS, and Windows, as part of the regular Jest tests.
Closes #310.
> Add E2E tests for Snaps CLI

- README.md
This pull request adds instructions on how to pass the `GITHUB_NPM_TOKEN` environment variable required to authenticate
against GitHub's NPM Package Registry when running `yarn install` command to install the preview packages generated in
the upstream repository. 
By default, `yarn install` won't authenticate against the NPM registry from GitHub. Therefore, we need to pass the
authentication token as an environment variable to authenticate with it. This change provides detailed instructions on
how to pass `GITHUB_NPM_TOKEN` variable as an environment variable during `yarn install`. 
Additionally, this will help prevent accidental commits of the token if you had it stored in the `.yarnrc.yml` file.
This is a necessary change to ensure that developers can install preview packages from the …
> Add instructions for passing `GITHUB_NPM_TOKEN` environment variable during `yarn install`

- packages/rpc-methods/package.json
- packages/rpc-methods/src/restricted/manageState.test.ts
- packages/rpc-methods/src/restricted/manageState.ts
This pull request adds a new encrypt and decrypt hook to the project to let implementers use their own encryption and
decryption functions. `@metamask/browser-passworder` previously handled these functions, but with this PR we are replacing
it with the new hooks.
The main motivation behind this change is compatibility. We want to ensure that both the extension and mobile version
of MetaMask can use the same JSON-RPC method logic, and provide their own encryption implementations.
This change increases the flexibility of our codebase and simplifies the work of future implementers.
1. Add a new encrypt and decrypt hook to the `snap_manageState` JSON-RPC method.
2. Replace `@metamask/browser-passworder` with the new encrypt and decrypt hooks.
- `@metamask/browser-passworder` is still used for …
> Add encrypt and decrypt hook for custom encryption implementations

- .github/workflows/build-lint-test.yml
- .gitignore
- package.json
- scripts/install-chrome.sh
- yarn.lock
This pull request upgrades `chromedriver` to the `112.0.0` version which is required to support the latest Chrome browser.
The current version was causing issues while running our tests, which made it necessary to upgrade.
As `chromedriver` is used by the WebDriverIO automated testing framework to control Chrome browser, it is important to keep it
up-to-date to ensure smooth test runs. This change ensures that our tests can be run on the latest version of Chrome
without any issues.
1. Upgrade `chromedriver` to version `112.0.0`.
Closes #1342.
> Upgrade `chromedriver` to version 112.0.0

- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/endowments/crypto.ts
- packages/snaps-execution-environments/src/common/endowments/math.test.ts
- packages/snaps-execution-environments/src/common/endowments/math.ts
Fixes the Math endowment when running in Node.js. Previously we would assume `crypto` to be available, but that isn't the case in the scope where we are creating the Math endowment.
> Fix Math endowment in Node.js

- packages/snaps-utils/src/mock.ts
Add `WebAssembly` to eval mock to fix issues with eval failing when devs are leveraging WebAssembly.
> Add `WebAssembly` to eval mock

- .yarn/patches/inline-source-map-npm-0.6.2-96902459a0.patch
- package.json
- yarn.lock
Patches `inline-source-map` to remove deprecated use of Buffer. This patch is identical to the one applied in the extension.
> Patch `inline-source-map` to remove deprecated use of Buffer

- packages/snaps-cli/jest.config.js
- packages/snaps-cli/src/cmds/watch/watchHandler.test.ts
- packages/snaps-cli/src/cmds/watch/watchHandler.ts
Watch manifest and config files to ensure automatic rebuild when changing permissions or changing build configuration.
Also fixes an issue detecting source paths on Windows
Fixes #1357
> Watch manifest and config files

- packages/snaps-controllers/src/services/node/NodeProcessExecutionService.test.ts
- packages/snaps-controllers/src/services/node/NodeThreadExecutionService.test.ts
- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
- packages/snaps-execution-environments/src/common/commands.ts
- packages/snaps-execution-environments/src/common/endowments/commonEndowmentFactory.ts
- packages/snaps-execution-environments/src/common/endowments/console.test.ts
- packages/snaps-execution-environments/src/common/endowments/console.ts
- packages/snaps-execution-environments/src/common/endowments/endowments.test.browser.ts
- packages/snaps-execution-environments/src/common/endowments/index.test.ts
- packages/snaps-execution-environments/src/common/endowments/index.ts
- packages/snaps-execution-environments/src/openrpc.json
Closes #1267 
The console endowment was added to prepend certain `console` methods with a message that states the calling snap's id to ensure that logs can be properly identified. Usage of the `snapName` variable was replaced with `snapId` for consistency and to avoid any confusion.
> Add console endowment

- .github/workflows/build-lint-test.yml
- packages/snaps-execution-environments/lavamoat/build-system/policy.json
This pull request adds a LavaMoat policy generation step to CI. This will ensure that the policy is up-to-date in CI, since we check that the working directory is clean.
1. Add a LavaMoat policy generation step to the build process.
2. Update the global 'Buffer' to 'Buffer.from' in the inline-source-map package.
> Add LavaMoat policy generation to CI

- packages/snaps-execution-environments/src/common/utils.test.ts
- packages/snaps-execution-environments/src/common/utils.ts
Block `wallet_requestPermissions` for now, until we figure out a strategy for snaps having dynamic permissions.
Fixes https://github.com/MetaMask/MetaMask-planning/issues/534
> Block `wallet_requestPermissions`

- package.json
- packages/examples/examples/bls-signer/package.json
- packages/examples/examples/ethers-js/package.json
- packages/examples/examples/insights/package.json
- packages/examples/examples/ipfs/package.json
- packages/examples/examples/notifications/package.json
- packages/examples/examples/rollup/package.json
- packages/examples/examples/typescript/package.json
- packages/examples/examples/wasm/package.json
- packages/examples/examples/webpack/package.json
- packages/examples/package.json
- packages/multichain-provider/package.json
- packages/rpc-methods/package.json
- packages/snaps-browserify-plugin/package.json
- packages/snaps-cli/package.json
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/package.json
- packages/snaps-rollup-plugin/package.json
- packages/snaps-types/package.json
- packages/snaps-ui/package.json
- packages/snaps-utils/package.json
- packages/snaps-webpack-plugin/package.json
- yarn.lock
- devDeps: `@lavamoat/allow-scripts`@`2.0.2`->`2.3.1` 
- Resolves multiple dependency issues
> devDeps: @lavamoat/allow-scripts@2.0.3->2.3.1

- .github/workflows/publish-release.yml
Bumps the GitHub action used for releases to add support for prereleases.
> Bump release action

- packages/rpc-methods/jest.config.js
- packages/rpc-methods/src/permitted/requestSnaps.test.ts
- packages/rpc-methods/src/permitted/requestSnaps.ts
Fixes a problem with merging of caveats when installing snaps in an origin that already has installed snaps.
> Fix snap install versioning

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
This removes the assertion that all the subjects passed to `removeSnapFromSubject` have the `wallet_snap` permission since the snap itself is a subject, some of the subject passed to this function are not containing the `wallet_snap` permission. It also adds a test.
> Skip subjects without the `wallet_snap` permission in `removeSnapFromSubject`

- .github/workflows/create-release-pr.yml
This will unblock the current pending patch release, by adding support for pre-releases in the create release PR action.
> Bump create release PR action

- README.md
- packages/snaps-utils/src/manifest/manifest.ts
- packages/snaps-utils/src/manifest/validation.test.ts
- packages/snaps-utils/src/manifest/validation.ts
$schema property is used to locate the JSON Schema that IDEs (specifically VSC) use to lint the JSON file.
> Allow use of $schema in manifest files

- packages/snaps-controllers/src/cronjob/CronjobController.ts
- packages/snaps-controllers/src/multichain/MultiChainController.test.ts
- packages/snaps-controllers/src/multichain/MultiChainController.ts
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/registry/registry.ts
- packages/snaps-controllers/src/test-utils/controller.ts
- packages/snaps-utils/src/snaps.ts
- packages/snaps-utils/src/test-utils/snap.ts
Closes #1245 
The `SnapId` and `ValidatedSnapId` types were used interchangeably in the snaps controllers, this PR replaces usage of `SnapId` at the points of execution where the `SnapId` has already been validated or is known to be valid.
> Clean up snap ID typing

- packages/snaps-utils/src/handlers.ts
`OnRpcRequestHandler` and `OnCronjobHandler` are generic in the type of the params, and default to the same as they are now. This allows devs to use e.g. an array as params.
> Make snaps handlers' types generic, allowing them to be changed

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/endowments/keyring.ts
- packages/snaps-controllers/src/snaps/endowments/rpc.ts
- packages/snaps-controllers/src/snaps/permission.test.ts
- packages/snaps-controllers/src/snaps/permissions.ts
- packages/snaps-simulator/src/features/simulation/sagas.ts
- packages/snaps-simulator/src/features/simulation/snap-permissions.ts
Export `buildSnapEndowmentSpecifications` & `buildSnapRestrictedMethodSpecifications` which is used in the extension and snaps-simulator.
Fixes #1430
> Export permissions specification builders

- README.md
Update the README to fit with the new repo name and remove the unnecessary `-monorepo` moniker.
> Rename repo in README

- packages/create-snap/package.json
- packages/examples/examples/bls-signer/snap.manifest.json
- packages/examples/examples/ethers-js/snap.manifest.json
- packages/examples/examples/insights/package.json
- packages/examples/examples/insights/snap.manifest.json
- packages/examples/examples/signer/packages/bitcoin/package.json
- packages/examples/examples/signer/packages/bitcoin/snap.manifest.json
- packages/examples/examples/signer/packages/core/package.json
- packages/examples/examples/signer/packages/core/snap.manifest.json
- packages/examples/examples/signer/packages/ethereum/package.json
- packages/examples/examples/signer/packages/ethereum/snap.manifest.json
- packages/multichain-provider/package.json
- packages/rpc-methods/package.json
- packages/snaps-cli/package.json
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/lavamoat/browserify/iframe/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-process/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-thread/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/offscreen/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-executor/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-pool/policy.json
- packages/snaps-execution-environments/package.json
- packages/snaps-simulator/package.json
- packages/snaps-types/package.json
- packages/snaps-ui/package.json
- packages/snaps-utils/package.json
- packages/snaps-webpack-plugin/package.json
- yarn.lock
Bumps `@metamask/utils` to `6.0.0` and `@metamask/snaps-registry` to `1.2.1`
> Bump `@metamask/utils` and `@metamask/snaps-registry`

- .github/workflows/build-lint-test.yml
This is a small change to the build step in CI. We now run LavaMoat policy generation in a separate job, as it does not any build files.
> Run LavaMoat policy generation in a separate job in CI

- .github/workflows/publish-release.yml
- package.json
- scripts/get-release-tag.ts
- tsconfig.json
- yarn.lock
This refactors the tag logic in CI for releases:
- If the branch is `main`, the release is tagged as `flask`.
- If the branch is not `main`:
- If the version is a prerelease version (i.e., it includes something like `-prerelease.1` in the version), it is tagged as `next`.
- Otherwise, it is tagged as `latest`.
> Properly tag prerelease versions

- package.json
- scripts/install-chrome.sh
- yarn.lock
This bumps Chromedriver and the Chrome version used in CI to `v114`, which matches the latest stable Chrome version.
> Bump Chrome and Chromedriver to v114

- constraints.pro
- packages/create-snap/package.json
- packages/multichain-provider/package.json
- packages/rpc-methods/package.json
- packages/snaps-browserify-plugin/package.json
- packages/snaps-cli/package.json
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/package.json
- packages/snaps-rollup-plugin/package.json
- packages/snaps-types/package.json
- packages/snaps-ui/package.json
- packages/snaps-utils/package.json
- packages/snaps-webpack-plugin/package.json
This allows tree shaking of packages by 3rd party bundlers (Webpack, Rollup, etc.)
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
> Add `sideEffects: false` to every package

- packages/rpc-methods/package.json
- packages/snaps-simulator/package.json
- packages/snaps-simulator/src/features/simulation/sagas.ts
- yarn.lock
Fixes the manageState implementation in `snaps-simulator`. 
The implementation was broken since it now expects the hooks `encrypt` and `decrypt` to be available for client-specific encryption. This wasn't added in the hackathon version of `snaps-simulator`.
> Fix manageState in `snaps-simulator`

- packages/snaps-simulator/src/features/handlers/cronjobs/slice.ts
- packages/snaps-simulator/src/features/handlers/json-rpc/slice.ts
- packages/snaps-simulator/src/features/handlers/transactions/slice.ts
Fixes the types for the response slices in `snaps-simulator`. These were wrongly marked as string.
> Fix response typing in `snaps-simulator`

- package.json
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/lavamoat/build-system/policy.json
- packages/snaps-execution-environments/package.json
- packages/snaps-utils/package.json
- yarn.lock
Fixes a few dependabot warnings by bumping `vite` and `find-babel-config`.
> Fix a few dependabot warnings

- packages/snaps-execution-environments/package.json
- packages/snaps-execution-environments/scripts/start.js
- yarn.lock
This is meant to help incorporate changes made to the execution environment into the extension. The idea is to spin up a local instance and then use your local url in place of the hosted url in `builds.yml` in the `metamask-extension` repo.
> Add script to spin up local instance of the Iframe Execution Environment

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/post-process.test.ts
- packages/snaps-utils/src/post-process.ts
Previously, our post processing would throw an error for code such as:
```ts
const foo = bar + `` + qux;
```
This is because we were looking at the entire source of the binary expression, rather than the individual `left` and `right` nodes. I fixed this by only checking the code between the left and right part.
> Fix false positives when post processing code with HTML comment tokens

- constraints.pro
- packages/create-snap/package.json
- packages/examples/packages/bip32/package.json
- packages/examples/packages/bip44/package.json
- packages/examples/packages/browserify-plugin/package.json
- packages/examples/packages/cronjobs/package.json
- packages/examples/packages/dialogs/package.json
- packages/examples/packages/errors/package.json
- packages/examples/packages/ethereum-provider/package.json
- packages/examples/packages/ethers-js/package.json
- packages/examples/packages/get-entropy/package.json
- packages/examples/packages/invoke-snap/packages/consumer-signer/package.json
- packages/examples/packages/invoke-snap/packages/core-signer/package.json
- packages/examples/packages/json-rpc/package.json
- packages/examples/packages/manage-state/package.json
- packages/examples/packages/network-access/package.json
- packages/examples/packages/network-access/snap.manifest.json
- packages/examples/packages/notifications/package.json
- packages/examples/packages/rollup-plugin/package.json
- packages/examples/packages/transaction-insights/package.json
- packages/examples/packages/wasm/package.json
- packages/examples/packages/webpack-plugin/package.json
- packages/snaps-simulator/package.json
Some packages were missing the `prepare-manifest:preview` and `publish:preview` scripts, meaning that they wouldn't be published properly when using preview releases. This adds a Yarn constraint and adds the missing scripts to those packages.
> Add missing `prepare-manifest:preview` and `publish:preview` scripts

- packages/snaps-controllers/src/snaps/endowments/index.ts
Adds an export for `getRpcCaveatOrigins` since it is used in the extension.
> Add export for `getRpcCaveatOrigins`

- constraints.pro
- packages/create-snap/package.json
- packages/rpc-methods/package.json
- packages/snaps-browserify-plugin/package.json
- packages/snaps-cli/package.json
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/package.json
- packages/snaps-jest/package.json
- packages/snaps-rollup-plugin/package.json
- packages/snaps-simulator/package.json
- packages/snaps-types/package.json
- packages/snaps-ui/package.json
- packages/snaps-utils/package.json
- packages/snaps-webpack-plugin/package.json
This adds wildcard exports (`./dist/cjs/*` and `./dist/esm/*`) to all packages, which makes it possible to import them from a subpath. Before, the following would fail:
```
require('@metamask/snaps-ui/dist/cjs/validation');
```
After this change, this will work as expected, and import the best version (ESM or CJS), regardless of the path used. This is a bit hacky, but Browserify doesn't support the `exports` field, so I'm not sure how to work around this otherwise.
> Add wildcard exports to all packages

- constraints.pro
- packages/snaps-jest/package.json
- packages/snaps-simulator/package.json
The `@metamask/snaps-jest` and `@metamask/snaps-simulator` packages were missing a `publishConfig`, causing the release to fail. This adds the missing `publishConfig`, as well as some Yarn constraints to prevent this in the future.
> Add missing `publishConfig` to `snaps-jest` and `snaps-simulator`

- packages/snaps-controllers/src/snaps/endowments/index.ts
Cherry-picks https://github.com/MetaMask/snaps/commit/db423be1702fe1caab119e51aa8678add69a755f to the audit branch.
> Cherry-pick to RC

- constraints.pro
- packages/create-snap/package.json
- packages/rpc-methods/package.json
- packages/snaps-browserify-plugin/package.json
- packages/snaps-cli/package.json
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/package.json
- packages/snaps-jest/package.json
- packages/snaps-rollup-plugin/package.json
- packages/snaps-simulator/package.json
- packages/snaps-types/package.json
- packages/snaps-ui/package.json
- packages/snaps-utils/package.json
- packages/snaps-webpack-plugin/package.json
This removes unnecessary exports fields, as Node.js is able to resolve these based on the file system. It also fixes an issue with missing build files in the `snaps-simulator` package.
> Remove unnecessary exports fields and fix missing build files

- packages/snaps-jest/README.md
The output path was recently changed, but not updated in the README.
> Update setup script path in `snaps-jest` README file

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/rpc-methods/jest.config.js
- packages/rpc-methods/src/restricted/invokeSnap.test.ts
- packages/rpc-methods/src/restricted/invokeSnap.ts
- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
Refactors `handleRequest` to properly handle input where `id` and `jsonrpc` is omitted. In the past this was only allowed for `wallet_invokeSnap` and thus not allowed for tx insights or other handlers. This also changes when validation is done that a JSON-RPC request is a valid request.
> Allow omitting `jsonrpc` and `id` in `handleRequest`

- packages/snaps-jest/src/internals/network.ts
For some reason, when mocking the network with an empty string as body, the request never resolves. When using a newline, this is not an issue.
> Default to newline instead of empty string for network mocking

- packages/examples/README.md
- packages/examples/packages/ethereum-provider/README.md
- packages/examples/packages/ethereum-provider/snap.manifest.json
- packages/examples/packages/ethereum-provider/src/index.ts
- packages/test-snaps/src/features/snaps/ethereum-provider/EthereumProvider.tsx
Adds `eth_requestAccounts` usage to the Ethereum provider example to provide an example of how snaps can access a user's existing Ethereum acounts.
> Add `eth_requestAccounts` usage to the Ethereum provider example

- packages/test-snaps/src/features/snaps/cronjobs/constants.ts
- packages/test-snaps/src/features/snaps/dialogs/constants.ts
- packages/test-snaps/src/features/snaps/errors/constants.ts
- packages/test-snaps/src/features/snaps/notifications/constants.ts
cronjob, error, dialog and notification had the names pulralized in the "features" for the test-snaps page but not in the individual package.json files.
we've reverted the names to singular so not to complicate the npm repository
> Fix example snaps names in test-snaps page

- packages/snaps-simulator/package.json
The `post-tsc` script was calling `build`, which builds the source and types. This is not the purpose of `post-tsc`, and causes the deployment workflow to break.
> Fix Snaps Simulator post-tsc script

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/snaps-ui/src/builder.test.ts
- packages/snaps-ui/src/builder.ts
- packages/snaps-ui/src/nodes.ts
Fixes #1587 
Allow disabling markdown for the snaps-ui text component.
Markdown can be disabled by specifying either:
```
text('Hello world', false)
text({ value: 'foo bar', markdown: false }
```
If no flag is specified, we will assume markdown to be **enabled**, this way the API is backwards compatible.
This will need changes on the extension-side as well and should probably be cherry-picked to the audit branch.
> Allow disabling markdown for text component

- packages/test-snaps/webpack.config.ts
see issue #1592 
this changes the test-snaps local server port to 9000
> Fix test-snaps site port to 9000

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/ethereum-provider/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/consumer-signer/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/json-rpc/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/network-access/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/rollup-plugin/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/examples/packages/wasm/snap.manifest.json
- packages/examples/packages/webpack-plugin/snap.manifest.json
- yarn.lock
Dependabot is trying to bump `semver` but failing. Doing it manually to get some DOS vulns fixed.
https://github.com/MetaMask/snaps/security/dependabot/74
https://github.com/MetaMask/snaps/security/dependabot/73
https://github.com/MetaMask/snaps/security/dependabot/72
> Bump `semver` as requested by Dependabot

- packages/snaps-simulator/src/features/navigation/components/Bottom.tsx
Updates GitHub link in snaps-simulator to point to the new location of the source code.
Fixes #1609
> Update GitHub link in snaps-simulator

- .github/workflows/publish-github-pages.yml
The concurrency group doesn't support queuing more than one job, so if there's a job pending and another job is added to the queue, the pending job will just be cancelled. We will find a better solution for this as part of #1600.
> Remove concurrency group from GitHub Pages workflow

- packages/test-snaps/src/features/snaps/network-access/constants.ts
missed in the last corrections pr - should be npm@network-example-snap not npm@network-access-example-snap
> Fix npm name of network access snap

- .github/workflows/publish-release.yml
This fixes [an issue in the deployment of the iframe execution environment](https://github.com/MetaMask/snaps/actions/runs/5613558288/job/15211010390). Reusable workflows cannot be called as part of a job, but must be called as their own job instead.
> Move environment deployment to separate CI job

- packages/test-snaps/src/features/snaps/transaction-insights/constants.ts
It was incorrectly listed as `npm:@metamask/transaction-insights-example-snap` rather than `npm:@metamask/insights-example-snap`
> Fix transaction insights example snap npm name

- .github/workflows/publish-release.yml
v3 doesn't support using the NPM tag to check if a new version should be released. This fixes a deployment issue after #1629.
> Bump action-npm-publish to v4

- package.json
- packages/snaps-jest/package.json
- packages/snaps-ui/package.json
- packages/snaps-utils/package.json
- yarn.lock
Problem: Many snaps recently audited used vulnerable package during audits/reviews.
Solutions: Bumping semver to ^7.5.4 (latest) in MetaMask/snaps and MetaMask/utils to ensure snap authors (and all other future imports) use version [built/signed with provenance](https://www.npmjs.com/package/semver?activeTab=versions) (new in >= 7.5.1) and fix [CVE-2022-25883](https://www.cve.org/CVERecord?id=CVE-2022-25883) (>= 7.5.2).
I spoke with @FrederikBolding yesterday, related PRs:
- MetaMask/snaps PR https://github.com/MetaMask/snaps/pull/1603 (approved 2023-07-14)
- MetaMask/snaps PR https://github.com/MetaMask/snaps/pull/1631 (this PR)
- MetaMask/utils PR https://github.com/MetaMask/utils/pull/123
> Bump semver to ensure signed provenance, CVE fix

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-utils/src/snaps.ts
- packages/snaps-utils/src/test-utils/snap.ts
Moves the source code and snap state from `SnapRuntimeData` to the `SnapController` state. This fixes a bug with persistence of snap state and source code changes. This change by itself will worsen performance of the extension, so it should be coupled with a change to filter source code and snap state from the state piped to the extension UI.
This PR also allows us to move `snapsRuntimeData` to hash private.
Fixes #1633
> Move source code and snap state back to controller state

- packages/snaps-cli/package.json
- packages/snaps-execution-environments/package.json
- yarn.lock
Fixes dependencies on SES, the CLI doesn't use SES directly and the execution environments only use it directly for testing.
> Fix SES dependencies

- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/test-utils/controller.ts
- packages/snaps-controllers/src/test-utils/registry.ts
This causes a type error if you are running tests with type checking, which we aren't on main. But perhaps we should be?
> Fix `MockSnapsRegistry` not matching `SnapsRegistry` interface

- .github/workflows/build-lint-test.yml
- .github/workflows/main.yml
- .github/workflows/publish-release.yml
In certain cases if GitHub Actions is unable to restore the cache, the rest of the workflow will fail too. In this case it's better to fail quickly, to give quicker feedback and make debugging easier (i.e., you can immediately see what failed).
> Fail CI if cache is unable to restore

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/rpc-methods/jest.config.js
- packages/rpc-methods/src/restricted/getBip32Entropy.ts
- packages/rpc-methods/src/restricted/getBip32PublicKey.test.ts
- packages/rpc-methods/src/restricted/getBip32PublicKey.ts
- packages/rpc-methods/src/utils.test.ts
- packages/rpc-methods/src/utils.ts
This is a replacement for #1651. In addition to fixing a typo in "ed225519," this also adds actual support for deriving public keys with `ed25519`. I've also cleared up some logic that was duplicated for `snap_getBip32PublicKey` and `snap_getBip32Entropy`.
> Fix ed25519 public key derivation

- packages/create-snap/package.json
- packages/snaps-cli/package.json
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/lavamoat/browserify/iframe/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-process/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-thread/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/offscreen/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-executor/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-pool/policy.json
- packages/snaps-execution-environments/lavamoat/build-system/policy.json
- packages/snaps-execution-environments/package.json
- packages/snaps-utils/package.json
- yarn.lock
Removes a bunch of unused dependencies that consumers of our packages don't need to install.
> Remove unused deps

- packages/examples/README.md
The `get-locale` example snap was missing from the list in the examples `README`.
> Add `get-locale` snap to examples list

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-locale/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/rpc-methods/src/restricted/manageAccounts.test.ts
- packages/rpc-methods/src/restricted/manageAccounts.ts
The arguments of a restricted method must extend the `RestrictedMethodParameters` type, which is defined as:
Json[] | Record<string, Json> | void
However, the current definition of `SnapMessageStruct` is not a valid JSON value due to the presence of an optional field. This optional field is incorrectly inferred by superstruct as `params?: ... | undefined`.
This PR adds a workaround to make `SnapMessageStruct` a valid JSON using the following pattern:
{ A, B? } -> { A } | { A, B }
See: https://github.com/ianstormtaylor/superstruct/issues/983
Fixes: https://github.com/MetaMask/accounts-planning/issues/41
> Make `manageAccounts` arguments extend `RestrictedMethodParameters`

- packages/snaps-simulator/src/features/builder/utils.ts
Fixes #1427.
Previously the UI builder would crash if you inputted a quote, due to the code editor actually trying to interpret the code. This is fixed by escaping the quotes.
> Fix error when using single quotes in UI builder

- packages/snaps-controllers/src/snaps/location/npm.test.ts
- packages/snaps-controllers/src/snaps/location/npm.ts
Fixes https://github.com/MetaMask/snaps/issues/1704
This is a fun one. If an NPM package included an empty file of length zero bytes, `concat-stream` would return it as an empty array instead of an `Uint8Array`. This meant that `data.byteLength` would be `undefined` which in turn would break our running counter of total tarball size, resulting in an error that the NPM tarball was too large:
```
number + undefined == NaN
NaN < TARBALL_SIZE_SAFETY_LIMIT == false
```
`concat-stream` supports providing an encoding argument that will convert any output to a given encoding and so the fix is simply providing the expected output type of `Uint8Array` as the specified encoding.
Previously `concat-stream` would try to infer the encoding by looking at the input, but the types did not take that into …
> Fix unpacking zero byte files from NPM

- .github/workflows/update-pull-request.yml
- package.json
- packages/examples/packages/rollup-plugin/snap.manifest.json
When running `yarn build`, everything in the repository is built, including the simulator, execution environments, test snaps, etc. This adds a lot of time to the build process, while those files are not used to build the examples.
By only building the source and types of the dependencies (of the examples), we can speed up the process significantly.
> Speed up update PR workflow by only building dependencies

- packages/snaps-simulator/src/components/SnapIcon.tsx
Fixes fallback icon in snaps simulator which was wrongly using the second char.
> Fix fallback icon in snaps simulator

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-locale/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/rpc-methods/jest.config.js
- packages/rpc-methods/src/restricted/manageAccounts.test.ts
- packages/rpc-methods/src/restricted/manageAccounts.ts
The `rpc-methods` repo should not have knowledge about the logic behind the `SnapKeyring` nor decide when its state needs to be saved.
This PR removes the **business-logic** callbacks from the `manageAccounts` implementation.
Note: The `manageAccounts` method is still 100% covered, but since some code was removed, the global coverage threshold decreased.
> Remove business-logic callbacks from `manageAccounts`

- packages/examples/packages/network-access/package.json
- packages/examples/packages/network-access/snap.manifest.json
- packages/examples/packages/network-access/src/constants.ts
- packages/examples/packages/network-access/src/index.test.ts
- packages/examples/packages/network-access/src/index.ts
- packages/examples/packages/network-access/src/types.ts
- packages/test-snaps/src/features/snaps/network-access/NetworkAccess.tsx
- yarn.lock
Fixes an issue with the hardcoded path in the network access example snap. From now on, an URL parameter is expected to be passed. This PR also changes `test-snaps` to add an input field for passing this URL.
> Fix network access example snap

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/cronjob/CronjobController.test.ts
- packages/snaps-controllers/src/cronjob/CronjobController.ts
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/test-utils/controller.ts
Fixes an issue where cronjobs would still fire on disabled snaps. The cronjob wouldn't succeed as the snap was not allowed to run, but the CronjobController would try to run the cronjob regardless.
Fixes https://github.com/MetaMask/snaps/issues/1720
> Fix cronjob running on disabled snaps

- packages/snaps-execution-environments/src/common/endowments/crypto.test.ts
- packages/snaps-execution-environments/src/common/globalEvents.test.ts
- packages/snaps-utils/src/mock.test.ts
Stop spreading `globalThis` for setting up tests. It is unnecessary and not supported in Node 20 and onwards.
> Stop spreading `globalThis` in tests

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-locale/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/snaps-types/src/types.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/handlers.ts
- packages/snaps-utils/src/manifest/validation.ts
The types previously merged in don't work with snap code as pointed out by @matthewwalsh0, we also weren't doing the correct validation for the manifest. Updated code with the correct types.
> Fix `onNameLookup` types

- .yarn/patches/@lavamoat-lavapack-npm-5.2.1-6ac9929a63.patch
- .yarn/patches/lavamoat-core-npm-14.2.1-879311807b.patch
- package.json
- yarn.lock
Adds a LavaMoat patch to enable `overrideTaming` in both `@lavamoat/lavapack` and `lavamoat-core`. This works around potential issues with dependencies and snaps causing `Cannot assign to read only property 'constructor' of object '[object Object]'`.
> Add LavaMoat patch to enable `overrideTaming`

- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
This fixes an issue where you could use blocked methods by changing the `toJSON` signature.
> Sanitize JSON before checking for blocked methods

- .github/workflows/main.yml
- .github/workflows/publish-release.yml
- scripts/get-release-tag.ts
Removes the notion of the RC branch from the CI workflows and the `get-release-tag` script.
> Preparations for releasing from `main`

- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
- packages/snaps-execution-environments/src/common/utils.ts
This PR allows passing `undefined` parameters to `request()`. Previously this would fail as `getSafeJson` asserts that all input is valid according to the JSON spec. For compatibility's sake we now strip `undefined` values before passing to `getSafeJson`.
> Allow passing `undefined` parameters to `request()`

- packages/snaps-cli/src/webpack/__snapshots__/config.test.ts.snap
- packages/snaps-cli/src/webpack/config.ts
This PR adds the `fullySpecified` rule to `false` for `.js` imports in modules to the default Webpack config.
This will allow importing modules that uses .js and not .mjs for the ES build.
> Disable fullySpecified rule for `.js` imports in the default Webpack config

- packages/create-snap/src/cli.ts
- packages/create-snap/src/cmds/init/initUtils.test.ts
- packages/create-snap/src/cmds/init/initUtils.ts
This changes `execSync` to `spawnSync` so we directly invoque the command and pass individual arguments to it.
https://github.com/MetaMask/snaps/assets/13910212/e5bd0656-c794-42ce-a6d6-de5541d752ce
> Fix Shell command injection in `create-snap`

- packages/create-snap/src/cmds/init/initHandler.test.ts
- packages/create-snap/src/cmds/init/initHandler.ts
This bumps the node minimal version to use `create-snap` to `>=18.6.0`.
> Bump node satisfied version in `create-snap`

- packages/examples/packages/bip32/snap.manifest.json
- packages/snaps-cli/package.json
- packages/snaps-cli/src/cli.test.ts
- packages/snaps-cli/src/cli.ts
- yarn.lock
We got several reports about the CLI not working, which was caused by an outdated Node.js version. Some functionality we use requires at least Node.js 16.17.0 or Node.js 18.6.0. Node.js <16 is not support at all.
To prevent this, I've added a check to the CLI, to make sure that the user knows what the problem is.
> Check minimum Node version in CLI

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/test-utils/controller.ts
Fixes a few issues with SnapController events being emitted prematurely when multiple snaps were being installed. Also adds a `SnapController:snapUninstalled` event which is more reliable than `SnapController:snapRemoved`.
This PR also removes an old feature flag `dappsCanUpdateSnaps`, this feature is now enabled by default.
Fixes https://github.com/MetaMask/MetaMask-planning/issues/1400
> Fix some issues with SnapController events

- .github/workflows/update-pull-request.yml
After deduping, the cache may have stale packages. Removing `--immutable-cache` allows the installation to complete regardless.
> Remove `--immutable-cache` from update PR workflow

- .github/workflows/main.yml
- .github/workflows/publish-release.yml
This updates the Slack subteam to `@metamask-snaps-publishers` and the channel to `metamask-snaps`.
> Update Slack subteam and channel

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-locale/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/json-rpc/snap.manifest.json
- packages/examples/packages/json-rpc/src/index.ts
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/json-rpc.test.ts
- packages/snaps-utils/src/json-rpc.ts
This adds an optional `allowedOrigins` field to `endowment:rpc`. For example, a Snap can now specify this:
```json
{
"initialPermissions": {
"endowment:rpc": {
"allowedOrigins": [
"example.com"
]
}
}
}
```
Which would then only allow requests from "example.com" to the Snap.
> Add `allowedOrigins` field to `endowment:rpc`

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-locale/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/rpc-methods/jest.config.js
- packages/rpc-methods/src/permitted/invokeKeyring.test.ts
- packages/rpc-methods/src/permitted/invokeKeyring.ts
- packages/snaps-execution-environments/src/common/commands.ts
This PR replaces #1809 to use a branch from `MetaMask/snaps` instead of my personal repo.
> Add `getAllowedKeyringMethods` hook to be used by `invokeKeyring`

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-utils/src/snaps.ts
- packages/snaps-utils/src/types.ts
- packages/snaps-utils/src/validation.ts
Refactors snap fetching slightly to remove the pattern of returning a list of files. Instead, we use another existing pattern where each type of file is defined within a strict set of keys.
> Refactor snap fetching slightly

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/test-utils/controller.ts
Removes snap errors from state. This feature wasn't covered well and we don't want to keep supporting it.
> Remove snap errors from state

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/services/AbstractExecutionService.ts
- packages/snaps-controllers/src/services/browser.test.ts
- packages/snaps-controllers/src/services/node/NodeProcessExecutionService.test.ts
- packages/snaps-controllers/src/services/node/NodeThreadExecutionService.test.ts
- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
This fixes the Snaps controllers and execution environments tests on #1818.
> Fix `snaps-controllers` and `snaps-execution-environments` tests

- packages/snaps-controllers/package.json
- yarn.lock
Makes `snaps-execution-environments` an optional peer dependency since you only need the dependency if you are trying to use the Node.js environments.
Fixes #1844
> Make `snaps-execution-environments` an optional peer dependency

- packages/snaps-controllers/package.json
- yarn.lock
We were using a really old version, this brings us up to date with a more recent version.
> Bump `tar-stream` to the latest version

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-file/README.md
- packages/examples/packages/get-file/package.json
- packages/examples/packages/get-file/snap.manifest.json
- packages/examples/packages/get-file/src/index.test.ts
- packages/examples/packages/get-file/src/index.ts
- packages/examples/packages/get-locale/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/rpc-methods/src/permitted/getFile.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/auxiliary-files.test.ts
- packages/snaps-utils/src/auxiliary-files.ts
- yarn.lock
Support `utf8` encoding for `snap_getFile`. This is useful for loading JSON or other text files.
> Support `utf8` encoding for `snap_getFile`

- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
Adds an origin parameter to the emitted `snapInstalled` and `snapUpdated` events.
> Add origin parameter to `snapInstalled` and `snapUpdated` events

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
Stops persisting snaps in the installing state, this prevents a bug where snaps could enter an invalid and unusable state if installation was halted unexpectedly.
> Stop persisting snaps in the installing state

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/package.json
- packages/snaps-controllers/src/snaps/location/npm.test.ts
- packages/snaps-controllers/src/snaps/location/npm.ts
- yarn.lock
Improves performance when installing snaps with a static version by computing the NPM tarball URL without hitting the NPM registry. If the requested version is a range, the NPM registry will be hit as normal to resolve to a version that is published.
Feedback appreciated.
> Improve performance when installing snaps with a static version

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/registry/json.test.ts
- packages/snaps-controllers/src/snaps/registry/json.ts
- packages/snaps-controllers/src/snaps/registry/registry.ts
- packages/snaps-controllers/src/test-utils/controller.ts
- packages/snaps-controllers/src/test-utils/registry.ts
Adds a `resolveVersion` function to the registry implementation, this can be used to find the highest matching and allowlisted version for a given version range. This function will be used if the `requireAllowlist` feature flag is enabled and resolves to a specific version before hitting NPM.
This resolves an issue where you would get stuck trying to install a snap if you specified a broad version range that included un-allowlisted versions that were published to NPM.
> Try to match requested version with an allowlisted version

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/location/location.ts
- packages/snaps-controllers/src/snaps/location/npm.ts
- packages/snaps-controllers/src/snaps/registry/json.test.ts
- packages/snaps-controllers/src/snaps/registry/json.ts
- packages/snaps-controllers/src/test-utils/location.ts
- packages/snaps-controllers/src/test-utils/registry.ts
Move allowlist version resolving to the `SnapLocation` implementations. This fixes an issue with the installation flow not triggering the popup in time.
> Move allowlist version resolving to the `SnapLocation` implementations

- package.json
- packages/examples/packages/get-file/snap.config.ts
- packages/test-snaps/package.json
- packages/test-snaps/src/features/snaps/get-file/GetFile.tsx
- packages/test-snaps/src/features/snaps/get-file/constants.ts
- packages/test-snaps/src/features/snaps/get-file/index.ts
- packages/test-snaps/src/features/snaps/index.ts
- yarn.lock
This adds the Get File Snap to the test-snaps page.
This also addresses a port overlap and switches the get-file port to 8024.
> Add Get File Snap to test-snaps page

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-locale/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/snaps-rpc-methods/src/restricted/notify.ts
- packages/snaps-utils/src/index.ts
Fixes the import for the link validation code in the `snap_notify` RPC method. This also removes the `assertLinksAreSafe` export from `snaps-utils` as it was flawed (broken in the browser) and unnecessary.
> Fix `assertLinksAreSafe` import

- package.json
- packages/snaps-rpc-methods/CHANGELOG.md
- packages/snaps-rpc-methods/package.json
Hotfix for an import issue with `snaps-rpc-methods`.
> Release 16.0.0

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-locale/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/rollup-plugin/snap.manifest.json
- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/endowments/enum.ts
- packages/snaps-controllers/src/snaps/endowments/home-page.test.ts
- packages/snaps-controllers/src/snaps/endowments/home-page.ts
- packages/snaps-controllers/src/snaps/endowments/index.ts
- packages/snaps-controllers/src/snaps/endowments/snap-pages.ts
- packages/snaps-controllers/src/snaps/permission.test.ts
- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/common/commands.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/handler-types.ts
- packages/snaps-utils/src/handlers.ts
Adds an `onHomePage` export and an endowment called `endowment:page-home`. Both of these are to be used for the new snaps home page feature.
Reference: https://metamask.github.io/SIPs/SIPS/sip-15
Progresses https://github.com/MetaMask/MetaMask-planning/issues/1384
> Add snap home page

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-locale/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-rpc-methods/jest.config.js
- packages/snaps-rpc-methods/src/restricted/manageState.test.ts
- packages/snaps-rpc-methods/src/restricted/manageState.ts
- packages/snaps-simulator/jest.config.js
- packages/snaps-simulator/src/features/simulation/hooks.test.ts
- packages/snaps-simulator/src/features/simulation/hooks.ts
- packages/snaps-simulator/src/features/simulation/sagas.ts
- packages/snaps-simulator/src/features/simulation/slice.test.ts
- packages/snaps-simulator/src/features/simulation/slice.ts
Adds support for unencrypted storage. This feature can be used by passing `{ encrypted: false }` as part of the manageState parameters. This will store and read from a new state bucket that is unencrypted, this also means it can be accessed while MetaMask is locked.
Fixes https://github.com/MetaMask/snaps/issues/1813
> Add support for unencrypted storage

- packages/examples/packages/manage-state/README.md
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/manage-state/src/index.test.ts
- packages/examples/packages/manage-state/src/index.ts
- packages/examples/packages/manage-state/src/types.ts
- packages/examples/packages/manage-state/src/utils.ts
- packages/test-snaps/src/api.ts
- packages/test-snaps/src/features/snaps/manage-state/ManageState.tsx
- packages/test-snaps/src/features/snaps/manage-state/components/ClearData.tsx
- packages/test-snaps/src/features/snaps/manage-state/components/SendData.tsx
- packages/test-snaps/src/features/snaps/manage-state/hooks/useSnapState.ts
Updates manage state example to support both encrypted and unencrypted state.
Also adds support for the new unencrypted mode to `test-snaps`.
> Update manage state example

- packages/create-snap/src/cmds/init/initUtils.test.ts
- packages/create-snap/src/cmds/init/initUtils.ts
A recent change from execSync to spawnSync didn't mock the new call properly, resulting in falsely passing tests. spawnSync doesn't throw when there's an error, it just returns an object all the time. This commit fixes the tests and the implementation to account for this difference.
> Handle spawnSync errors in create-snap

- package.json
- scripts/install-chrome.sh
- yarn.lock
This bumps `chromedriver` to `^119.0.0` to match the latest stable Google Chrome version.
> Bump Chromedriver to `^119.0.0`

- packages/create-snap/src/cmds/init/initHandler.test.ts
- packages/create-snap/src/cmds/init/initHandler.ts
- packages/create-snap/src/cmds/init/initUtils.test.ts
- packages/create-snap/src/cmds/init/initUtils.ts
Note: merge this after #1916 
When creating a new Snap using the create-snap CLI, we make an initial commit with the code of the template. This makes it easier for devs to see the changes they make as they start hacking on the template, without having to remember to make an initial commit manually.
This is similar to what's done by other "create" projects such as CRA.
Tested:
> Make an initial commit when creating a Snap from template

- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
Await stream communication calls to ensure message delivery. This prevents issues where a snap could grab execution and prevent stream messages from being reliably delivered.
> Await stream communication

- package.json
- packages/create-snap/CHANGELOG.md
- packages/create-snap/package.json
- packages/examples/package.json
- packages/examples/packages/home-page/CHANGELOG.md
- packages/examples/packages/home-page/package.json
- packages/examples/packages/home-page/snap.manifest.json
- packages/examples/packages/localization/CHANGELOG.md
- packages/examples/packages/localization/package.json
- packages/examples/packages/localization/snap.manifest.json
- packages/examples/packages/manage-state/CHANGELOG.md
- packages/examples/packages/manage-state/package.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/transaction-insights/CHANGELOG.md
- packages/examples/packages/transaction-insights/package.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/snaps-controllers/CHANGELOG.md
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/CHANGELOG.md
- packages/snaps-execution-environments/package.json
- packages/snaps-rpc-methods/CHANGELOG.md
- packages/snaps-rpc-methods/package.json
- packages/snaps-simulator/CHANGELOG.md
- packages/snaps-simulator/package.json
- packages/snaps-types/CHANGELOG.md
- packages/snaps-types/package.json
- packages/snaps-utils/CHANGELOG.md
- packages/snaps-utils/package.json
- packages/test-snaps/CHANGELOG.md
- packages/test-snaps/package.json
Reverts MetaMask/snaps#1939
There was a problem with the release due to an incorrectly set version of an unreleased package.
> Revert "Release 17.0.0"

- packages/snaps-sdk/package.json
The package isn't published yet, so the version should be `0.0.0`.
> Set `snaps-sdk` version to `0.0.0`

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-utils/src/handlers.ts
When RPC result assertions were added, we forgot to account for transaction insight snaps returning null to signify no insight. This PR fixes this problem.
> Fix transaction insight snaps returning null

- packages/examples/packages/localization/snap.manifest.json
- packages/snaps-utils/src/manifest/manifest.test.ts
- packages/snaps-utils/src/snaps.ts
Localization files were previously not included in the checksum calculations, meaning you could change those files without the checksum changing.
> Include localization files in checksum calculations

- packages/examples/packages/localization/package.json
The localization snap was missing package.json configuration to correctly publish the locales folder which is needed for install.
> Publish locales folder in localization snap

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/home-page/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/lifecycle-hooks/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/snaps-execution-environments/lavamoat/browserify/iframe/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-process/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-thread/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/offscreen/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-executor/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-pool/policy.json
- packages/snaps-sdk/package.json
- packages/snaps-sdk/src/error-wrappers.test.ts
- packages/snaps-sdk/src/error-wrappers.ts
- packages/snaps-sdk/src/internals/error-wrappers.test.ts
- packages/snaps-sdk/src/internals/error-wrappers.ts
- packages/snaps-sdk/src/internals/index.ts
This adds Snap error wrappers of `@metamask/rpc-errors`' error functions. All error functions are wrapped in a class that extends `SnapError`, meaning they can be thrown without causing the Snap to crash.
These errors should not be thrown from internal APIs.
Closes #1825.
> Add Snap error wrappers of JSON-RPC errors

- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
- packages/snaps-execution-environments/src/common/endowments/commonEndowmentFactory.ts
- packages/snaps-execution-environments/src/common/endowments/endowments.test.browser.ts
- packages/snaps-execution-environments/src/common/endowments/index.test.ts
- packages/snaps-execution-environments/src/common/endowments/index.ts
- packages/snaps-execution-environments/src/common/endowments/network.test.ts
- packages/snaps-execution-environments/src/common/endowments/network.ts
- packages/snaps-execution-environments/src/common/validation.ts
This PR adds notifications from the network access endowment that are sent during fetch. Calling `fetch` will result in `OutboundRequest` upfront and `OutboundResponse` once the promise resolves. Furthermore, once per response object, triggering an async action, e.g. `json()` will also trigger `OutboundRequest` upfront and `OutboundResponse` once the promise resolves. The notifications pause the request processing timer in the same way that requests via `snap.request` and `ethereum.request` pause the timer.
This PR also refactors the endowment creation slightly to make it take an options bag and always require an endowment array.
Closes https://github.com/MetaMask/snaps/issues/1755
> Pause timer on fetch

- packages/snaps-jest/src/internals/structs.ts
When using the `snaps-jest` `sendTransaction` function with address values the coercing would fail and throw because the coerced value doesn't match the expected output (in this case hexadecimal). This PR fixes this oversight by converting the coerced value to hex.
> Fix coercing of address values in sendTransaction

- packages/snaps-sdk/.eslintrc.js
- packages/snaps-sdk/jest.config.js
- packages/snaps-sdk/package.json
- packages/snaps-sdk/src/internals/helpers.test.ts
- packages/snaps-sdk/src/types/caip.test.ts
- packages/snaps-sdk/src/types/methods/dialog.test.ts
- packages/snaps-sdk/src/types/methods/get-file.test.ts
- packages/snaps-sdk/src/types/methods/manage-state.test.ts
- packages/snaps-sdk/src/types/methods/notify.test.ts
- packages/snaps-sdk/src/types/permissions.test.ts
- packages/snaps-sdk/src/types/provider.test.ts
- packages/snaps-sdk/src/types/snap.test.ts
- yarn.lock
This adds type tests to the most important parts of the SDK. This helps us to catch potential type regressions in this package.
Note that this also required using `ts-jest` for running tests, since otherwise potential type issues would not be caught.
> Add type tests to SDK

- yarn.lock
Bump `sharp` to address https://github.com/MetaMask/snaps/security/dependabot/82
Dependabot failed to make this PR itself.
> Bump `sharp`

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/manifest/manifest.test.ts
- packages/snaps-utils/src/manifest/manifest.ts
Fixes an issue with the CLI generating a checksum for binary auxiliary files. Since the encoding of the files was set to `utf8` but the files were binary when fetched in the SnapController this would cause a difference in the checksum.
> Fix issues generating checksum with binary auxiliary files

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/services/AbstractExecutionService.test.ts
- packages/snaps-controllers/src/services/AbstractExecutionService.ts
- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
`AbstractExecutionService` will now properly guard against passing invalid JSON-RPC requests and `BaseSnapExecutor` will try to respond with an error if it receives an invalid JSON-RPC request that is deemed valid enough to respond.
> Fix a few issues with passing non-serializable JSON

- packages/snaps-controllers/package.json
- packages/snaps-controllers/src/cronjob/CronjobController.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/registry/json.ts
- packages/snaps-rpc-methods/package.json
- packages/snaps-simulator/package.json
- packages/snaps-utils/package.json
- yarn.lock
This PR bumps `base-controller` and `permission-controller` to the latest version. It also handles some breaking changes in the latest version of `base-controller`.
Replaces #1988 
Replaces #1986
> Bump `base-controller` and `permission-controller`

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-simulator/src/features/simulation/hooks.test.ts
- packages/snaps-simulator/src/features/simulation/hooks.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/auxiliary-files.test.ts
- packages/snaps-utils/src/auxiliary-files.ts
- packages/snaps-utils/src/base64.test.ts
- packages/snaps-utils/src/base64.ts
- packages/snaps-utils/src/bytes.test.ts
- packages/snaps-utils/src/bytes.ts
- packages/snaps-utils/src/checksum.test.ts
- packages/snaps-utils/src/checksum.ts
- packages/snaps-utils/src/index.browser.ts
- packages/snaps-utils/src/index.ts
- packages/snaps-utils/src/virtual-file/VirtualFile.ts
Adds new base64 encoding and decoding utilities that have faster performance characteristics than the current implementation. This also fixes an issue where the client would sometimes get unresponsive while encoding large files.
Fixes #1984 
```
async base64 encoding of 98095974 bytes took 596 ms
sync base64 encoding of 98095974 bytes took 86004 ms
async base64 decoding of 98095974 bytes took 5525 ms
sync base64 decoding of 98095974 bytes took 73044 ms
```
> Improve base64 encoding/decoding speeds

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.ts
In https://github.com/MetaMask/snaps/pull/1634 we removed the source code and snap state from the runtime type. But the data was still being saved wastefully in memory. This PR fixes this.
> Remove source code and state from runtime

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
Fixes an issue where a snap that never had an incoming RPC request would never be torn down by the idle timeout.
> Fix idle snap timeout for unused snap

- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/snaps-controllers/package.json
- packages/snaps-controllers/src/snaps/registry/json.ts
- packages/snaps-utils/package.json
- yarn.lock
Bumps `snaps-registry` to the latest version to fix some incompatibilities with React Native.
> Bump `snaps-registry`

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.ts
Improve SnapController constructor typing to improve compatibility with mobile. Most of the constructor arguments have sane defaults provided by the SnapController itself and are therefore allowed to be undefined. The feature flags are also allowed to be true, false and undefined.
These issues weren't caught until now because the extension integration is not typed.
> Improve `SnapController` constructor typing

- packages/snaps-utils/coverage.json
- packages/snaps-utils/package.json
- packages/snaps-utils/src/derivation-path.test.ts
- packages/snaps-utils/src/derivation-paths.ts
- packages/snaps-utils/src/index.browser.ts
- packages/snaps-utils/src/index.ts
- yarn.lock
Upstreams derivation path logic from the extension client to be used across all clients.
Fixes https://github.com/MetaMask/snaps/issues/1467
> Upstream derivation path logic from the extension client

- packages/snaps-rpc-methods/jest.config.js
- packages/snaps-rpc-methods/src/permitted/middleware.test.ts
- packages/snaps-rpc-methods/src/permitted/middleware.ts
To be on the safe side we should use the prototype `startsWith` for snaps method middleware.
> Use prototype `startsWith` for middleware

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/location/npm.test.ts
- packages/snaps-controllers/src/snaps/location/npm.ts
Refactor `NpmLocation` to move most logic to a `BaseNpmLocation` class that can be extended in the mobile client. A class extending the base class only need to implement `fetchNpmTarball` reducing code duplication. As part of this refactor I've also simplified the implementation in multiple places and improved the coverage.
Fixes https://github.com/MetaMask/snaps/issues/2040
> Refactor `NpmLocation` class

- packages/snaps-rpc-methods/jest.config.js
- packages/snaps-rpc-methods/src/permitted/getAllSnaps.test.ts
- packages/snaps-rpc-methods/src/permitted/getAllSnaps.ts
- packages/snaps-rpc-methods/src/permitted/handlers.ts
- packages/snaps-rpc-methods/src/permitted/index.ts
This adds a new permitted JSON-RPC method `wallet_getAllSnaps`, returning all the installed Snaps, regardless of whether the origin has installed them. This method is permitted in the sense that it doesn't require a permission to be called, but it's only callable from the Snaps Directory (`https://snaps.metamask.io`).
This is a temporary solution until we have a proper connection flow in the Snaps Directory.
> Add `wallet_getAllSnaps` method to get all installed Snaps

- packages/examples/packages/images/src/index.test.ts
Disable E2E testing of the `getCat` method in the image example as it uses the network.
> Disable E2E testing method that uses the network

- packages/snaps-sdk/src/ui/components/copyable.ts
This PR fixes the missing property in the `Copyable` type declaration by inferring it from the superstruc rather than writting its type.
> Fix missing property in Copyable type

- packages/snaps-utils/src/eval-worker.ts
The `global` global was missing in the eval-worker, causing eval to fail when a snap tried to access `global`.
This PR changes the eval-worker to mirror the `BaseSnapExecutor`, setting up the endowments as globals in an identical way: https://github.com/MetaMask/snaps/blob/main/packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts#L404-L417
> Fix missing `global` in eval-worker

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/package.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/test-utils/controller.ts
- packages/snaps-rpc-methods/package.json
- packages/snaps-simulator/package.json
- packages/snaps-utils/package.json
- yarn.lock
Populate subject metadata in the SnapController, allowing us to reduce code duplication in clients of the following snippet: https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/metamask-controller.js#L2367-L2373
This change is also required for preinstalled snaps to work.
> Populate subject metadata

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/cronjob/CronjobController.test.ts
- packages/snaps-controllers/src/cronjob/CronjobController.ts
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/test-utils/controller.ts
After merging #2073, I realized that we might as well remove `:snapRemoved` too. It is more confusing than `:snapUninstalled` and all current use-cases can be covered with the previously mentioned event.
> BREAKING: Remove `:snapRemoved` event

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-utils/src/snaps.ts
- packages/snaps-utils/src/test-utils/snap.ts
Adds the notion of preinstalled snaps, these are snaps that will be automatically inserted into the SnapController state on boot and made available for execution. This proves useful for platforms where installing arbitrary snaps is not supported or for shipping MetaMask-built functionality as snaps.
Closes https://github.com/MetaMask/MetaMask-planning/issues/1742
> Add support for preinstalled snaps

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/manifest/manifest.ts
- packages/snaps-utils/src/manifest/validation.ts
- packages/snaps-utils/src/test-utils/manifest.ts
- packages/snaps-utils/src/test-utils/snap.ts
Adds `initialConnections`, a new field for the manifest that can be used to pre-approve certain origins for communication with your snap, as such:
```
"initialConnections": {
"https://snaps.metamask.io": {},
"npm:filsnap": {}
},
"initialPermissions": {
"endowment:rpc": {
"dapps": true,
"snaps": true
}
},
```
This will automatically grant the subjects the required permissions to invoke the snap after an installation or update has completed. The user can still revoke these permissions in the UI anytime in the future.
Closes https://github.com/MetaMask/snaps/issues/2037
> Add support for initial connections

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/home-page/snap.manifest.json
- packages/examples/packages/images/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/lifecycle-hooks/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/signature-insights/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/snaps-execution-environments/lavamoat/browserify/iframe/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-process/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-thread/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/offscreen/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-executor/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-pool/policy.json
- packages/snaps-rpc-methods/jest.config.js
- packages/snaps-rpc-methods/src/permitted/getClientStatus.test.ts
- packages/snaps-rpc-methods/src/permitted/getClientStatus.ts
- packages/snaps-rpc-methods/src/permitted/handlers.ts
- packages/snaps-rpc-methods/src/permitted/index.ts
- packages/snaps-sdk/src/types/methods/get-client-status.ts
- packages/snaps-sdk/src/types/methods/index.ts
- packages/snaps-sdk/src/types/methods/methods.ts
Add the `snap_getClientStatus` RPC method. This RPC method is meant to return useful information about the client executing the snap. Currently it returns whether the client is in a locked state or not.
> Add `snap_getClientStatus`

- packages/snaps-rpc-methods/src/permitted/invokeKeyring.test.ts
- packages/snaps-rpc-methods/src/permitted/invokeKeyring.ts
For _permitted RPC methods_ we are able to bind the hooks to the origin, we prefer this over passing the origin where available.
> BREAKING: Use origin bound hooks for `invokeKeyring`

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/services/ProxyPostMessageStream.test.ts
- packages/snaps-controllers/src/services/ProxyPostMessageStream.ts
- packages/snaps-controllers/src/services/offscreen/OffscreenExecutionService.test.ts
- packages/snaps-controllers/src/services/offscreen/OffscreenExecutionService.ts
- packages/snaps-controllers/src/services/proxy/ProxyExecutionService.ts
- packages/snaps-execution-environments/.depcheckrc.json
- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/offscreen/index.ts
- packages/snaps-execution-environments/src/proxy/ProxySnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/proxy/ProxySnapExecutor.ts
- packages/snaps-execution-environments/tsconfig.build.json
- packages/snaps-execution-environments/tsconfig.json
Moves most offscreen logic to a shared proxy executor and execution service that can be consumed by the offscreen executor. This is also useful for mobile. This PR is very similar to #2083 but targeting main to simplify the mobile PR.
This PR also removes the notion of a passed `frameUrl` in proxy executors. Instead they use a constructor argument that defaults to a hardcoded URL based on their version.
> Move offscreen logic to shared proxy classes

- packages/examples/packages/home-page/src/index.test.ts
- packages/snaps-jest/src/helpers.test.ts
- packages/snaps-jest/src/helpers.ts
- packages/snaps-jest/src/types.ts
Adds a `renderHomePage` helper to `snaps-jest`, allowing testing of snaps home pages.
> Add home page support to `snaps-jest`

- packages/examples/packages/signature-insights/package.json
- packages/examples/packages/signature-insights/snap.manifest.json
Sets the version of the signature insights example to `0.0.0` as it has not been released yet. Otherwise this blocks release.
> Fix version on the signature insights example

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/location/npm.test.ts
- packages/snaps-controllers/src/snaps/location/npm.ts
We now know that the NPM fetching problems were caused by a bug in `tar-stream` and unrelated to our usage of `DecompressionStream`. Therefore we can reintroduce it for improved performance.
> Reintroduce `DecompressionStream`

- packages/snaps-cli/src/commands/manifest/implementation.test.ts
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/registry/json.test.ts
- packages/snaps-controllers/src/test-utils/controller.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-sdk/src/types/permissions.ts
- packages/snaps-utils/src/manifest/validation.ts
- packages/snaps-utils/src/test-utils/manifest.ts
- `snap_confirm` was removed a long time ago.
- Certain permissions were missing.
- Everything is now wrapped in `Partial`.
> Fix initial permissions types

- packages/test-snaps/package.json
- packages/test-snaps/src/features/snaps/index.ts
- packages/test-snaps/src/features/snaps/signature-insights/SignatureInsights.tsx
- packages/test-snaps/src/features/snaps/signature-insights/constants.ts
- packages/test-snaps/src/features/snaps/signature-insights/index.ts
- yarn.lock
Added a section for the signature insights example snap. 
**Note:** This is merely for installation purposes when testing, but the e2e tests for signature insights in the extension will utilize the test-dapp.
> Add signature insights to `test-snaps`

- packages/snaps-controllers/package.json
- yarn.lock
Bump `tar-stream` to the latest patch version as the patch includes a fix for a problem where tar headers would sometimes fail to decode depending on the stream performance.
This manifested as a snap installation failure.
> Bump `tar-stream`

- packages/examples/packages/cronjobs/src/index.test.ts
- packages/examples/packages/home-page/src/index.test.ts
- packages/examples/packages/transaction-insights/src/index.test.ts
- packages/snaps-jest/src/helpers.test.ts
- packages/snaps-jest/src/helpers.ts
- packages/snaps-jest/src/types.ts
With the exception of `request`, all APIs were renamed to match the name of the entry point in the Snap. This prevents confusing names like `sendSignature` (#2114) in the future.
> Rename snaps-jest APIs

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/endowments/caveats/generic.test.ts
- packages/snaps-controllers/src/snaps/endowments/caveats/generic.ts
- packages/snaps-controllers/src/snaps/endowments/caveats/index.ts
Add a utility function for validating caveat types for a permission. This lets us generically validate permissions with multiple caveat types without duplicating validation code across the permission specifications. This is useful long-term as we add more permissions that have more than 1 caveat type.
This is a prerequisite for https://github.com/MetaMask/snaps/pull/2113 and https://github.com/MetaMask/snaps/pull/2098
> Add generic caveat validation utility

- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-sdk/src/types/handlers/signature.ts
- packages/snaps-sdk/src/types/handlers/transaction.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/handlers.ts
This PR adds the ability to pass an interface id to the response of `onTransaction` and `onSignature`.
Fixes: #2124 #2125
> Add support for interactive UI to `onTransaction` and `onSignature`

- packages/snaps-utils/src/eval-worker.ts
Speed up eval-worker by removing hack to make it terminate after 1 second.
This moves the lowerbound for snap evaluation in the CLI from 1s to potentially milliseconds.
> Speed up eval-worker

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/test-utils/controller.ts
This PR makes changes to always create dynamic UI for returned static content from handlers. It introduces a `transformSnapRpcRequestResult` function that can be used in the future for any transformation needed for snap results before returning them.
This removes the need for the `SnapController` to handle phishing detection and extended validation of the UI. The `SnapInterfaceController` now manages this for all handler types and inputs.
This PR also adds an assertion to check that returned interface ids are valid.
> Always create dynamic UI for returned content

- packages/snaps-execution-environments/src/index.ts
- packages/snaps-execution-environments/src/proxy/index.ts
Export `ProxySnapExecutor` to be used in the extension for the offscreen MV3 implementation.
> Export `ProxySnapExecutor`

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/constants.ts
Allows snaps with certain permissions to be installed without being on the allowlist even when the allowlist feature flag is set.
> Loosen allowlist requirements

- packages/snaps-execution-environments/lavamoat/browserify/iframe/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-process/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-thread/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-executor/policy.json
- packages/snaps-execution-environments/lavamoat/build-system/policy.json
- packages/snaps-execution-environments/scripts/build.js
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
Reduce executor bundle sizes by tweaking a `@metamask/providers` import.
Before:
```
Finished node-thread (933 KB)
Finished node-process (933 KB)
Finished iframe (491 KB)
Finished worker-executor (945 KB)
Finished worker-pool (320 KB)
```
After:
```
Finished node-thread (816 KB)
Finished node-process (816 KB)
Finished iframe (383 KB)
Finished worker-executor (837 KB)
Finished worker-pool (320 KB)
```
Strips about 100 KB of unused code from the bundle.
> Reduce executor bundle sizes

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/structs.test.ts
- packages/snaps-utils/src/structs.ts
This adds a `validateUnion` function, which can validate a union of objects (with at least one common property), and throw readable errors if validation fails.
For example, using the following structs:
```ts
const FooStruct = object({
type: literal('a'),
value: string(),
});
const BarStruct = object({
type: literal('b'),
value: number(),
});
const Union = union([FooStruct, BarStruct]);
```
We can use the `validateUnion` function with `type` as common property:
```ts
validateUnion(value, Union, 'type');
```
If the provided value does not have a valid type (i.e., it doesn't satisfy any of the objects in the union), the function throws:
> Error: At path: type — Expected the value to be one of: "a", "b", but received: "c".
If the type matches, but not the value (`{ type: 'b', value: 'foo' …
> Add union validation utils

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/structs.test.ts
- packages/snaps-utils/src/structs.ts
This adds a `createUnion` which is a wrapper of the function introduced in #2161, but returns the (coerced) value after validation.
> Add union creation util

- .github/workflows/publish-environment.yml
- packages/snaps-execution-environments/src/proxy/ProxySnapExecutor.ts
- packages/snaps-simulator/src/features/simulation/sagas.ts
Changes AWS deployment slightly to allow for deployment of both the iframe and webview bundles.
This means that the format of the AWS URLs changes from:
```
https://execution.metamask.io/%VERSION%/index.html
```
to
```
https://execution.metamask.io/iframe/%VERSION%/index.html
https://execution.metamask.io/webview/%VERSION%/index.html
```
To be merged once we are ready to publish the webview bundle.
> Deploy multiple bundles to AWS

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/client-status/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/errors/snap.manifest.json
- packages/examples/packages/ethereum-provider/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-file/snap.manifest.json
- packages/examples/packages/home-page/snap.manifest.json
- packages/examples/packages/images/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/consumer-signer/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/json-rpc/snap.manifest.json
- packages/examples/packages/lifecycle-hooks/snap.manifest.json
- packages/examples/packages/localization/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/name-lookup/snap.manifest.json
- packages/examples/packages/network-access/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/rollup-plugin/snap.manifest.json
- packages/examples/packages/signature-insights/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/examples/packages/wasm/snap.manifest.json
- packages/snaps-cli/src/commands/build/implementation.test.ts
- packages/snaps-cli/src/config.ts
- packages/snaps-cli/src/webpack/__snapshots__/config.test.ts.snap
Disables source maps by default in the CLI, speeding up the build process for devs that don't need source maps (most currently do not with snaps).
> BREAKING: Disable source maps by default

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/structs.test.ts
- packages/snaps-utils/src/structs.ts
`getStructFailureMessage` was previously returning confusing error messages for errors related to invalid sizes. This adds proper support for these messages.
> Fix error message for invalid sizes

- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-jest/src/environment.ts
- packages/snaps-jest/src/helpers.ts
- packages/snaps-jest/src/internals/request.test.ts
- packages/snaps-jest/src/internals/request.ts
- packages/snaps-jest/src/internals/simulation/controllers.test.ts
- packages/snaps-jest/src/internals/simulation/controllers.ts
- packages/snaps-jest/src/internals/simulation/interface.test.ts
- packages/snaps-jest/src/internals/simulation/interface.ts
- packages/snaps-jest/src/internals/simulation/methods/hooks/index.ts
- packages/snaps-jest/src/internals/simulation/methods/hooks/interface.test.ts
- packages/snaps-jest/src/internals/simulation/methods/hooks/interface.ts
- packages/snaps-jest/src/internals/simulation/methods/hooks/show-dialog.test.ts
- packages/snaps-jest/src/internals/simulation/methods/hooks/show-dialog.ts
- packages/snaps-jest/src/internals/simulation/methods/specifications.test.ts
- packages/snaps-jest/src/internals/simulation/methods/specifications.ts
- packages/snaps-jest/src/internals/simulation/simulation.test.ts
- packages/snaps-jest/src/internals/simulation/simulation.ts
- packages/snaps-jest/src/internals/simulation/store/ui.ts
- packages/snaps-jest/src/test-utils/controller.ts
- packages/snaps-jest/src/test-utils/index.ts
- packages/snaps-rpc-methods/jest.config.js
- packages/snaps-rpc-methods/src/restricted/dialog.test.ts
- packages/snaps-rpc-methods/src/restricted/dialog.ts
- packages/snaps-rpc-methods/src/utils.test.ts
- packages/snaps-rpc-methods/src/utils.ts
- packages/snaps-sdk/src/types/methods/dialog.ts
This PR adds the ability to pass an interface id to the params of the `snap_dialog` RPC method. It also experiments a way to display better errors when they come from unions.
`snaps-jest` has also been updated to handle the intrerfaces ID.
Fixes: #2123 
BREAKING CHANGES:
- Now the `showDialog` hook expects an interface id.
> [BREAKING] Add support for interactive UI to `snap_dialog`

- packages/snaps-cli/src/webpack/__snapshots__/config.test.ts.snap
- packages/snaps-cli/src/webpack/config.ts
By default, Webpack will use `JsonpChunkLoadingRuntimeModule` to load chunks. This injects `document` into the Snap code, causing it to break. By setting `output.chunkFormat` to `commonjs`, we can disable `JsonpChunkLoadingRuntimeModule`.
More context here: https://github.com/MetaMask/snaps/discussions/2135
> Set `output.chunkFormat` to `commonjs` by default

- package.json
- scripts/install-chrome.sh
- yarn.lock
This updates `chromedriver` to the latest version, to add support for the latest Google Chrome.
> Update Chromedriver to 121

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/client-status/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/errors/snap.manifest.json
- packages/examples/packages/ethereum-provider/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-file/snap.manifest.json
- packages/examples/packages/home-page/snap.manifest.json
- packages/examples/packages/images/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/consumer-signer/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/json-rpc/snap.manifest.json
- packages/examples/packages/lifecycle-hooks/snap.manifest.json
- packages/examples/packages/localization/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/name-lookup/snap.manifest.json
- packages/examples/packages/network-access/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/signature-insights/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/examples/packages/wasm/snap.manifest.json
- packages/snaps-cli/src/webpack/__snapshots__/config.test.ts.snap
- packages/snaps-cli/src/webpack/config.ts
- packages/snaps-cli/src/webpack/utils.ts
SWC was previously configured to output CJS, which means any imports would be transpiled to `require`. This means that any dependencies would also be loaded as CJS, even though an ESM version may be available. By changing SWC to output ES6 code and not transpiling any imports, Webpack loads potentially more ESM code which can be better optimised and tree-shaken.
Below are the old and new file sizes of the examples. For some examples, this change reduces the file size by 70%.
<details>
<summary>Before this change</summary>
```
272K    ./bip32/dist/bundle.js
344K    ./bip44/dist/bundle.js
312K    ./browserify-plugin/dist/bundle.js
136K    ./browserify/dist/bundle.js
104K    ./client-status/dist/bundle.js
152K    ./cronjobs/dist/bundle.js
156K    ./dialogs/dist/bundle.js
4.0K …
```
> Optimise CLI Webpack configuration

- packages/snaps-sdk/src/error-wrappers.test.ts
- packages/snaps-sdk/src/internals/error-wrappers.ts
Previously you would have to do something like `new InternalError(undefined, { data: 'here' })`. Now you can omit the `undefined` parameter, and simply use `new InternalError({ data: 'here' })`.
> Improve support for Snap errors without a message

- packages/examples/packages/network-access/package.json
- packages/examples/packages/network-access/src/index.test.ts
- packages/examples/packages/network-access/tsconfig.json
- yarn.lock
This (hopefully) fixes the network access example E2Es sometimes getting stuck.
> Use process execution service for network access example

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/client-status/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/ethereum-provider/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-file/snap.manifest.json
- packages/examples/packages/images/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/consumer-signer/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/json-rpc/snap.manifest.json
- packages/examples/packages/localization/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/network-access/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/wasm/snap.manifest.json
- packages/snaps-cli/src/config.ts
- packages/snaps-cli/src/webpack/__snapshots__/config.test.ts.snap
- packages/snaps-cli/src/webpack/config.ts
- packages/snaps-cli/src/webpack/loaders/wasm.test.ts
- packages/snaps-cli/src/webpack/loaders/wasm.ts
- packages/snaps-cli/src/webpack/plugins.test.ts
- packages/snaps-cli/src/webpack/plugins.ts
- packages/snaps-cli/src/webpack/utils.test.ts
- packages/snaps-cli/src/webpack/utils.ts
- packages/snaps-utils/src/post-process.ts
- packages/snaps-webpack-plugin/src/plugin.test.ts
- packages/snaps-webpack-plugin/src/plugin.ts
Compilation warnings were previously ignored, potentially hiding important warnings from Webpack. This updates the Webpack config to show these warnings, and does some other changes to make warnings more readable.
Closes #2145.
> Show Webpack compilation warnings in CLI

- packages/snaps-cli/src/webpack/utils.test.ts
- packages/snaps-cli/src/webpack/utils.ts
Strings containing new lines would not be indented previously. This fixes that.
> Support new lines in CLI message formatting

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/registry/json.test.ts
- packages/snaps-controllers/src/snaps/registry/json.ts
Fixes an issue installing non-allowlisted Snaps in allowlist mode. Previously we would fail if resolving a version range to an allowlisted version would fail. We cannot do this anymore as some Snaps may still be available for installation in allowlist mode without the version being on the allowlist. This PR alters the `resolveVersion` function to return the unaltered version range if it isn't possible to narrow down the version to install.
Snaps that require allowlisting will still fail in the `assertIsInstallAllowed` step which follows this step. This issue was not caught before testing in the extension since the SnapController tests run with a mocked registry.
> Fix issue installing non-allowlisted Snaps in allowlist mode

- packages/examples/packages/bip32/snap.config.ts
- packages/examples/packages/bip44/snap.config.ts
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/dialogs/snap.config.ts
- packages/examples/packages/ethereum-provider/snap.config.ts
- packages/examples/packages/ethers-js/snap.config.ts
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.config.ts
- packages/examples/packages/get-file/snap.config.ts
- packages/examples/packages/home-page/snap.config.ts
- packages/examples/packages/interactive-ui/snap.manifest.json
- packages/examples/packages/interactive-ui/src/ui.ts
- packages/examples/packages/invoke-snap/packages/consumer-signer/snap.config.ts
- packages/examples/packages/invoke-snap/packages/core-signer/snap.config.ts
- packages/examples/packages/manage-state/snap.config.ts
- packages/examples/packages/network-access/snap.config.ts
- packages/examples/packages/notifications/snap.config.ts
- packages/examples/packages/signature-insights/snap.config.ts
- packages/examples/packages/transaction-insights/snap.config.ts
This updates the configuration of most example Snaps to reduce the number of warnings. Some examples also were using polyfills that were not needed anymore.
> Update example configurations

- packages/snaps-utils/src/bytes.ts
This import previously brought in `fs` even in browser contexts. This was unintentional and can be easily fixed by correcting the import to be more narrow.
> Fix VirtualFile import in browser contexts

- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
- packages/snaps-execution-environments/src/common/utils.test.ts
- packages/snaps-execution-environments/src/common/utils.ts
Enforces a size limit on JSON-RPC responses from Snaps, throwing an error if the object is larger than 64 MB.
64 MB was chosen because it seems to be the limit set by Chrome for postMessage between the extension and dapps: https://source.chromium.org/chromium/chromium/src/+/main:extensions/renderer/api/messaging/messaging_util.cc;l=65?q=%22Message%20length%20exceeded%20maximum%20allowed%20length%22&ss=chromium
> Enforce JSON-RPC response size limits

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/interface/SnapInterfaceController.test.ts
- packages/snaps-controllers/src/interface/SnapInterfaceController.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/ui.test.ts
- packages/snaps-utils/src/ui.ts
Adds sizing limits for custom UI input. Previously these inputs were only validated to have the proper formatting.
This PR adds logic to validate that the UI components provided by the Snap are within reasonable length. Both the entire UI component object is serialized to JSON and validated that it's total size is less than 250 kb. Also the total text used in the UI component is validated to be less than 50 kb.
> Add sizing limits for custom UI

- packages/test-snaps/package.json
- packages/test-snaps/src/features/snaps/images/Images.tsx
- packages/test-snaps/src/features/snaps/images/components/ShowImage.tsx
- packages/test-snaps/src/features/snaps/images/components/ShowQr.tsx
- packages/test-snaps/src/features/snaps/images/components/index.ts
- packages/test-snaps/src/features/snaps/images/constants.ts
- packages/test-snaps/src/features/snaps/images/index.ts
- packages/test-snaps/src/features/snaps/index.ts
- yarn.lock
When debugging an issue, I noticed that there was no section on the test-snaps page for the images example, so I've added one.
> Add images example to test-snaps page

- packages/snaps-cli/src/config.ts
- packages/snaps-cli/src/structs.test.ts
- packages/snaps-cli/src/structs.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/structs.test.ts
- packages/snaps-utils/src/structs.ts
Moves the `file` struct to the CLI package as it is the only place where it is currently in use.
Previously it was part of the `snaps-utils` and even included in the browser entrypoint. This PR moves it to avoid that problem.
> Move `file` struct to CLI

- packages/snaps-utils/src/post-process.test.ts
- packages/snaps-utils/src/post-process.ts
Address code scanning alert by altering the regex for HTML comment tokens used in the post processing step. Apparently `--!>` is a valid way to end an HTML comment 🤯 
Fixes https://github.com/MetaMask/snaps/security/code-scanning/1
> Fix regex for HTML comment tokens

- constraints.pro
- packages/snaps-cli/package.json
I accidentally removed `.browserslistrc` in the `tsup` refactor. This adds it back.
> Publish `.browserslistrc` in CLI

- .github/workflows/main.yml
- .github/workflows/publish-release.yml
After the `tsup` refactor we removed `build:post-tsc`. This PR fixes a problem where this script was still in use in CI.
> Fix simulator build in CI

- .github/workflows/update-pull-request.yml
The update PR workflow previously builds the examples twice. We only need to build dependencies of the examples, so we can use `build:ci` instead. The Snaps CLI doesn't do type checking, so we can skip building those too.
> Fix update pull request workflow

- packages/snaps-execution-environments/lavamoat/browserify/iframe/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-process/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/node-thread/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/policy-override.json
- packages/snaps-execution-environments/lavamoat/browserify/webview/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-executor/policy.json
- packages/snaps-execution-environments/lavamoat/browserify/worker-pool/policy.json
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/icon.test.ts
- packages/snaps-utils/src/icon.ts
Remove one usage of `Buffer` since the exported function is used in both in the browser and in the Node.js export.
> Remove usage of `Buffer` from `snaps-utils`

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/home-page/snap.manifest.json
- packages/examples/packages/images/snap.manifest.json
- packages/examples/packages/interactive-ui/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/lifecycle-hooks/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/signature-insights/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/snaps-sdk/src/ui/components/input.test.ts
- packages/snaps-sdk/src/ui/components/input.ts
Add an optional error text property to the input component. This lets Snaps provide feedback directly below input values:
> Add error text to input component

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/home-page/snap.manifest.json
- packages/examples/packages/images/snap.manifest.json
- packages/examples/packages/interactive-ui/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/lifecycle-hooks/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/signature-insights/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/snaps-execution-environments/src/common/validation.test.ts
- packages/snaps-sdk/src/types/handlers/user-input.test.ts
- packages/snaps-sdk/src/types/handlers/user-input.ts
Add an `InputChangeEvent` dynamic UI event to be triggered when an input in a form has changed. The event may be debounced in the client implementation and is not triggered instantly.
> Add `InputChangeEvent` event

- .github/workflows/build-lint-test.yml
- .github/workflows/main.yml
- .github/workflows/publish-environment.yml
- .github/workflows/publish-github-pages.yml
- .github/workflows/publish-preview.yml
- .github/workflows/publish-release.yml
- .github/workflows/update-pull-request.yml
Replaces deprecated GitHub actions of version `v3` with with `v4`.
> Replace deprecated GitHub actions

- packages/snaps-controllers/package.json
- packages/snaps-utils/package.json
- yarn.lock
This bumps `@metamask/snaps-registry` to `^3.0.1`, which fixes an issue with signature validation.
> Bump `@metamask/snaps-registry` to `^3.0.1`

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/home-page/snap.manifest.json
- packages/examples/packages/images/snap.manifest.json
- packages/examples/packages/interactive-ui/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/lifecycle-hooks/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/signature-insights/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/snaps-sdk/src/ui/components/address.test.ts
- packages/snaps-sdk/src/ui/components/address.ts
Fixes address validation in the address row component. Before this change the regex was flawed and would allow addresses longer than 42 characters.
> Fix address validation in row component

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/registry/json.test.ts
- packages/snaps-controllers/src/snaps/registry/json.ts
- packages/snaps-controllers/src/snaps/registry/registry.ts
This PR makes a few changes to the registry controller implementation to attempt to handle an unavailable registry (e.g. invalid signature) more gracefully.
Instead of throwing when the registry fails to update or populate, we return `SnapsRegistryStatus.Unavailable`. This status is meant to indicate to the `SnapController` that we can't currently access the latest registry and thus our data might be out of date. For Snaps that don't require allowlisting, this shouldn't be a problem and they will still be installable. If a user is trying to install a Snap that does require allowlisting they are now greeted with a slightly better error message.
> Handle unavailable registry more gracefully

- packages/examples/packages/network-access/src/index.test.ts
Disables the network access E2E test since it is too flaky and often blocks CI 😞
> Disable network access E2E test

- packages/snaps-utils/src/manifest/validation.ts
When implementing `maxRequestTime`, validation support for the property on `endowment:rpc` in the manifest was left out accidentally. This would cause problems when devs try to use `maxRequestTime` with the endowment permission. This PR fixes that by making the endowment use similar validation to the other handler endowments.
Fixes https://github.com/MetaMask/snaps/issues/2290
> Allow `maxRequestTime` on `endowment:rpc`

- packages/snaps-sdk/src/types/permissions.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/manifest/validation.test.ts
- packages/snaps-utils/src/manifest/validation.ts
By using Superstruct's `Describe` type, we can validate that a struct is assignable to a type. In this case, we make sure that the validation struct in `snaps-utils` matches the type in `snaps-sdk`. I had to make a small change to the type to get validation to pass.
> Validate that initial permissions type matches validation struct

- packages/create-snap/.depcheckrc.json
- packages/create-snap/package.json
- packages/create-snap/src/cmds/init/initHandler.test.ts
- packages/create-snap/src/cmds/init/initHandler.ts
- packages/create-snap/tsup.config.ts
- packages/snaps-cli/src/cli.test.ts
- packages/snaps-cli/src/cli.ts
- yarn.lock
Fixes the checks for minimum versions in the CLI. 
The minimum Node.js version we support is `18.16`, this was not reflected properly in our CLIs. After this PR the CLIs will check the minimum version themselves by looking in the package.json instead of relying on a constant.
> Fix minimum version for CLIs

- packages/snaps-cli/src/config.ts
This updates the link in CLI error messages to point to `docs.metamask.io` instead of GitHub.
> Update CLI docs link

- packages/test-snaps/src/api.ts
- packages/test-snaps/src/features/snaps/index.ts
- packages/test-snaps/src/features/snaps/multi-install/MultiInstall.tsx
- packages/test-snaps/src/features/snaps/multi-install/index.ts
Adds an entry to test-snaps for installing multiple snaps at once, this is helpful for E2E testing.
> Add multi install entry to test-snaps

- packages/snaps-jest/src/global.ts
- packages/snaps-jest/src/index.ts
- packages/snaps-jest/src/types.ts
This improves the `expect` function types by:
- Adding documentation to each matcher.
- Removing duplication between the regular and asymmetric matchers.
- Removing the need to import `expect from `@jest/globals` (though this is still recommended by Jest).
> Improve Jest expect types

- packages/snaps-utils/src/derivation-paths.ts
Specify the derivation path for Nimiq so its name is resolved when deriving public and private keys.
> Add derivation path for Nimiq

- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/notifications/src/index.test.ts
- packages/examples/packages/notifications/src/index.ts
The native notification example message was too long and would fail when testing on test-snaps. This PR fixes that.
> Fix native notification example

- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
Unencrypted state is currently not deleted when uninstalling a Snap. I've fixed this, and also added a test to check this behaviour.
> Delete unencrypted state when uninstalling a Snap

- packages/snaps-utils/src/ui.test.ts
- packages/snaps-utils/src/ui.ts
`marked` has GitHub flavored Markdown enabled by default, but we don't support GitHub flavored Markdown in the UI. This makes the validation stricter than it needs to be. This PR fixes that by disabling GitHub flavored Markdown when lexing.
> Disable GitHub flavored Markdown when lexing

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-utils/src/snaps.ts
This PR adds `initialConnections` specification from manifest to `requestState` object which is used on Snap installation or update process.
Related ticket: https://github.com/MetaMask/MetaMask-planning/issues/1895
Blocking: https://github.com/MetaMask/MetaMask-planning/issues/1895
> Add initialConnections to requestState

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
This PR fixes a few problems discovered when trying to integrate the new encryption caching mechanism.
When the Snap is initially installed, its state will be `undefined`. Thus, `getSnapState` needs to account for this when deciding when to return `null`, which is the normalized value we use for lack of state.
Also in our tests, the salt is always the same, so tests were passing, but in reality the salt changes every time `generateSalt` is called. For that reason, we cache the salt alongside the encryption key for a session.
> Fix encryption key caching issues

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/examples/packages/client-status/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/ethereum-provider/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-file/snap.manifest.json
- packages/examples/packages/home-page/snap.manifest.json
- packages/examples/packages/images/snap.manifest.json
- packages/examples/packages/interactive-ui/snap.manifest.json
- packages/examples/packages/interactive-ui/src/index.test.ts
- packages/examples/packages/interactive-ui/src/index.ts
- packages/examples/packages/invoke-snap/packages/consumer-signer/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/json-rpc/snap.manifest.json
- packages/examples/packages/lifecycle-hooks/snap.manifest.json
- packages/examples/packages/localization/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/network-access/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/rollup-plugin/snap.manifest.json
- packages/examples/packages/signature-insights/snap.manifest.json
- packages/examples/packages/transaction-insights/snap.manifest.json
- packages/examples/packages/wasm/snap.manifest.json
- packages/examples/packages/webpack-plugin/snap.manifest.json
- packages/snaps-sdk/src/types/handlers/user-input.ts
Fixes an unintentional issue where null was disallowed in `FormSubmitEventStruct.value`. This value represents the form state and `null` is intended to be used as a lack of value. This also fixes a problem where Snaps would error if a user tried to submit an empty form field.
> Allow `null` in `FormSubmitEventStruct` form state

- packages/snaps-controllers/src/interface/SnapInterfaceController.test.ts
- packages/snaps-controllers/src/interface/SnapInterfaceController.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/json.test.ts
- packages/snaps-utils/src/json.ts
Increase the max UI size limit to 10 MB. This lets Snaps use images of larger size without running into this issue.
Also modifies the implementation slightly to improve performance, instead of validating that the JSON blob is valid JSON, we strictly calculate the size of the blob.
Fixes #2341
> Increase max UI size limit

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/package.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/test-utils/controller.ts
- packages/snaps-controllers/src/utils.test.ts
- packages/snaps-controllers/src/utils.ts
- yarn.lock
The permission diff calculation was incorrect when considering caveats.
Because of this, changes to caveats were not always correctly applied when updating a Snap.
One specific instance of this was updating a Snap with:
```
'endowment:rpc': { dapps: true },
```
to
```
'endowment:rpc': { allowedOrigins: ['https://metamask.io'] },
```
This problem was fixed by introducing `permissionsDiff` which follows the implementation of `setDiff` except for the additional condition that when the permission is included in both permission sets, it is subtracted if the caveats differ.
> fix: account for caveats in permissions difference calculation

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
Fixes a problem where if multiple simultaneous requests were sent to a Snap that resulted in an error, termination would be attempted multiple times causing unintentional errors to be surfaced to the caller.
This is fixed by making sure `stopSnap` is only called once even if we have multiple pending requests for the Snap.
> fix: gracefully handle errors for multiple failing requests

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/services/AbstractExecutionService.test.ts
- packages/snaps-controllers/src/services/AbstractExecutionService.ts
- packages/snaps-controllers/src/services/ExecutionService.ts
- packages/snaps-controllers/src/services/iframe/IframeExecutionService.ts
- packages/snaps-controllers/src/services/node-js/NodeProcessExecutionService.ts
- packages/snaps-controllers/src/services/node-js/NodeThreadExecutionService.ts
- packages/snaps-controllers/src/services/offscreen/OffscreenExecutionService.test.ts
- packages/snaps-controllers/src/services/proxy/ProxyExecutionService.ts
- packages/snaps-controllers/src/services/webview/WebViewExecutionService.test.ts
- packages/snaps-controllers/src/services/webworker/WebWorkerExecutionService.ts
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/Timer.test.ts
- packages/snaps-controllers/src/snaps/Timer.ts
Refactor execution timeout logic to fix a problem where the execution worker would not be torn down correctly when failing to initialize. This PR also moves the entire initialization timeout logic to the `AbstractExecutionService`, simplifying the `SnapController`. Moving the timeout logic fixes problems where job initialization was not cancelled properly resulting in "Snap is already being executed", since execution of the async functions inside `AbstractExecutionService` would continue even after the timeout.
The ExecutionService gets an optional `maxInitTime` constructor argument that can be set to define init time for the specific service. This timeout value is spread between initiating the execution job and running the first execution of the Snap. If the execution environment fails …
> fix: properly tear down partially initialized executors

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/Timer.test.ts
- packages/snaps-controllers/src/snaps/Timer.ts
Fixes an issue where terminating a Snap that is currently executing (e.g. when removing it) would cause unexpected errors to be thrown.
Fixes #2300
> fix: properly handle termination of Snaps while executing

- packages/snaps-controllers/src/services/AbstractExecutionService.test.ts
- packages/snaps-controllers/src/services/iframe/IframeExecutionService.test.browser.ts
- packages/snaps-controllers/src/services/node-js/NodeProcessExecutionService.test.ts
- packages/snaps-controllers/src/services/node-js/NodeThreadExecutionService.test.ts
- packages/snaps-controllers/src/services/webworker/WebWorkerExecutionService.test.browser.ts
- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
- packages/snaps-jest/src/internals/server.test.ts
- packages/snaps-jest/src/test-utils/snap/snap.js
- packages/snaps-jest/src/test-utils/snap/snap.manifest.json
If no valid exports were found during initial eval of the Snap, fail early instead of potentially throwing misleading errors later.
> fix: fail starting Snap if no exports found

- packages/snaps-cli/src/webpack/__snapshots__/config.test.ts.snap
- packages/snaps-cli/src/webpack/config.ts
Disables `experiments.topLevelAwait` in the Webpack config. This was enabled by default in Webpack `5.83.0`, but is unsupported in Snaps.
With this flag disabled, trying to build a Snap with top level await will result in:
```
• Module parse failed: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enable it)
File was processed with these loaders:
* ../../node_modules/swc-loader/src/index.js
You may need an additional loader to handle the result of these loaders.
Error: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enable it)
at .../node_modules/webpack/lib/dependencies/HarmonyDetectionParserPlugin.js:68:11
at Hook.eval [as call] (eval at create (.../node_modules/tapable/lib/HookCodeFactory.js:19:10), …
```
> fix: disable top level await

- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/utils.ts
Unblock `eth_sendRawTransaction` since it doesn't show a confirmation but is just a passthrough to the node for broadcasting a transaction.
> chore: unblock `eth_sendRawTransaction`

- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-utils/src/handlers.ts
Snaps should not be required to to export `onUserInput` if they don't care to use it. This PR makes the export optional and uses existing functionality to return `null` if calls to the undefined export are detected.
Fixes #2364
> fix: make `onUserInput` export optional

- packages/examples/packages/jsx/snap.manifest.json
- packages/snaps-sdk/src/jsx/jsx-dev-runtime.test.tsx
- packages/snaps-sdk/src/jsx/jsx-dev-runtime.ts
- packages/snaps-sdk/src/jsx/jsx-runtime.test.tsx
- packages/snaps-sdk/src/jsx/jsx-runtime.ts
I assumed keys were part of the props, but it's actually a separate parameter for the `jsx` function. I've updated the runtime to properly pass keys to components.
> Forward keys to JSX component

- packages/test-snaps/package.json
- packages/test-snaps/src/features/snaps/index.ts
- packages/test-snaps/src/features/snaps/jsx/Jsx.tsx
- packages/test-snaps/src/features/snaps/jsx/constants.ts
- packages/test-snaps/src/features/snaps/jsx/index.ts
- yarn.lock
This adds a section for the JSX example Snap to `test-snaps`. It just has one button, which triggers the UI with JSX.
> Add JSX example to test-snaps

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/ui.test.tsx
- packages/snaps-utils/src/ui.tsx
To make `getJsxChildren` easier to use in practice, I've updated it to return an array of `JSXElement | string`, instead of the more generic `SnapNode`. It also filters nullish values now.
> Make `getJsxChildren` return array of `JSXElement | string`

- packages/snaps-sdk/src/ui/components/address.ts
- packages/snaps-sdk/src/ui/components/button.ts
- packages/snaps-sdk/src/ui/components/copyable.ts
- packages/snaps-sdk/src/ui/components/divider.ts
- packages/snaps-sdk/src/ui/components/form.ts
- packages/snaps-sdk/src/ui/components/heading.ts
- packages/snaps-sdk/src/ui/components/image.ts
- packages/snaps-sdk/src/ui/components/input.ts
- packages/snaps-sdk/src/ui/components/panel.ts
- packages/snaps-sdk/src/ui/components/row.ts
- packages/snaps-sdk/src/ui/components/spinner.ts
- packages/snaps-sdk/src/ui/components/text.ts
Now that JSX is merged, we can deprecate the legacy UI components. I've added a deprecation notice to all the legacy UI functions.
> Add deprecation notice to legacy UI components

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/services/AbstractExecutionService.ts
- packages/snaps-controllers/src/services/proxy/ProxyExecutionService.ts
Fixes a problem with proxy execution environments having unintentionally low timeout values. The assumption is that `initJob` resolves once the execution environment is perceived to be ready for requests and therefore we ping the execution env with a very low timeout to detect issues and fail early. However, `initJob` was resolving way before the actual proxy executor was ready. This problem can be fixed by effectively pinging the execution environment as part of the initialization process of proxy executors as this loads the proxy executor and doesn't resolve until the executor responds.
Fixes #2372
> fix: unintentionally low timeout value for proxy executors

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
Preinstalled snaps should not be cleaned up. This ensures they are saved and have the correct permissions when a cleanup is performed.
This comes from testing with Extensions PreInstalled snaps. As a user is setting up a new wallet, the SnapController will have its state cleared.
https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/metamask-controller.js#L3780
Due to this, any Snap calls made using preinstalled snaps will fail with:
`Snap "npm:<SNAP_ID>" is not permitted to use "endowment:rpc"`
> fix: instantiate preinstalled snaps on cleanup

- packages/snaps-sdk/jsx-dev-runtime.d.ts
- packages/snaps-sdk/jsx-runtime.d.ts
- packages/snaps-sdk/jsx.d.ts
- packages/snaps-sdk/package.json
- packages/snaps-sdk/tsconfig.json
Add missing TypeScript declarations for JSX entry points that don't use the `exports`.
> fix: add missing TypeScript declarations for JSX entry points

- packages/snaps-rpc-methods/src/permitted/invokeSnapSugar.test.ts
- packages/snaps-rpc-methods/src/permitted/invokeSnapSugar.ts
Supersedes: #2398
We are moving our permission middleware ahead of all RPC method implementations in the extension (https://github.com/MetaMask/metamask-extension/pull/24472) and mobile (https://github.com/MetaMask/metamask-mobile/pull/9521). This breaks the current implementation of `wallet_invokeSnap`, which assumes that it's called before the permission middleware (which calls the implementation of `wallet_snap`, which is a restricted method).
This PR refactors `wallet_invokeSnap` to use an `invokeSnap()` hook, intended to be `PermissionController.executeRestrictedMethod()` bound to the requesting origin and `'wallet_snap'`.
> refactor!(snaps-rpc-methods): Use hooks in `wallet_invokeSnap` instead of remapping the request to `wallet_snap`

- packages/examples/packages/bip32/package.json
- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/package.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/consumer-signer/package.json
- packages/examples/packages/invoke-snap/packages/core-signer/package.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/snaps-jest/package.json
- packages/snaps-rpc-methods/package.json
- packages/snaps-rpc-methods/src/restricted/getBip32Entropy.test.ts
- packages/snaps-rpc-methods/src/restricted/getBip32PublicKey.test.ts
- packages/snaps-rpc-methods/src/restricted/getBip32PublicKey.ts
- packages/snaps-rpc-methods/src/utils.test.ts
- packages/snaps-rpc-methods/src/utils.ts
- packages/snaps-sdk/package.json
- packages/snaps-sdk/src/types/permissions.test.ts
- packages/snaps-sdk/src/types/permissions.ts
- packages/snaps-simulator/package.json
- packages/snaps-utils/coverage.json
- packages/snaps-utils/package.json
- packages/snaps-utils/src/derivation-path.test.ts
- packages/snaps-utils/src/derivation-paths.ts
- packages/snaps-utils/src/manifest/validation.test.ts
- packages/snaps-utils/src/manifest/validation.ts
- yarn.lock
This bumps `@metamask/key-tree` to `9.1.0` and applies some changes to support the new BIP-32-Ed25519 derivation.
Replaces #2400.
> Add support for BIP-32-Ed25519 / CIP-3 key derivation

- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/test-utils/controller.ts
Fixes a bug where we weren't correctly merging caveat values when using initial connections, since we were spreading the entire caveat and not just the value.
> fix: correctly merge caveats when using initial connections

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/utils.test.ts
- packages/snaps-controllers/src/utils.ts
- packages/snaps-utils/src/test-utils/snap.ts
This PR adds additional logic for calculating difference of `initialConnections`. This is required so changes can be displayed in the UI for Snap update process.
New method is added to `SnapController` and integrated within Snap update handling functions.
> Add connections diff calculations needed for Snap update

- docs/internals/architecture.md
Adds an entity diagram of the Snaps architecture.
> docs: Add entity diagram to `docs/internals/architecture.md`

- .github/workflows/build-lint-test.yml
- .github/workflows/main.yml
Bump CodeCov to latest version and add upload token secret to fix issues publishing code coverage.
> ci: Bump CodeCov action

- packages/snaps-jest/src/matchers.ts
This fixes two problems with diff outputs when using `toRender` with legacy UI:
- Firstly we had flipped actual and expected causing confusing output
- Secondly we were diffing not just the content but also the rest of the response object unnecessarily
> fix: properly diff when using legacy UI with `toRender` matcher

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip32/src/index.test.ts
- packages/examples/packages/bip32/src/index.ts
- packages/examples/packages/bip32/src/types.ts
- packages/test-snaps/src/features/snaps/bip32/BIP32.tsx
- packages/test-snaps/src/features/snaps/bip32/components/SignMessage.tsx
Add support for the `ed25519Bip32` curve to the BIP-32 example Snap for E2E testing purposes.
> Add support for `ed25519Bip32` to the BIP-32 example snap

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
Add `getFeatureFlags` constructor argument that can return dynamic feature flags at runtime, use the feature flag to assert whether the Snaps platform is allowed to run.
Closes https://github.com/MetaMask/MetaMask-planning/issues/2556
> feat: add feature flag to disable platform

- packages/snaps-jest/src/internals/request.test.tsx
- packages/snaps-jest/src/internals/request.ts
When using `.getInterface()` with a Snap that produces an invalid interface, the tests would previously time out. This PR aims to catch the problem and fail sooner with a better error message.
> fix: properly handle invalid interfaces during test

- packages/snaps-execution-environments/package.json
- packages/snaps-sdk/package.json
- packages/test-snaps/package.json
- yarn.lock
Bump `@metamask/providers` from 16 to latest [17](https://github.com/MetaMask/providers/releases/tag/v17.0.0).
> deps: @metamask/providers 17

- constraints.pro
- packages/snaps-controllers/package.json
- packages/snaps-controllers/react-native.d.ts
- packages/snaps-controllers/react-native.js
- packages/snaps-controllers/tsconfig.json
`@metamask/snaps-controllers` has a `/react-native` export, but React Native seemingly doesn't support exports (or at least the version we use in the mobile repository)? This adds a `react-native.js` and `react-native.d.ts` file to support tools that don't support exports.
> Add files for `react-native` export compatibility

- tsconfig.packages.json
Modifies TS paths to point more directly to the JSX runtime. This prevents problems where TS would incorrectly use an import of `/jsx-runtime`.
```
children: import("@metamask/snaps-sdk/jsx-runtime").MaybeArray<import("@metamask/snaps-sdk/jsx-runtime").SnapElement<{
value: string;
children: string;
}, "Option">>;
```
> fix: correct JSX runtime path in tsconfig

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/json-rpc.test.ts
- packages/snaps-utils/src/json-rpc.ts
Allow wildcards in `allowedOrigins` by generating a RegExp based on each allowed origin and testing the origin against it.
Closes #2457
> feat: allow wildcards in `allowedOrigins`

- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-utils/src/snaps.ts
Adds a `hidden` flag that preinstalled Snaps can use to signal whether they should be displayed to the user or not.
> feat: add hidden flag for preinstalled Snaps

- packages/examples/packages/interactive-ui/src/index.test.tsx
- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/interface/utils.test.tsx
- packages/snaps-controllers/src/interface/utils.ts
Fixes a problem where the default state for a dropdown would be `null` even though the UI would show option 1 as selected.
We fix this by using option 1 as the default state value if nothing is specified.
> fix: use first dropdown option as the default value

- packages/snaps-sdk/src/jsx/component.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
- packages/snaps-utils/src/ui.tsx
In #2466 we changed the types and validation of JSX components to use `NonEmptyArray<Type>` as children. This causes issues however when using utility functions like `.map()` and `.filter()`, since they return a regular `Type[]` type. This is not great for devex, since it would require type assertions everywhere.
I've changed the types to accept `Type[]`, though we technically still validate `NonEmptyArray<Type>`.
> Change types to allow regular array types as children

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/constants.ts
- packages/snaps-controllers/src/test-utils/controller.ts
Fixes a problem where encrypted state blobs produced before `keyMetadata` was added would fail to decrypt. 
The encryptor would attempt to use the latest key derivation parameters when no `keyMetadata` was passed in, causing a failure to decrypt: https://github.com/MetaMask/metamask-extension/blob/ed5ec2d28f7e118803c6fdc74abe90db4e00f480/app/scripts/lib/encryptor-factory.ts#L78-L82
This PR simply falls back to the legacy key derivation parameters whenever `keyMetadata` isn't present strictly for decryption purposes. The default key derivation parameters are still in use for all encryption.
> fix: properly decrypt legacy state blobs

- packages/snaps-sdk/src/jsx/components/form/Dropdown.ts
- packages/snaps-sdk/src/jsx/components/form/Input.ts
Removes a line in the documentation about `Dropdown` and `Input` only being children of `Field`. This is not accurate as they can also be used outside of forms.
> chore: Correct docs for Input and Dropdown

- packages/examples/packages/name-lookup/snap.manifest.json
- packages/examples/packages/name-lookup/src/index.test.ts
- packages/examples/packages/name-lookup/src/index.ts
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-sdk/src/types/handlers/name-lookup.ts
- packages/snaps-utils/src/handlers.ts
Updating the name lookup response object to include a `domainName` property to let a snap indicate which domain the returned address was resolved against. This essentially allows for fuzzy matching results to be properly displayed in the extension.
> Update `onNameLookup` response

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/services/offscreen/OffscreenExecutionService.test.ts
- packages/snaps-controllers/src/services/offscreen/OffscreenExecutionService.ts
Previously, the offscreen document needed to be created from the `OffscreenExecutionService` because the extension did not do any offscreen set up. Nowadays though, the offscreen document is used by the extension for functionality other than Snaps, and the set up is handled from the extension.
Instead, we the offscreen service now accepts a `Promise` which should resolve when the offscreen document is ready. The service will wait for the promise to resolve before continuing.
> BREAKING: Defer creation of offscreen document in `OffscreenExecutionService`

- packages/examples/packages/jsx/snap.manifest.json
- packages/examples/packages/jsx/src/components/Counter.tsx
This adds a `Tooltip` component in the JSX example snap for ease of testing.
> Add `Tooltip` to JSX example

- packages/snaps-execution-environments/src/common/endowments/interval.test.ts
- packages/snaps-execution-environments/src/common/endowments/interval.ts
- packages/snaps-execution-environments/src/common/endowments/timeout.test.ts
- packages/snaps-execution-environments/src/common/endowments/timeout.ts
Tiny fix to support parameters in `setTimeout` and `setInterval`. This increases compatibility with ecosystem code that may use this functionality and was an oversight to not support initially.
> fix: Support parameters in `setTimeout` and `setInterval`

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/manifest/validation.test.ts
- packages/snaps-utils/src/manifest/validation.ts
- packages/snaps-utils/src/structs.test.ts
- packages/snaps-utils/src/structs.ts
This PR introduces `mergeStructs` which merges structs, including refinements, which `superstruct`s `assign` does not do by default. This also fixes a bug where `endowment:rpc: {}` would not be reported as invalid until attempting to install the Snap. 
Fixes #2405
> fix: Properly merge structs

- packages/examples/packages/interactive-ui/snap.manifest.json
- packages/examples/packages/interactive-ui/src/components/InteractiveForm.tsx
- packages/examples/packages/interactive-ui/src/components/Result.tsx
- packages/examples/packages/interactive-ui/src/index.test.tsx
- packages/snaps-jest/src/internals/simulation/interface.test.tsx
- packages/snaps-jest/src/internals/simulation/interface.ts
Add support for checkboxes in `snaps-jest` by allowing `clickElement` to also simulate clicks on checkboxes.
Also expands the interactive UI example to include a checkbox.
> feat: Support checkboxes in `snaps-jest`

- packages/examples/packages/jsx/package.json
- packages/examples/packages/jsx/snap.manifest.json
- packages/examples/packages/jsx/src/components/Counter.tsx
This moves the bold tags in the example snap to the number, allowing for easier E2E testing.
> Move bold tags in JSX Example Snap

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
For certain platforms, we want to disable installation of external Snaps while allowing preinstalled Snaps. This PR adds a feature flag that disables installation of new Snaps.
> feat: Add feature flag to disable Snap installation

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/utils.test.ts
- packages/snaps-controllers/src/utils.ts
This PR adds logic to account for revoked origins when calculating the difference in `initialConnections`. Essentially, we don't need to revoke permissions that are already revoked and we want to show revoked connections as being re-added in the UI.
Fixes #2532
> fix: Account for revoked origins in `initialConnections`

- packages/snaps-execution-environments/scripts/build.js
Inline the Snaps execution bundle in the WebView index.html, this will get us closer to running Snaps without a remote execution environment on mobile.
> feat: Inline WebView bundle

- packages/snaps-execution-environments/scripts/build.js
This removes some code duplication from the LavaMoat build script following #2528.
> Remove code duplication in LavaMoat build script

- packages/snaps-utils/src/json-rpc.test.ts
- packages/snaps-utils/src/json-rpc.ts
Fixes an oversight in the regex generation for `allowedOrigins` that allows a bypass of the functionality due to the regex not being properly terminated.
Also fixes a mistake in the regex generation that wouldn't properly add `.*` to the regex but instead use somewhat escaped characters.
> fix: Properly terminate origin regex with $

- package.json
- packages/snaps-rpc-methods/CHANGELOG.md
- packages/snaps-rpc-methods/package.json
- packages/snaps-sdk/CHANGELOG.md
- packages/snaps-sdk/package.json
- packages/snaps-utils/CHANGELOG.md
- packages/snaps-utils/package.json
This reverts commit ffa9dd10b58c227e44d2249845593f8aee43c574.
> Revert "Release/56.0.0 (#2581)"

- package.json
- packages/snaps-rpc-methods/CHANGELOG.md
- packages/snaps-rpc-methods/package.json
- packages/snaps-sdk/CHANGELOG.md
- packages/snaps-sdk/package.json
- packages/snaps-utils/CHANGELOG.md
- packages/snaps-utils/package.json
This is the release candidate for v56.0.0.
The previous release candidate (https://github.com/MetaMask/snaps/pull/2583) was completely overwritten by a main branch merge commit (https://github.com/MetaMask/snaps/commit/cb55071ea14e0730b42911d1c8ec135c01d791c0), because the preceding revert commit (https://github.com/MetaMask/snaps/pull/2582) introduced "newer" changes than the commits in the release candidate branch. For future reference, rebasing would be safer in this situation.
As a result, the main branch is currently restored to its original state prior to the first release attempt (ffa9dd10b58c227e44d2249845593f8aee43c574), enabling us to move forward with this PR without having to merge an additional revert commit.
This commit reverts commit …
> Release 56.0.0

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
`#handlePreinstalledSnaps` previously did not account for initial connections in preinstalled Snaps. I've added a call to `#handleInitialConnections` if the preinstalled Snap has initial connections.
Closes #2588.
> Handle initial connections for preinstalled Snaps

- package.json
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/manifest/manifest.test.ts
- packages/snaps-utils/src/manifest/validators/is-localization-file.test.ts
- packages/snaps-utils/src/manifest/validators/is-localization-file.ts
- packages/snaps-utils/src/manifest/validators/is-package-json.test.ts
- packages/snaps-utils/src/manifest/validators/is-package-json.ts
- packages/snaps-utils/src/manifest/validators/is-snap-manifest.test.ts
- packages/snaps-utils/src/manifest/validators/is-snap-manifest.ts
- packages/snaps-utils/src/structs.ts
- packages/snaps-webpack-plugin/src/plugin.test.ts
- packages/snaps-webpack-plugin/src/plugin.ts
- scripts/install-chrome.sh
- yarn.lock
> Improve errors in checkManifest

- packages/snaps-utils/package.json
- yarn.lock
Bumps `fast-xml-parser` to address a Dependabot advisory: https://github.com/MetaMask/snaps/security/dependabot/96
Dependabot was not able to apply this bump by itself.
> chore: Bump fast-xml-parser

- packages/test-snaps/src/features/snaps/dialogs/Dialogs.tsx
This adds a button to trigger the `showCustom` method of the dialog example snap in `test-snaps`.
> Add `Custom` button to the dialog example snap in `test-snaps`

- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/location/http.ts
- packages/snaps-controllers/src/snaps/location/npm.ts
- packages/snaps-controllers/src/snaps/registry/json.ts
Fixes `fetch` binding under LavaMoat by using `undefined` as the parameter instead of `globalThis`, as suggested here: https://github.com/MetaMask/metamask-extension/pull/26431#issuecomment-2293923392
> fix: Fix fetch binding under LavaMoat

- packages/snaps-controllers/src/snaps/registry/json.ts
Fixes the `SnapsRegistryMessenger` type and the `JsonSnapsRegistry` class. Currently they do not fulfill their intended specifications correctly. 
- [Define the `*:getState` action using the `ControllerGetStateAction` utility type](https://github.com/MetaMask/core/blob/add-controller-guidelines/docs/writing-controllers.md#define-the-getstate-action-using-the-controllergetstateaction-utility-type)
- [Define the `*:stateChange` event using the `ControllerStateChangeEvent` utility type](https://github.com/MetaMask/core/blob/add-controller-guidelines/docs/writing-controllers.md#define-the-statechange-event-using-the-controllerstatechangeevent-utility-type)
- [Define and export a type union for internal action types](https://github.com/MetaMask/core/blob/add-controller-guidelines/docs/writing-c …
> fix(snaps-registry): Define missing `getState` action, `stateChange` event

- packages/snaps-cli/src/main.ts
This PR hides browserlist warning when using our CLI. This error is not useful to our users.
fixes #2614
> Hide browserlist warning in the CLI

- packages/test-snaps/package.json
`--all` can't be used with `--worktree` anymore
> Fix test-snaps after yarn upgrade

- packages/examples/packages/localization/snap.manifest.json
- packages/examples/packages/localization/src/locales.ts
We're deprecating `snap_getLocale` in the future.
> Use `snap_getPreferences` in localization example

- packages/snaps-utils/src/derivation-paths.ts
Adds the BTC Taproot derivation paths to our hardcoded list since they do not follow SLIP44.
> chore: Add BTC taproot derivation paths

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/ui.test.tsx
- packages/snaps-utils/src/ui.tsx
This improves the error handling of `validateLink` in case of assertion errors. Previously we used `instanceof`, which can cause false negatives when importing from libraries. I've changed it to look at the error code instead.
> Improve `validateLink` error handling

- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-utils/src/snaps.ts
Adds a `hideHeader` flag that preinstalled Snaps can use to signal whether they should be displaying a header in the UI or not.
> feat: add `hideHeader` flag for preinstalled Snaps

- package.json
- packages/create-snap/package.json
- packages/snaps-browserify-plugin/package.json
- packages/snaps-cli/package.json
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/package.json
- packages/snaps-jest/package.json
- packages/snaps-rollup-plugin/package.json
- packages/snaps-rpc-methods/package.json
- packages/snaps-sdk/package.json
- packages/snaps-utils/package.json
- packages/snaps-webpack-plugin/package.json
- yarn.lock
This bumps `ts-bridge` to `0.5.1`, which fixes several issues compared to the current version.
> Bump `ts-bridge` to `0.5.1`

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/form/Button.test.tsx
- packages/snaps-sdk/src/jsx/components/form/Button.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
This will allow `Button` in the `Footer` be linked to a specific form so that it also can submit the form.
```tsx
<Container>
<Form name="foo">
<Input />
</Form>
<Footer>
<Button type="submit" form="foo" />
</Footer>
</Container>
```
> Added form property to Button JSX component

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/component.ts
- packages/snaps-sdk/src/jsx/components/form/Field.test.tsx
- packages/snaps-sdk/src/jsx/components/form/Field.ts
- packages/snaps-sdk/src/jsx/validation.ts
This fixes an issue when using a conditional in a `Field` children.
> Fix type issue with `Field` children

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/Box.test.tsx
- packages/snaps-sdk/src/jsx/components/Box.ts
- packages/snaps-sdk/src/jsx/validation.ts
This adds the `center` prop to the `Box` component allowing the childrens in it to be center aligned.
> Add `center` prop to `Box` component

- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-utils/src/snaps.ts
We made a conclusion that there are more things we should hide for preinstalled Snaps, like SnapIcon inside Snap custom footer button or maybe even something else in the future. 
So the decision is made to make this flag name more generic. 
Flag `hideHeader` is renamed to `hideSnapBranding`.
> Rename hideHeader flag to hideSnapBranding

- packages/examples/packages/interactive-ui/snap.manifest.json
- packages/examples/packages/interactive-ui/src/components/InteractiveForm.tsx
- packages/examples/packages/interactive-ui/src/components/Result.tsx
- packages/examples/packages/interactive-ui/src/index.test.tsx
- packages/snaps-jest/src/helpers.test.tsx
- packages/snaps-jest/src/internals/request.test.tsx
- packages/snaps-jest/src/internals/simulation/interface.test.tsx
- packages/snaps-jest/src/internals/simulation/interface.ts
- packages/snaps-jest/src/types/types.ts
Add example of `<Selector>` component to Interactive UI Snap example. Also, add `snaps-jest` tests that cover `<Selector>` component functionality.
Fixes: https://github.com/MetaMask/snaps/issues/2701
> Add example for Selector UI component

- packages/snaps-controllers/src/interface/SnapInterfaceController.test.tsx
The interface controller uses `getJsonSizeUnsafe` to determine the size of an interface object. For some reason this takes a long time for large legacy UI components, especially in CI.
> Mock `getJsonSizeUnsafe` to speed up tests

- .github/workflows/publish-release.yml
The execution environment wasn't built in de publish workflow, resulting in the execution bundles not being part of the NPM package.
> Fix missing build step in publish workflow

- packages/snaps-sdk/package.json
The exports in `snaps-sdk` were wrongfully specifying `default` before `types` in some cases. The `types` field for the JSX entrypoints was also pointing to the wrong location.
> Fix package exports in `snaps-sdk`

- packages/snaps-controllers/package.json
This fixes the package exports in `snaps-controllers`. The `types` field was pointing to the wrong location.
> Fix package exports in `snaps-controllers`

- packages/snaps-controllers/src/services/browser.test.ts
- packages/snaps-controllers/src/services/webview/WebViewMessageStream.ts
- packages/snaps-controllers/src/services/webview/index.ts
This exports the `WebViewMessageStream` class and related types from the `react-native` entrypoint in `@metamask/snaps-controllers`.
> Export `WebViewMessageStream` and related types

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/ui.test.tsx
- packages/snaps-utils/src/ui.tsx
This improves the hostname validation when using a list of emails rather than a single email.
> Validate list of emails in `validateLink` function

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/Heading.test.tsx
- packages/snaps-sdk/src/jsx/components/Heading.ts
- packages/snaps-sdk/src/jsx/components/Text.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
This PR adds an optional `size` prop to the `Heading` component. I can be `md` or `lg`.
> feat: Add the `size` prop to `Heading`

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/Link.test.tsx
- packages/snaps-sdk/src/jsx/components/Link.ts
- packages/snaps-sdk/src/jsx/components/Row.test.tsx
- packages/snaps-sdk/src/jsx/components/Row.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
This PR allows two things:
- `Link` to be a children of `Row`
- `Address` to be a children of `Link`
Fixes: #2757
> Allow `Link` in `Row` and `Address` in `Link`

- packages/snaps-controllers/src/services/iframe/IframeExecutionService.ts
- packages/snaps-controllers/src/services/webworker/WebWorkerExecutionService.ts
- packages/snaps-execution-environments/src/proxy/ProxySnapExecutor.ts
- packages/snaps-utils/src/iframe.test.browser.ts
- packages/snaps-utils/src/iframe.ts
This PR refactors the `createWindow` function to use an options bag for its parameters, improving clarity and extensibility. Additionally, it introduces a new `testId` option, allowing customization of the `data-testid` attribute for the generated iframe.
We need this change in the [MetaMask/ocap-kernel ](https://github.com/MetaMask/ocap-kernel/) package ([see issue](https://github.com/MetaMask/ocap-kernel/issues/91)), where the `createWindow` function is used, to set a different testId that doesn't conflict with the snaps iframe. This will ensure clear differentiation when using iframes across different packages.
Updated and expanded the test suite to cover the presence and absence of sandbox and testId attributes.
> Convert createWindow parameters to options bag and add testid option

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/interface/utils.test.tsx
- packages/snaps-controllers/src/interface/utils.ts
This PR adds the necessary logic to handle interface state for `AccountSelector`
> Add interface state handling for `AccountSelector`

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/form/AccountSelector.test.tsx
- packages/snaps-sdk/src/jsx/components/form/AccountSelector.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
This PR changes the `chainId` prop of the `AccountSelector` to `chainIds` that is an array of CAIP-2 chain IDs.
> Allow multiple chain ID in `AccountSelector`

- packages/examples/packages/bip32/snap.manifest.json
- packages/examples/packages/bip44/snap.manifest.json
- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/examples/packages/client-status/snap.manifest.json
- packages/examples/packages/cronjobs/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/ethereum-provider/snap.manifest.json
- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/file-upload/snap.manifest.json
- packages/examples/packages/get-entropy/snap.manifest.json
- packages/examples/packages/get-file/snap.manifest.json
- packages/examples/packages/images/snap.manifest.json
- packages/examples/packages/interactive-ui/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/consumer-signer/snap.manifest.json
- packages/examples/packages/invoke-snap/packages/core-signer/snap.manifest.json
- packages/examples/packages/json-rpc/snap.manifest.json
- packages/examples/packages/localization/snap.manifest.json
- packages/examples/packages/manage-state/snap.manifest.json
- packages/examples/packages/network-access/snap.manifest.json
- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/preinstalled/snap.manifest.json
- packages/examples/packages/rollup-plugin/snap.manifest.json
- packages/examples/packages/wasm/snap.manifest.json
- packages/examples/packages/webpack-plugin/snap.manifest.json
- tsconfig.packages.json
I thought we could target ES2022 since we use that in the extension, but doing so apparently breaks Browserify...
> Set target back to ES2020

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-rpc-methods/src/permitted/createInterface.test.tsx
- packages/snaps-sdk/src/jsx/components/form/AccountSelector.test.tsx
- packages/snaps-sdk/src/jsx/components/form/AccountSelector.ts
- packages/snaps-sdk/src/jsx/components/form/Field.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
This PR fixes the forgotten addition of the `AccountSelector` to `Box` childrens list.
It also allows the usage of `AccountSelector` in the `Field` component.
The `title` prop of the `AccountSelector` was also dropped in favor of wrapping this component inside of a `Field`.
> Add `AccountSelector` to `Box` and `Field` children

- packages/examples/packages/signature-insights/snap.manifest.json
- packages/examples/packages/signature-insights/src/index.ts
- packages/snaps-execution-environments/src/common/utils.ts
- packages/snaps-sdk/src/types/handlers/signature.ts
- packages/snaps-simulation/src/methods/constants.ts
- packages/snaps-simulation/src/structs.ts
- packages/snaps-simulator/src/features/simulation/snap-permissions.ts
`eth_sign` has been removed from all MetaMask clients, so we can remove any mention of it from Snaps as well.
Closes https://github.com/MetaMask/snaps/issues/2669
> Remove `eth_sign`

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-rpc-methods/jest.config.js
- packages/snaps-rpc-methods/src/permitted/experimentalProviderRequest.test.ts
- packages/snaps-rpc-methods/src/permitted/experimentalProviderRequest.ts
- packages/snaps-rpc-methods/src/permitted/handlers.ts
- packages/snaps-rpc-methods/src/permitted/index.ts
- packages/snaps-sdk/src/types/methods/index.ts
- packages/snaps-sdk/src/types/methods/provider-request.ts
Adds an experimental RPC method that lets Snaps make requests to networks that are not currently selected in the MetaMask UI. This is a large improvement for Snaps that want to leverage MetaMask RPC as previously the only access to RPC was given through `endowment:ethereum-provider` which strictly uses the currently selected network. This change would effectively let Snaps make requests to any networks added by the user and is a temporary stopgap solution until the MetaMask multichain API ships. **This means that this API may break at any time, use accordingly.**
Snaps with `endowment:ethereum-provider` would now be able to make requests like this:
```js
const chainId = await snap.request({
method: 'snap_experimentalProviderRequest',
params: {
chainId: 'eip155:59144',
request: { method: …
```
> feat: Add experimental provider request RPC method

- packages/snaps-rpc-methods/src/permitted/experimentalProviderRequest.ts
There are no size limits on Ethereum chain ids, so we should use BigInt to parse them.
> feat(snaps-rpc-methods): Use BigInt to parse chain ids

- packages/test-snaps/src/components/Connect.tsx
In the snaps test dapp, all the Connect buttons have a nested span inside it, that causes test flakiness when we try to click the button.
The problem is that we are trying to click the button by its id, but inside it, there is a span element which interferes with the click.
You can see this behaviour in the videos below and an example of failure [here](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/102974/workflows/b7dff65d-661f-4bb6-a8d5-d32ff34be250/jobs/3837339/tests).
This causes a lot of flakiness on any snap test that tries to click/scroll to buttons from the test dapp snap page. Any snap e2e failure that looks like this, is due to the span inside the button:
`ElementNotInteractableError: Element <button id="connectcronjobs" class="btn btn-primary" …
> fix: `span` element inside `button` causes test flakiness in extension repo e2e, interfering with the click and scroll actions

- README.md
- packages/snaps-simulation/package.json
- yarn.lock
When moving the simulation logic to `snaps-simulation`, we forgot to add `snaps-execution-environments` as a direct dependency. This causes errors at runtime when trying to install the latest version of `snaps-jest`.
`snaps-execution-environments` is an optional peer dependency of `snaps-controllers` . But is not optional for `snaps-simulation` as it leverages the Node execution environments.
> fix: Add missing dependency on execution environments to `snaps-simulation`

- .github/workflows/main.yml
- .github/workflows/re-run.yml
Some CI jobs are a bit flaky, without an obvious way for us to fix them. Instead, I've added a new job that checks if any job failed, and re-runs them automatically.
> Automatically re-run failed jobs

- .github/dependabot.yml
- package.json
- scripts/install-chrome.sh
- yarn.lock
This bumps `chromedriver` to `^129.0.2` to fix compatibility with Chrome 129.
> Bump `chromedriver` to `^129.0.2`

- .github/workflows/main.yml
- .github/workflows/re-run.yml
We have the default permissions for `GITHUB_TOKEN` set to read-only, meaning we need to explicitly grant write permission to any workflows.
> Add `actions` permission for re-run workflow

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/snaps.test.ts
- packages/snaps-utils/src/snaps.ts
This adds a `isSnapId` function which accepts any value, and returns a boolean if the input is a valid Snap ID or not.
This is extracted from #2634.
> Add `isSnapId` utility function

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/interface/SnapInterfaceController.test.tsx
- packages/snaps-controllers/src/interface/SnapInterfaceController.ts
- packages/snaps-rpc-methods/src/permitted/updateInterface.test.tsx
- packages/snaps-rpc-methods/src/permitted/updateInterface.ts
- packages/snaps-sdk/src/types/methods/update-interface.ts
Allows updating the `context` object in the `SnapInterfaceController` via `snap_updateInterface`. This is a non-breaking change as `context` is optional.
Closes https://github.com/MetaMask/snaps/issues/2804
> feat: Allow updating interface context

- packages/snaps-utils/src/index.ts
The `url.ts` file was not being exported in `snaps-utils`.
> Add url export

- packages/snaps-jest/README.md
- packages/snaps-jest/src/helpers.test.tsx
- packages/snaps-jest/src/helpers.ts
- packages/snaps-simulation/src/helpers.test.tsx
- packages/snaps-simulation/src/helpers.ts
- packages/snaps-simulation/src/structs.ts
- packages/snaps-simulation/src/types.ts
Add possibility to test `onKeyringRequest` with `snaps-jest`.
Fixes: https://github.com/MetaMask/snaps/issues/2775
Keyring test example:
```typescript
describe("onKeyringRequest", () => {
it("sends keyring request", async () => {
const { onKeyringRequest } = await installSnap();
const response = await onKeyringRequest(
{
origin: "https://metamask.github.io",
params: {
options: {
privateKey: "foo bar"
}
},
method: "keyring_createAccount"
});
expect(response).toBe({ /* Add expected result here */ });
});
});
```
> Add onKeyringRequest to snaps-jest

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/form/Input.test.tsx
- packages/snaps-sdk/src/jsx/components/form/Input.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
This PR adds the `min`, `max` and `step` props to the `Input` component of type `number`.
> Add `min`, `max` and `step` props to `Input`

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/insights/SnapInsightsController.test.ts
- packages/snaps-controllers/src/insights/SnapInsightsController.ts
Ignore Snap insight responses when a transaction/signature has already been signed/rejected. Otherwise, we are trying to set state that no longer exists.
Fixes https://github.com/MetaMask/metamask-extension/issues/27738
> fix: Ignore Snap insight response if transaction/signature has already been signed

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/Heading.ts
- packages/snaps-sdk/src/jsx/validation.ts
This adds a new `size` variant to the `Heading` component `sm`. It is the default size of the heading
> Add `sm` size variant to `Heading`

- packages/snaps-simulation/src/interface.test.tsx
- packages/snaps-simulation/src/interface.ts
In #2712 we added a `form` property to the button component, but we didn't add support to `snaps-simulation`/`snaps-jest`. In this PR I've added some logic to `snaps-simulation` to support this prop, so that forms are submitted when a button is placed outside a form with this prop.
> Add support for button `form` property in `snaps-simulation`

- packages/snaps-utils/src/url.ts
`URL` in the browser does not populate the `hostname` property, additional logic is added to handle this.
> fix: Make `parseMetaMaskUrl` platform agnostic

- packages/snaps-controllers/src/interface/SnapInterfaceController.test.tsx
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/ui.test.tsx
- packages/snaps-utils/src/ui.tsx
Following https://github.com/MetaMask/metamask-extension/pull/25839/ full URLs are required as the argument for `PhishingController:testOrigin`. This PR makes sure that our calls to `isOnPhishingList` pass strictly full URLs.
> fix: Pass URLs to `PhishingController`

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/Address.test.tsx
- packages/snaps-sdk/src/jsx/components/Address.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
Update props of address component to get it work in more flexible way.
Integration PR for `metamask-extension`: https://github.com/MetaMask/metamask-extension/pull/27798
Related ticket: https://github.com/MetaMask/snaps/issues/2758
> Add updated props for address component

- packages/snaps-sdk/src/types/methods/methods.ts
This adds the types for the `snap_getCurrencyRate` method in `snaps-sdk`. It was forgotten in #2763
> Add `snap_getCurrencyRate` to `SnapMethods`

- packages/snaps-controllers/src/services/AbstractExecutionService.test.ts
- packages/snaps-controllers/src/services/AbstractExecutionService.ts
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
- packages/snaps-execution-environments/src/common/utils.test.ts
- packages/snaps-execution-environments/src/common/utils.ts
- packages/snaps-execution-environments/src/common/validation.ts
Reduces unnecessary JSON validation when handling JSON-RPC requests to and from Snaps. For large payloads, JSON validation may be expensive, so we should attempt to reduce additional validation where inputs are already validated.
> perf: Reduce unnecessary JSON validation

- packages/snaps-utils/src/derivation-paths.ts
Add Kadena to list of known derivation paths.
Fixes https://github.com/MetaMask/MetaMask-planning/issues/3527
> chore: Add Kadena derivation path

- packages/examples/packages/ethers-js/snap.manifest.json
- packages/examples/packages/ethers-js/src/index.ts
- packages/snaps-execution-environments/lavamoat/build-system/policy.json
- yarn.lock
Updates yarn.lock to resolve the following alerts.
Rollup
https://github.com/MetaMask/snaps/security/dependabot/117
https://github.com/MetaMask/snaps/security/dependabot/116
path-to-regexp
https://github.com/MetaMask/snaps/security/dependabot/110
https://github.com/MetaMask/snaps/security/dependabot/104
body-parser
https://github.com/MetaMask/snaps/security/dependabot/106
ws (via ethers)
https://github.com/MetaMask/snaps/security/dependabot/95
vite
https://github.com/MetaMask/snaps/security/dependabot/85
> chore: Resolve Dependabot alerts

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.ts
Removes some validation checks when storing and retrieving state from `snap_manageState`. Since we have input sanitization on the Snap side, we can improve performance significantly when retrieving state by parsing it without additional validation.
Also improves performance slightly by not using `isVaultUpdated` as the sole check for caching (as that function can be somewhat expensive to call).
> perf: Stop validating JSON for stored state

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/platform-version.ts
Use regular import to reference the package.json of the SDK. This makes referencing the JSON work in the browser as well when using ESM.
> fix: Use regular import to reference package.json

- packages/snaps-utils/src/json-rpc.test.ts
- packages/snaps-utils/src/json-rpc.ts
Add line beginning to regex to prevent incorrect matches with certain types of origins.
> fix: Add line beginning to origin regex

- package.json
- packages/create-snap/package.json
- packages/snaps-browserify-plugin/package.json
- packages/snaps-cli/package.json
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/package.json
- packages/snaps-jest/package.json
- packages/snaps-rollup-plugin/package.json
- packages/snaps-rpc-methods/package.json
- packages/snaps-sdk/package.json
- packages/snaps-simulation/package.json
- packages/snaps-utils/package.json
- packages/snaps-webpack-plugin/package.json
- yarn.lock
This bumps `@ts-bridge/cli` to `0.6.0`, which brings some performance improvements.
> Bump `ts-bridge` to `0.6.0`

- packages/snaps-controllers/src/snaps/location/http.ts
Fixes a problem with fetching local Snaps on mobile. React Native does not support `blob` well, so we can use `arrayBuffer` and cache `Uint8Array` instead.
> fix: Use arrayBuffer for fetching and caching local Snaps

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/Card.test.tsx
- packages/snaps-sdk/src/jsx/components/Card.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
This PR adds support for the `Address` component as a title in the `Card` component.
> Add support for `Address` in `Card` title.

- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/common/endowments/endowments.test.browser.ts
- packages/snaps-execution-environments/src/common/endowments/network.test.ts
- packages/snaps-execution-environments/src/common/endowments/network.ts
Overwrite `[Symbol.hasInstance]` on the exposed `Response` class slightly to make `ResponseWrapper` pass `instanceof` checks. This prevents `fetch` responses from failing when using WASM bindgen for instance.
Fixes https://github.com/MetaMask/snaps/issues/2891
> fix: Make `ResponseWrapper` an instance of `Response`

- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
- packages/snaps-execution-environments/src/common/endowments/index.ts
- packages/snaps-execution-environments/src/common/test-utils/endowments.ts
- packages/snaps-execution-environments/src/common/utils.ts
Removes unnecessary proxy wrapping of provider globals to reduce complexity and overhead.
> perf: Remove unnecessary proxy for provider globals

- packages/snaps-execution-environments/src/common/endowments/commonEndowmentFactory.ts
- packages/snaps-execution-environments/src/common/endowments/endowments.test.browser.ts
- packages/snaps-simulation/src/methods/specifications.test.ts
- packages/snaps-utils/src/default-endowments.ts
Adds `isSecureContext` for the browser environments, this will continue to be undefined in the Node.js environment.
Fixes https://github.com/MetaMask/snaps/issues/2890
> fix: Add `isSecureContext` endowment

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
Fixes an oversight where preinstalled Snaps would not emit `snapInstalled` and `snapUpdated`. This would cause lifecycle hooks among other things to not work. This PR also adds a `preinstalled` flag to the events, this will be necessary to not collect metrics for installation/update of preinstalled Snaps.
Additionally, this PR fixes an oversight where preinstalled Snaps could have the manual update flow triggered. For now, we disallow this behaviour.
Progresses https://github.com/MetaMask/snaps/issues/2899
> feat: Emit `snapInstalled` and `snapUpdated` for preinstalled Snaps

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/Text.test.tsx
- packages/snaps-sdk/src/jsx/components/Text.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
This adds a new optional prop to `Text` called `size`.
It allows two values, `sm` and `md` that relates to `bodySm` and `bodyMd` in extension.
It should default to `md`.
Fixes: #2905
> Add `size` prop to `Text`

- packages/examples/packages/wasm/snap.manifest.json
- packages/snaps-cli/src/webpack/loaders/wasm.test.ts
- packages/snaps-cli/src/webpack/loaders/wasm.ts
This PR changes the WASM loader slightly to package the WASM source code using Base64 and decode it at runtime. This has multiple effects:
- Fixes an obscure OOM bug in Firefox that would only occur on Mac OS (possibly due to extremely large arrays?)
- Reduces bundle size for Snaps that leverage WASM
- Prevents bundler slowdown due to large arrays needing to be parsed by Babel
This adds minor overhead to initializing WASM bundles, but this seems worth it given the effects above.
> fix: Init WASM modules using Base64

- packages/examples/packages/notifications/snap.manifest.json
- packages/examples/packages/notifications/src/index.test.ts
- packages/examples/packages/notifications/src/index.ts
Adds an inline link to the notification example, this is helpful for testing purposes.
Progresses https://github.com/MetaMask/snaps/issues/2914
> chore: Add link to notification example

- package.json
- packages/create-snap/package.json
- packages/snaps-browserify-plugin/package.json
- packages/snaps-cli/package.json
- packages/snaps-controllers/package.json
- packages/snaps-execution-environments/package.json
- packages/snaps-jest/package.json
- packages/snaps-rollup-plugin/package.json
- packages/snaps-rpc-methods/package.json
- packages/snaps-sdk/package.json
- packages/snaps-simulation/package.json
- packages/snaps-utils/package.json
- packages/snaps-webpack-plugin/package.json
- yarn.lock
Bumps `ts-bridge` to the latest version, fixing some issues with processing CJS exports: https://github.com/ts-bridge/ts-bridge/commit/ce3394692cc7236d3baacbbb8b334a3ee20dc500
> chore: Bump ts-bridge

- packages/snaps-sdk/src/jsx/components/Icon.ts
- packages/snaps-sdk/src/ui/components/input.ts
Rename the main `metamask-extension` branch in comments where it is referenced. It was recently renamed from `develop` to `main`.
> chore: Update comments referencing extension main branch

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-controllers/src/interface/utils.test.tsx
- packages/snaps-rpc-methods/src/permitted/createInterface.test.tsx
- packages/snaps-sdk/src/jsx/components/form/Field.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
- packages/snaps-simulator/src/features/builder/utils.test.ts
This PR allows the usage of `Field` in `Box` to be able to put two field in a row.
> Allow `Field` in `Box`

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-rpc-methods/src/permitted/createInterface.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
Improves validation errors for `Field` by rewriting the struct using `selectiveUnion`.
Fixes https://github.com/MetaMask/snaps/issues/2927
> fix: Improve field validation errors

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/form/Button.test.tsx
- packages/snaps-sdk/src/jsx/components/form/Button.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
Add `size` prop to buttons, letting devs size them similarly to `Text`. 
Progresses https://github.com/MetaMask/snaps/issues/2947
> feat: Add `size` prop to Button

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/Text.test.tsx
- packages/snaps-sdk/src/jsx/components/Text.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
Add support for specifying the `fontWeight` prop on the `Text` component.
> feat: Support `fontWeight` prop on `Text`

- packages/snaps-jest/src/helpers.test.tsx
- packages/snaps-simulation/package.json
- packages/snaps-simulation/src/controllers.ts
- packages/snaps-simulation/src/helpers.test.tsx
- packages/snaps-simulation/src/interface.test.tsx
- packages/snaps-simulation/src/interface.ts
- packages/snaps-simulation/src/request.test.tsx
- packages/snaps-simulation/src/types.ts
- yarn.lock
Adds `waitForUpdate` as an interface action, which lets developers wait for the Snap content to be updated by the Snap. This is useful when waiting for the Snap to populate the UI with information gathered asynchronously.
Fixes https://github.com/MetaMask/snaps/issues/2958
> feat: Add `waitForUpdate` interface action

- packages/examples/packages/manage-state/src/index.test.ts
- packages/snaps-simulation/src/controllers.test.ts
- packages/snaps-simulation/src/controllers.ts
- packages/snaps-simulation/src/methods/hooks/index.ts
- packages/snaps-simulation/src/methods/hooks/permitted/index.ts
- packages/snaps-simulation/src/methods/hooks/permitted/state.test.ts
- packages/snaps-simulation/src/methods/hooks/permitted/state.ts
- packages/snaps-simulation/src/methods/specifications.test.ts
- packages/snaps-simulation/src/methods/specifications.ts
- packages/snaps-simulation/src/middleware/engine.test.ts
- packages/snaps-simulation/src/middleware/engine.ts
- packages/snaps-simulation/src/simulation.test.ts
- packages/snaps-simulation/src/simulation.ts
This adds support for the state methods introduced in #2916 to `snaps-simulation` (and `snaps-jest`), and updates the example to test these methods as well.
- The middleware hooks in `snaps-simulation` were separated into two separate types, `PermittedMiddlewareHooks` and `RestrictedMiddlewareHooks`.
- The `MiddlewareHooks` type was removed.
> BREAKING: Add support for new state methods to `snaps-simulation`

- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/test-utils/execution-environment.ts
- packages/snaps-controllers/src/test-utils/service.ts
- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
- packages/snaps-execution-environments/src/common/SnapProvider.ts
- packages/snaps-execution-environments/src/common/test-utils/executor.ts
- packages/snaps-execution-environments/src/iframe/IFrameSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/node-process/ChildProcessSnapExecutor.test.ts
- packages/snaps-execution-environments/src/node-thread/ThreadSnapExecutor.test.ts
- packages/snaps-execution-environments/src/webworker/executor/WebWorkerSnapExecutor.test.browser.ts
Since we only expose the `request` function from the provider and don't allow listening to events or using `provider.chainId` etc we can initialize the provider without making the `metamask_getProviderState` request. This saves us a potential network request that may add overhead to booting the Snap. Specifically the clients call `net_version` since this property is required in the `MetaMaskInpageProvider`.
Closes https://github.com/MetaMask/snaps/issues/2968
> fix: Skip unnecesary provider initialization

- packages/snaps-cli/src/webpack/__snapshots__/config.test.ts.snap
- packages/snaps-cli/src/webpack/config.ts
Disable the `nodeEnv` optimization in the default Webpack config, this optimization would simply add the `NODE_ENV` environment variable set to `production`, but that is unnecessary since we are already defining `NODE_ENV` ourselves.
This prevents an issue where devs would run into warnings when attempting to set `NODE_ENV` themselves.
> fix: Disable `nodeEnv` optimization in Webpack

- packages/examples/packages/ethereum-provider/README.md
- packages/examples/packages/ethereum-provider/snap.manifest.json
- packages/examples/packages/ethereum-provider/src/index.test.ts
- packages/examples/packages/ethereum-provider/src/index.ts
- packages/examples/packages/ethereum-provider/src/types.ts
- packages/snaps-execution-environments/src/common/utils.ts
- packages/test-snaps/src/features/snaps/ethereum-provider/EthereumProvider.tsx
- packages/test-snaps/src/features/snaps/ethereum-provider/components/SignTypedData.tsx
- packages/test-snaps/src/features/snaps/ethereum-provider/components/index.ts
Unblock all variants of `eth_signTypedData` as they are deemed lower risk following UI changes on the clients.
Also adds logic to use it in the Ethereum provider example Snap.
> feat: Unblock `eth_signTypedData`

- packages/snaps-rpc-methods/src/restricted/getPreferences.test.ts
- packages/snaps-sdk/src/types/methods/get-preferences.ts
- packages/snaps-simulation/src/methods/hooks/get-preferences.test.ts
- packages/snaps-simulation/src/methods/hooks/get-preferences.ts
- packages/snaps-simulation/src/options.test.ts
- packages/snaps-simulation/src/options.ts
- packages/snaps-simulation/src/test-utils/options.ts
- packages/snaps-simulator/src/features/simulation/sagas.ts
This adds a new property to the `snap_getPreferences` return value called `hideBalances` which binds to the property existing in the preference controller called `privacyMode`.
Fixes: #2977
> feat: Add `hideBalances` to `snap_getPreferences`

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/Value.test.tsx
- packages/snaps-sdk/src/jsx/components/Value.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
This allows the usage of `Text` in the `Value` component props `value` and `extra`.
> feat: Allow usage of `Text` in `Value` props

- package.json
- scripts/install-chrome.sh
- yarn.lock
This bumps `chromedriver` to `^131.0.5` and updates CI to use the latest version of Chrome.
> Bump Chromedriver to `^131.0.5`

- package.json
- scripts/install-chrome.sh
- scripts/update-chrome.sh
I've created a script to simplify bumping Chrome and `chromedriver` a little bit. With the script you can just run `yarn update-chrome`, which fetches the latest version of `chromedriver`, and updates the version and shasum in the `install-chrome` script.
Ideally we can run this automatically on Dependabot PRs, but Dependabot seems to be broken right now.
> Add script to update Chrome version

- package.json
Rather than running `yarn dedupe --check` in the pre-commit hook we now run `yarn dedupe` whenever `yarn.lock` has changed. This means we no longer need to run `yarn dedupe` manually after adding or updating dependencies, and also fixes an issue in Dependabot.
> Update `lint-staged` config

- .github/workflows/main.yml
Seems like GitHub is struggling with all the Dependabot PRs right now, so we should at least temporarily disable rerunning failed workflows for Dependabot.
> Don't rerun workflows for Dependabot

- packages/snaps-sdk/src/types/permissions.ts
- packages/snaps-utils/src/manifest/validation.ts
Make the `jobs` property fully optional in the cronjob endowment since it is also allowed to be empty.
We accounted for and discussed this in #2941, but must have forgotten to allow `endowment:cronjob: {}`.
> fix: Make `jobs` property fully optional in the cronjob endowment

- packages/snaps-controllers/src/cronjob/CronjobController.ts
For unknown reasons we were storing our own instance of the messenger in the `CronjobController`, we don't need to do that since the `BaseController` provides this functionality already.
> fix: Stop storing messenger manually in `CronjobController`

- packages/examples/packages/ethereum-provider/snap.manifest.json
- packages/examples/packages/ethereum-provider/src/index.ts
When writing the signTypedData example I had based the code on some example code that hardcoded the chain ID. Instead we should use the current chain ID, so we can test the Snap on any chain.
> fix: Use proper chain ID for `signTypedData` example

- packages/examples/packages/ethereum-provider/src/index.test.ts
- packages/snaps-simulation/src/middleware/internal-methods/chain-id.test.ts
- packages/snaps-simulation/src/middleware/internal-methods/chain-id.ts
- packages/snaps-simulation/src/middleware/internal-methods/middleware.ts
- packages/snaps-simulation/src/middleware/internal-methods/net-version.test.ts
- packages/snaps-simulation/src/middleware/internal-methods/net-version.ts
Mock calls to `eth_chainId` and `net_version` in the simulation framework, so users don't have to mock them manually.
This should also prevent some flakiness in our tests.
> feat: Mock chain ID and network version calls in simulation

- packages/test-snaps/src/features/snaps/state/State.tsx
- packages/test-snaps/src/features/snaps/state/components/SetState.tsx
Some HTML IDs were duplicated between the state and manage state sections on `test-snaps`, and there was a missing button as well. I've fixed both issues in this PR.
> Update state section on `test-snaps`

- packages/examples/packages/notifications/src/index.tsx
- packages/test-snaps/src/features/snaps/notifications/Notifications.tsx
The wrong method was being triggered in `test-snaps`. Fixed the typo.
> Fix typo in `test-snaps`

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/Image.test.tsx
- packages/snaps-sdk/src/jsx/components/Image.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
Add a border radius prop to `Image`.
Progresses https://github.com/MetaMask/metamask-extension/issues/29668
> feat: Add border radius to `Image`

- packages/snaps-rpc-methods/jest.config.js
- packages/snaps-rpc-methods/src/permitted/setState.test.ts
- packages/snaps-rpc-methods/src/permitted/setState.ts
- packages/snaps-rpc-methods/src/restricted/manageState.test.ts
- packages/snaps-rpc-methods/src/restricted/manageState.ts
This PR contains a couple changes related to JSON size validation in the `snap_manageState` and `snap_setState` methods:
- The maximum size was reduced from 100 MB to 64 MB. This is to because `window.postMessage` breaks when sending payloads that are too large. This is technically a breaking change, but I'm not sure if it should be considered as one, given that the execution environment would throw regardless, if the new state is too big?
- `snap_setState` now properly validates the size of the new state, like `snap_manageState` does.
> Improve state size validation

- packages/snaps-execution-environments/src/common/endowments/commonEndowmentFactory.ts
- packages/snaps-execution-environments/src/common/endowments/endowments.test.browser.ts
- packages/snaps-simulation/src/methods/specifications.test.ts
- packages/snaps-utils/src/default-endowments.ts
Add `Intl` as a default endowment to allow Snaps to use the browser native functionality for formatting text and numbers in the UI.
Closes #3034
> feat: Add `Intl` as a default endowment

- packages/snaps-sdk/src/jsx/components/Avatar.ts
The jsdoc for Avatar JSX component was missing a prop
> Add prop for Avatar inside jsdoc

- packages/snaps-execution-environments/src/common/endowments/commonEndowmentFactory.ts
- packages/snaps-execution-environments/src/common/endowments/endowments.test.browser.ts
- packages/snaps-simulation/src/methods/specifications.test.ts
- packages/snaps-utils/src/default-endowments.ts
Add `URLSearchParams` as a default global to allow for easy modification of query strings for API calls. This was already somewhat available through `URL.searchParams`.
Closes https://github.com/MetaMask/snaps/issues/3044
> feat: Add `URLSearchParams` as a default endowment

- packages/snaps-controllers/src/snaps/SnapController.ts
`SnapController`'s name was set to `string` rather than `"SnapController"`, which causes some problems with type inference in MetaMask/metamask-extension#30034.
> Set name for `SnapController`

- packages/snaps-controllers/src/snaps/SnapController.ts
For some reason the controller name was defined twice. This removes one of the instances.
> chore: Remove duplicate controller name

- docs/internals/permissions.md
- packages/snaps-controllers/src/cronjob/CronjobController.ts
- packages/snaps-controllers/src/insights/SnapInsightsController.ts
- packages/snaps-controllers/src/interface/SnapInterfaceController.ts
- packages/snaps-controllers/src/multichain/MultichainRouter.ts
- packages/snaps-controllers/src/services/ExecutionService.ts
- packages/snaps-controllers/src/services/node-js/NodeProcessExecutionService.test.ts
- packages/snaps-controllers/src/services/node-js/NodeThreadExecutionService.test.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/registry/json.ts
- packages/snaps-controllers/src/test-utils/controller.ts
- packages/snaps-controllers/src/test-utils/service.ts
- packages/snaps-simulation/src/controllers.test.ts
- packages/snaps-simulation/src/controllers.ts
- packages/snaps-simulation/src/methods/specifications.test.ts
- packages/snaps-simulation/src/simulation.ts
- packages/snaps-simulator/jest.config.js
- packages/snaps-simulator/src/features/simulation/sagas.ts
- packages/snaps-simulator/src/features/simulation/test/controllers.ts
- packages/snaps-utils/src/test-utils/controller.ts
Rename `RestrictedControllerMessenger` to `RestrictedMessenger` and `ControllerMessenger` to `Messenger`.
Relates to [#4538](https://github.com/MetaMask/core/issues/4538)
No functional changes.
> chore: Rename `ControllerMessenger` to `Messenger`

- .github/workflows/main.yml
- .github/workflows/update-pull-request.yml
This updates the "update PR" workflow to trigger for Dependabot PRs automatically.
> Automatically update Dependabot pull requests

- .github/workflows/main.yml
- .github/workflows/update-pull-request.yml
`github.event` doesn't propagate to called workflows, so `github.event.issue.number` would not be set. This attempts to fix it by providing the PR number from the main workflow.
> Update Dependabot update workflow

- .github/workflows/main.yml
- .github/workflows/update-pull-request.yml
This fixes a couple minor issues with the Dependabot update workflow:
- The update won't be retriggered anymore after MetaMask bot pushes the new commits.
- I've updated the commit message so it doesn't include the quotes. Turns out those were unnecessary.
> Fix minor issue with Dependabot update workflow

- .github/workflows/main.yml
- .github/workflows/security-code-scanner.yml
This updates the code scanner workflow to run from the main workflow, instead of a separate workflow.
> Run code scanner from main workflow

- packages/snaps-cli/package.json
- packages/snaps-cli/src/builders.ts
- packages/snaps-cli/src/commands/build/build.test.ts
- packages/snaps-cli/src/commands/build/build.ts
- packages/snaps-cli/src/commands/build/implementation.ts
- packages/snaps-cli/src/commands/build/index.test.ts
- packages/snaps-cli/src/commands/build/index.ts
- packages/snaps-cli/src/commands/build/utils.test.ts
- packages/snaps-cli/src/commands/build/utils.ts
- packages/snaps-cli/src/types/webpack-bundle-analyzer.d.ts
- packages/snaps-cli/src/types/yargs.d.ts
- packages/snaps-cli/src/utils/logging.test.ts
- packages/snaps-cli/src/utils/logging.ts
- packages/snaps-cli/src/utils/steps.test.ts
- packages/snaps-cli/src/utils/steps.ts
- packages/snaps-cli/src/webpack/__snapshots__/config.test.ts.snap
- packages/snaps-cli/src/webpack/config.test.ts
- packages/snaps-cli/src/webpack/config.ts
- yarn.lock
This adds `mm-snap build --analyze` to enable the bundle analyser. It uses `webpack-bundle-analyser` under the hood.
> Add `--analyze` flag to enable bundle analyzer to CLI

- packages/snaps-controllers/src/services/webview/WebViewMessageStream.test.ts
- packages/snaps-controllers/src/services/webview/WebViewMessageStream.ts
- packages/snaps-controllers/src/test-utils/webview.ts
- packages/snaps-execution-environments/src/webview/WebViewExecutorStream.test.ts
- packages/snaps-execution-environments/src/webview/WebViewExecutorStream.ts
Base64 encoding/decoding seems to be a significant overhead for the boot message on mobile. Encoding the messages as bytes instead have proven to be more performant, but still has overhead.
> perf: Encode messages in mobile as byte arrays

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/multichain/MultichainRouter.ts
Recreate the JSON-RPC request in MultichainRouter to remove any unnecesary properties passed in from the middlewares in the client. This ensures that we don't leak unnecessary details to Snaps and also makes sure the requests are formatted as expected downstream.
> fix: Recreate JSON-RPC request in MultichainRouter

- .github/workflows/update-pull-request.yml
`update-chrome` was missing `actions/checkout`, causing the workflow to fail.
> Add missing checkout step to `update-chrome` workflow

- scripts/update-chrome.sh
The `update-chrome` script was only compatible with macOS. Since we now run it as part of Dependabot, I've updated it to be compatible with Linux.
> Fix Linux support for `update-chrome` script

- packages/snaps-execution-environments/lavamoat/build-system/policy.json
This updates the LavaMoat build policy, following the dependency changes in #3096.
> Update LavaMoat policy

- packages/snaps-simulation/src/helpers.ts
Fixes an unnecessarily narrow type for `onKeyringRequest` that makes it seem like the request cannot produce interfaces.
> fix(simulation): Unintentionally narrow type for `onKeyringRequest` helper

- packages/snaps-controllers/src/services/AbstractExecutionService.test.ts
- packages/snaps-controllers/src/services/iframe/IframeExecutionService.ts
- packages/snaps-controllers/src/services/offscreen/OffscreenExecutionService.ts
- packages/snaps-controllers/src/services/proxy/ProxyExecutionService.ts
- packages/snaps-controllers/src/services/webview/WebViewExecutionService.ts
- packages/snaps-controllers/src/services/webworker/WebWorkerExecutionService.ts
Properly pass down constructor arguments passed into execution services. This allows proper overriding of the `initTimeout` for instance.
> fix(controllers): Properly pass down execution service constructor args

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/components/Box.test.tsx
- packages/snaps-sdk/src/jsx/components/Box.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
This PR adds a new prop to `Box` called `crossAlignment` which should bind to `align-items`.
Fixes: #3114
> feat: Add `crossAlignment` to `Box`

- packages/examples/package.json
The build script for examples broke in #3094. Using the `filter` command seems to be the easiest way to get it working again.
> Fix example build script

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/services/webview/WebViewExecutionService.test.ts
- packages/snaps-controllers/src/services/webview/WebViewExecutionService.ts
- packages/snaps-controllers/src/services/webview/WebViewMessageStream.ts
- packages/snaps-controllers/src/test-utils/webview.ts
- packages/snaps-execution-environments/lavamoat/browserify/webview/policy.json
- packages/snaps-execution-environments/src/webview/index.ts
Allows us to run Snaps locally on mobile by instantiating a WebView per Snap. This PR changes the `WebViewExecutionService` to let it instantiate and remove webviews (this will need support on the mobile implementation side). Additionally alters the WebView bundle so it no longer functions as a "proxy executor", but instead inherits from the iframe executor implementation. 
**Breaking changes**
- `WebViewExecutionService` now requires `createWebView` and `removeWebView` constructor arguments, `getWebView` is no longer supported.
- The WebView bundle in `snaps-execution-environments` no longer supports proxy executor calls and functions as a single executor.
> feat!: Run a WebView per Snap on mobile

- eslint.config.mjs
- packages/examples/packages/invoke-snap/packages/core-signer/src/utils.ts
- packages/snaps-browserify-plugin/src/plugin.ts
- packages/snaps-cli/jest.setup.ts
- packages/snaps-cli/src/__mocks__/fs.ts
- packages/snaps-cli/src/cli.ts
- packages/snaps-cli/src/main.ts
- packages/snaps-cli/src/utils/steps.ts
- packages/snaps-cli/src/webpack/loaders/function.ts
- packages/snaps-controllers/src/snaps/location/local.ts
- packages/snaps-controllers/src/snaps/location/npm.test.ts
- packages/snaps-controllers/src/snaps/location/npm.ts
- packages/snaps-execution-environments/src/common/globalObject.ts
- packages/snaps-execution-environments/src/webview/WebViewExecutorStream.test.ts
- packages/snaps-simulator/src/features/handlers/transactions/components/TransactionPrefill.test.tsx
- packages/snaps-simulator/src/utils/environment.ts
- packages/test-snaps/src/utils/id.ts
This updates the ESLint configuration to fix errors related to Node.js and browser globals, and disables some rules that were too strict.
> Fix remaining Node.js, browser, globals errors

- packages/examples/packages/network-access/src/index.test.ts
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/location/http.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/webworker/executor/WebWorkerSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/webworker/pool/WebWorkerPool.test.browser.ts
This fixes lint violations for the following rules:
- jest/no-disabled-tests
- jest/prefer-to-be
- jest/prefer-to-have-length
> Fix Jest-related errors

- packages/snaps-controllers/src/cronjob/CronjobController.ts
- packages/snaps-controllers/src/services/AbstractExecutionService.ts
- packages/snaps-controllers/src/services/webview/WebViewMessageStream.ts
- packages/snaps-controllers/src/services/webworker/WebWorkerExecutionService.ts
- packages/snaps-controllers/src/snaps/RequestQueue.ts
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/Timer.ts
- packages/snaps-controllers/src/snaps/location/http.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
- packages/snaps-execution-environments/src/webview/WebViewExecutorStream.ts
- yarn.config.cjs
This fixes lint violations caused by the `no-restricted-syntax` rule by suppressing these errors. We need to do additional research whether these can be fixed, as some may be used by tests.
> Fix `no-restricted-syntax` errors

- packages/snaps-sdk/src/jsx/components/Box.ts
This PR updates the JSDoc for `Box` `crossAlignment` prop to omit default value
> fix: Update `Box` `crossAlignment` default value

- packages/snaps-simulation/src/types.ts
In https://github.com/MetaMask/snaps/commit/3556c3cc8fb5c65a0c0cc53f226b8483de5cd7cc I change the type of `onKeyringRequest` but apparently it is defined in more places and I forgot to change it here.
> fix(simulation): `onKeyringRequest` not matching the implementation type

- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/snaps.test.ts
- packages/snaps-utils/src/snaps.ts
- packages/snaps-utils/src/types.ts
`@metamask/utils` introduced a new `definePattern` superstruct helper to have better error messages for `pattern`. This updates the repo to use it.
Fixes: #3066
> chore: Remove `pattern` in favour of `definePattern`

- .yarn/plugins/local/plugin-workspaces-filter.js
- packages/examples/package.json
- packages/test-snaps/package.json
`yarn start` in the `test-snaps` folder was broken after #3094. This fixes it.
> Fix start command in `test-snaps`

- packages/examples/README.md
- packages/examples/packages/preferences/.depcheckrc.json
- packages/examples/packages/preferences/CHANGELOG.md
- packages/examples/packages/preferences/LICENSE.APACHE2
- packages/examples/packages/preferences/LICENSE.MIT0
- packages/examples/packages/preferences/README.md
- packages/examples/packages/preferences/jest.config.js
- packages/examples/packages/preferences/package.json
- packages/examples/packages/preferences/snap.config.ts
- packages/examples/packages/preferences/snap.manifest.json
- packages/examples/packages/preferences/src/index.test.ts
- packages/examples/packages/preferences/src/index.ts
- packages/examples/packages/preferences/tsconfig.json
- packages/test-snaps/package.json
- packages/test-snaps/src/features/snaps/index.ts
- packages/test-snaps/src/features/snaps/preferences/Preferences.tsx
- packages/test-snaps/src/features/snaps/preferences/constants.ts
- packages/test-snaps/src/features/snaps/preferences/index.ts
- yarn.lock
Adds the `preferences-example-snap` to `examples` and `test-snaps`.
Fixes: #3153
> feat: Add the preferences example snap

- packages/snaps-controllers/src/snaps/SnapController.ts
Log unhandled Snap errors for easier debugging when a Snap is crashing. This lets developers dig up the actual reason for their Snap being terminated in the logs.
> fix: Log unhandled Snap errors

- .github/workflows/main.yml
This adds `merge_group` to the main workflow, enabling us to use the merge queue functionality.
> Add `merge_group` trigger to main workflow

- packages/test-snaps/src/features/snaps/bip32/BIP32.tsx
- packages/test-snaps/src/features/snaps/bip44/BIP44.tsx
- packages/test-snaps/src/features/snaps/bip44/components/SignMessage.tsx
- packages/test-snaps/src/features/snaps/get-entropy/GetEntropy.tsx
- packages/test-snaps/src/features/snaps/get-entropy/components/EntropySelector.tsx
- packages/test-snaps/src/features/snaps/get-entropy/hooks/useEntropySelector.tsx
I've made some minor changes to `test-snaps` related to the SIP-30 entropy selector.
- Each selector now has a unique ID. Previously the same ID was shared by multiple components, which is semantically incorrect HTML, and also makes it more difficult to E2E test.
- I've added an "invalid" option to the selector, to test that we properly throw errors for entropy sources that don't exist.
> Add ID to entropy selector and invalid option for E2E testing

- packages/snaps-jest/src/helpers.test.tsx
- packages/snaps-simulation/src/helpers.test.tsx
- packages/snaps-simulation/src/interface.test.tsx
- packages/snaps-simulation/src/interface.ts
- packages/snaps-simulation/src/request.test.tsx
- packages/snaps-simulation/src/types.ts
This adds the interface ID in the return value of `snap-jest` `getInterface`.
> Add the interface ID to the return value of `getInterface`

- packages/test-snaps/src/features/snaps/updates/constants.ts
Bumping the BIP-32 example in #3185 caused issues in the MetaMask extension E2E tests. We don't update the Webpack plugin example so often, and it's not on the `test-snaps` page directly, so less likely to cause issues in the future.
> Use Webpack plugin example Snap for testing updates

- packages/snaps-rpc-methods/src/permitted/listEntropySources.test.ts
- packages/snaps-rpc-methods/src/permitted/listEntropySources.ts
`snap_listEntropySources` was missing a call to `getUnlockPromise`, so if the client is locked, it would just return an empty array.
> Unlock client before calling `getEntropySources` in `snap_listEntropySources` method

- packages/snaps-jest/package.json
- packages/snaps-simulation/package.json
- packages/snaps-simulator/package.json
- yarn.lock
Addresses https://github.com/MetaMask/snaps/security/dependabot/133, https://github.com/MetaMask/snaps/security/dependabot/125 & https://github.com/MetaMask/snaps/security/dependabot/120
> chore: Bump dependencies for Dependabot alerts

- .github/dependabot.yml
This enables grouping of Dependabot PRs for minor and patch updates to `@metamask/*` dependencies. Major dependencies are still done separately, as they may require more action.
> Group Dependabot minor and patch updates for MetaMask dependencies

- .github/workflows/update-pull-request.yml
`update-chrome` is a requirement for `commit-result`, but it turns out that if `update-chrome` is skipped, so is `commit-result`.  Adding the if condition makes the job always run (assuming it didn't fail or didn't get cancelled).
> Always run commit step in update PR workflow

- .github/workflows/build-lint-test.yml
- .github/workflows/main.yml
- .github/workflows/publish-environment.yml
- .github/workflows/publish-github-pages.yml
- .github/workflows/publish-preview.yml
- .github/workflows/publish-release.yml
- .github/workflows/security-code-scanner.yml
- .github/workflows/update-pull-request.yml
This updates all workflows to use `MetaMask/action-checkout-and-setup` and remove the use of `actions/cache`.
> Update workflows to use `MetaMask/action-checkout-and-setup`

- packages/snaps-rpc-methods/jest.config.js
- packages/snaps-rpc-methods/src/restricted/getBip32Entropy.test.ts
- packages/snaps-rpc-methods/src/restricted/getBip32Entropy.ts
- packages/snaps-rpc-methods/src/restricted/getBip32PublicKey.test.ts
- packages/snaps-rpc-methods/src/restricted/getBip32PublicKey.ts
- packages/snaps-rpc-methods/src/restricted/getBip44Entropy.test.ts
- packages/snaps-rpc-methods/src/restricted/getBip44Entropy.ts
- packages/snaps-rpc-methods/src/restricted/getEntropy.test.ts
- packages/snaps-rpc-methods/src/restricted/getEntropy.ts
- packages/snaps-rpc-methods/src/utils.test.ts
- packages/snaps-rpc-methods/src/utils.ts
- packages/snaps-simulation/src/methods/hooks/get-mnemonic-seed.test.ts
- packages/snaps-simulation/src/methods/hooks/get-mnemonic-seed.ts
- packages/snaps-simulation/src/simulation.ts
- packages/snaps-simulator/jest.config.js
- packages/snaps-simulator/src/features/simulation/sagas.ts
This PR adjusts the implementations of the entropy RPC methods to use `getMnemonicSeed` if the curve being used is either `secp256k1` or `ed25519`. This let's us skip the most computationally heavy part of the key derivation by re-using the already derived BIP-39 seed.
Closes #3219 
**Breaking changes**
- A `getMnemonicSeed` hook is now required to support all entropy RPC methods.
- Note that `getMnemonic` can not be removed as that is still also in use.
> perf!: Use mnemonic seed for entropy RPC methods

- .github/dependabot.yml
This reverts commit ba54f3772191dce9183b7ac512f598aea1abb76e.
> Revert "Group Dependabot minor and patch updates for MetaMask dependencies (#3207)"

- .github/workflows/main.yml
If a workflow fails in the merge queue, it's removed from the queue right away. Rerunning jobs like this doesn't work unfortunately.
> Skip rerunning workflows in merge queue

- packages/snaps-controllers/src/multichain/MultichainRouter.ts
- packages/snaps-controllers/src/test-utils/multichain.ts
`KeyringController.withKeyring` had a breaking change in https://github.com/MetaMask/core/commit/8e15f01af8b6e10b68177ade5a687bcac29b29b9 where the format of the callback parameters was changed. This breaks the SIP-26 branch as the extension is already using the latest version of the `KeyringController`. This PR adjusts our usage of `withKeyring` to expect the new format.
> fix: Handle `withKeyring` breaking change in `MultichainRouter`

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/interface/utils.test.tsx
- packages/snaps-controllers/src/interface/utils.ts
- packages/snaps-rpc-methods/src/permitted/createInterface.test.tsx
- packages/snaps-sdk/src/internals/jsx.ts
- packages/snaps-sdk/src/jsx/components/form/AddressInput.test.tsx
- packages/snaps-sdk/src/jsx/components/form/AddressInput.ts
- packages/snaps-sdk/src/jsx/components/form/Field.test.tsx
- packages/snaps-sdk/src/jsx/components/form/Field.ts
- packages/snaps-sdk/src/jsx/components/form/index.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
- packages/snaps-sdk/src/types/interface.ts
Closes #2812 
This adds an `AddressInput` component that takes a CAIP-2 `chainId` to identify the chain the address needs resolution on and resolves to a display name and avatar (if it exists). The resolution is to be made against the user's own saved accounts.
> Add `AddressInput` component

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/interface/utils.test.tsx
- packages/snaps-controllers/src/interface/utils.ts
This PR refactors `constructState` to use an util function called `isStatefulComponent` that uses an array of component types that includes all the stateful components.
Fixes: #3235
> chore: Refactor stateful component check in `constructState`

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.ts
This wraps `getSnapState` in a mutex, to ensure we only decrypt once when calling it at the same time. The first call will decrypt the state and cache it in the Snaps runtime, and the next call will just use the cached result.
> Add mutex to `getSnapState` to prevent concurrent decryption

- .github/workflows/main.yml
CI should not be able to pass if the analyse code step is failing.
> Make CI depend on `analyse-code` step

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/examples/packages/send-flow/package.json
- packages/examples/packages/send-flow/snap.manifest.json
- packages/examples/packages/send-flow/src/components/SendFlow.tsx
- packages/examples/packages/send-flow/src/components/SendForm.tsx
- packages/examples/packages/send-flow/src/index.tsx
- packages/snaps-sdk/src/jsx/components/form/AddressInput.ts
- packages/snaps-sdk/src/jsx/validation.test.tsx
- packages/snaps-sdk/src/jsx/validation.ts
- yarn.lock
The `displayAvatar` prop is being added to the `AddressInput` component to allow a snap to indicate that it has validated the value of the component itself. Updated the send flow example snap as well, removed dead code that was missed previously.
> Add `displayAvatar` prop to `AddressInput` component

- packages/examples/packages/send-flow/snap.manifest.json
- packages/examples/packages/send-flow/src/index.tsx
Previous PR failed to parse the event value as it is a `CaipAccountId`, updated the implementation to parse the value before checking against the struct.
> Fix send flow snap

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-sdk/src/jsx/validation.ts
Improve error messages when validating `AddressStruct` by using `selectiveUnion`. This may also improve performance when validating JSX blobs.
> fix: Improve error messages for `AddressStruct`

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/interface/SnapInterfaceController.test.tsx
- packages/snaps-controllers/src/interface/SnapInterfaceController.ts
- packages/snaps-controllers/src/test-utils/controller.ts
- packages/snaps-jest/src/test-utils/controller.ts
- packages/snaps-simulation/src/controllers.ts
- packages/snaps-simulation/src/request.test.tsx
- packages/snaps-simulation/src/simulation.test.ts
- packages/snaps-simulation/src/simulation.ts
- packages/snaps-simulation/src/test-utils/controller.ts
- packages/snaps-simulator/jest.config.js
- packages/snaps-simulator/src/features/simulation/sagas.ts
- packages/snaps-simulator/src/features/simulation/test/controllers.ts
Before this PR we would sometimes (every 5 minutes or so) update the phishing list before validating interfaces. When the phishing list is out of date it takes multiple seconds for this call to resolve causing an unacceptable experience.
From now on, we will assume that the phishing list is kept up to date by other controllers (or the user visiting dapps for instance).
> fix: Stop refreshing phishing list when updating interfaces

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/cronjob/CronjobController.test.ts
- packages/snaps-controllers/src/cronjob/CronjobController.ts
- packages/snaps-controllers/src/insights/SnapInsightsController.test.ts
- packages/snaps-controllers/src/insights/SnapInsightsController.ts
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-simulation/src/interface.test.tsx
- packages/snaps-simulation/src/interface.ts
- packages/snaps-simulation/src/request.test.tsx
- packages/snaps-simulator/src/contexts/SnapInterface.tsx
- packages/snaps-simulator/src/features/handlers/cronjobs/slice.ts
- packages/snaps-simulator/src/features/handlers/json-rpc/slice.ts
- packages/snaps-simulator/src/features/handlers/transactions/components/Request.tsx
We were using empty origins in a lot of places instead of specifying `metamask` for internal requests. This PR disallows doing that so we can be clear about where requests are coming from. `origin` must now be either a valid URL or `metamask`.
> fix: Validate origin in `handleRequest`

- packages/examples/packages/interactive-ui/snap.manifest.json
- packages/examples/packages/interactive-ui/src/components/InteractiveForm.tsx
- packages/examples/packages/interactive-ui/src/components/Result.tsx
- packages/examples/packages/interactive-ui/src/index.test.tsx
- packages/examples/packages/interactive-ui/src/index.tsx
- packages/test-snaps/src/features/snaps/interactive-ui/InteractiveUI.tsx
Makes a couple of improvements to the interactive UI example Snap:
- Use custom dialog type with footers instead of regular buttons
- Add a `disabled` parameter which disables all of the components for testing and visual inspection
- Remove broken "Get interface state" button
> feat: Add disabled state to interactive UI example

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/multichain/MultichainRouter.test.ts
- packages/snaps-controllers/src/multichain/MultichainRouter.ts
As per request from the wallet API team and after discussion with them we want to consider protocol Snaps when determining the return value of `isSupportedScope`. Previously we assumed that a scope was not serviceable if no accounts existed, but that isn't entirely accurate enough.
> fix: Consider protocol Snaps when determining `isSupportedScope`

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/test-utils/controller.ts
Inject `context` into `onUserInput` requests, this reduces complexity on the client-side where the UI system no longer has to keep `context` up to date. Also fixes a problem where we weren't keeping the context properly up to date.
Fixes https://github.com/MetaMask/snaps/issues/3069
> fix: Inject `context` into `onUserInput` calls

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/browserify/snap.manifest.json
- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/interface/utils.test.tsx
- packages/snaps-controllers/src/interface/utils.ts
- packages/snaps-sdk/src/types/handlers/assets-lookup.test.ts
- packages/snaps-sdk/src/types/handlers/assets-lookup.ts
This makes the `name` and `symbol` of an asset optional per the SIP-29 update.
> fix: Update `name` and `symbol` to be optional in a fungible asset type

- packages/snaps-controllers/src/multichain/MultichainRouter.test.ts
- packages/snaps-controllers/src/multichain/MultichainRouter.ts
As non-EVM accounts may be case sensitive, we cannot use `toLowerCase` for address comparision. This PR makes the `MultichainRouter` use case sensitive comparison instead.
> fix: Make comparision case sensitive in MultichainRouter

- .github/workflows/validate-pull-request.yml
This PR adds a new workflow to CI which will enforce titles to use a conventional commits-style format.
> ci: Use conventional commits-style pull request titles

- packages/snaps-execution-environments/CHANGELOG.md
- packages/snaps-execution-environments/src/common/commands.test.ts
- packages/snaps-execution-environments/src/common/commands.ts
This passes the missing param `includeMarketData` to the handler in the execution environment.
> fix: Pass `includeMarketData` to handler arguments

- .github/workflows/main.yml
This updates `MetaMask/action-is-release` to `v2` which supports multiple commit titles for releases. I've added support for the following, in addition to the current "Release [version]":
- Release `[version]`
- release: [version]
- release: `[version]`
> ci: Allow `release: [version]` as release PR title

- packages/test-snaps/CHANGELOG.md
`test-snaps` didn't publish in #3325.
> fix: Fix `test-snaps` changelog

- packages/snaps-controllers/CHANGELOG.md
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
Increase the limit of the `RequestQueue` to `100` pending requests. This request queue is only used when the Snap has not yet booted, to detect issues where the Snap is failing to boot. The current limit of `5` seems too low to hit accidentally, therefore `100` was chosen which seems less likely to hit with a real use-case.
> fix: Increase boot request queue limit

- packages/examples/packages/browserify-plugin/snap.manifest.json
- packages/examples/packages/dialogs/snap.manifest.json
- packages/examples/packages/file-upload/snap.manifest.json
- packages/examples/packages/home-page/snap.manifest.json
- packages/examples/packages/interactive-ui/snap.manifest.json
- packages/examples/packages/jsx/snap.manifest.json
- packages/examples/packages/preinstalled/snap.manifest.json
- packages/examples/packages/send-flow/snap.manifest.json
- packages/snaps-sdk/src/types/handlers/user-input.ts
Use `typedUnion` for `UserInputEventStruct`. This comes with some performance benefits and also makes the error message more readable.
> perf: Use `typedUnion` for `UserInputEventStruct`

- packages/snaps-controllers/src/types/controllers.ts
Fixed incorrect terminology: 
- `"Network ID as per EIP-155"` → `"Chain ID as per EIP-155"` (EIP-155 defines `chainId`, not `network ID`).  
Fixed spelling mistake:
- `"Maxmimum"` → `"Maximum"`.
> Fix typo in documentation in `TransactionParams`

- packages/snaps-utils/src/json.ts
Alters `getJsonSizeUnsafe` to not use `TextEncoder` as this has proven slow on mobile. We don't need full byte length accuracy for the uses of `getJsonSizeUnsafe` anyway, so this is an OK tradeoff for performance.
> perf: Speed up JSON size calculation

- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
Not guaranteed to give any massive speed up, but we know `null` is safe to return as-is.
> perf: Simplify executor return

- .github/workflows/main.yml
By default, GitHub Actions allows multiple jobs within the same workflow, multiple workflow runs within the same repository, and multiple workflow runs across a repository owner's account to run concurrently. This means that multiple instances of the same workflow or job can run at the same time, performing the same steps.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
GitHub Actions also allows you to disable concurrent execution. This can be useful for controlling your account’s or organization’s resources in situations where running multiple workflows or jobs at the same time could cause conflicts or consume more Actions minutes and storage than expected.
[![Open in GitHub …
> ci: add concurrency to high volume workflows

- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.ts
- packages/snaps-execution-environments/src/common/utils.test.ts
- packages/snaps-execution-environments/src/common/utils.ts
- packages/snaps-utils/src/index.executionenv.ts
- packages/snaps-utils/src/json.ts
Previously we were validating that responses were JSON, but we already do that elsewhere and are guaranteed for the responses to be valid by the time we get to `isValidResponse`. Additionally, we don't need an entirely byte accurate length for the response, if the Snap goes beyond the limit they simply won't receive a response from the Snap.
> perf: Reduce unnecessary validation on responses

- .github/workflows/build-lint-test.yml
To reduce the number of concurrent jobs, we can stop running CI for Node.js 18 (since it's EOL in a few days anyway).
> ci: Stop running CI for Node.js 18

- packages/snaps-controllers/src/services/AbstractExecutionService.ts
When handling notifications on the command stream we already know that the values are valid JSON, therefore we can use `hasProperty` as a type guard instead of validating the notification entirely.
> perf: Use cheaper guard to determine if message is a notification

- .github/workflows/main.yml
Related to https://github.com/MetaMask/snaps/pull/3351, this allows concurrency on main branches to allow semantic releases.
> ci: allow concurrency on main

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/cronjob/CronjobController.test.ts
- packages/snaps-controllers/src/cronjob/CronjobController.ts
This PR fixes two issues:
Firstly, we were not catching errors thrown during the "daily checkin" of the `CronjobController`, this means that if one Snap failed we would not complete the initialization of the controller and no cronjobs would run.
Secondly, we were running all the cronjobs sequentially during "daily check" which seems unintentional given that we don't need the result of the cronjob invocation.
> fix: Properly catch cronjob errors during initialization

- .github/dependabot.yml
This adds `@lavamoat/*` to the Dependabot allowlist, so LavaMoat packages are automatically bumped by Dependabot.
> chore: Add `@lavamoat/*` to Dependabot allowlist

- .github/workflows/update-pull-request.yml
Currently we cache the `node_modules` folder and restore it from cache in the steps after. This means that any changes to the `yarn.lock` file made in the deduplication step are not used for generating LavaMoat policies or building the examples, sometimes resulting in errors.
To fix it, I've added a check which checks if the `yarn.lock` was updated. The other steps will use a high risk environment which skips loading the `node_modules` cache if that's the case.
> ci: Fix update workflow to use latest `yarn.lock` changes

- .github/workflows/update-pull-request.yml
After #3322, generating LavaMoat policies requires the build files to be present. Since the examples step requires build files as well, I've moved the build to a new job which is now a requirement for the other steps.
> ci: Build packages in update workflow

- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
Clear unencrypted state properly when calling `clearState`. Without this change, state from previously installed Snaps or preinstalled Snaps would retain even when resetting the client.
Also just clearing `rollbackSnapshots` which I noticed we weren't properly clearing.
> fix: Clear unencrypted Snap state properly

- packages/snaps-execution-environments/scripts/build.js
Handle Webpack compilation errors when building execution environments and set `exitCode` for CI purposes.
> build: Handle Webpack compilation errors when building execution environments

- .github/workflows/publish-environment.yml
Since building the execution environments with Webpack require the other packages to be built, we modify the `publish-environment` workflow to build the dependencies first.
> ci: Fix building execution environments for deployment

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/multichain/MultichainRouter.test.ts
- packages/snaps-controllers/src/multichain/MultichainRouter.ts
The `MultichainRouter` incorrectly passes on `params` that could be undefined, this PR fixes that.
> fix: Remove undefined params in `MultichainRouter`

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-controllers/src/snaps/constants.ts
- packages/snaps-execution-environments/coverage.json
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/common/commands.ts
- packages/snaps-rpc-methods/src/endowments/index.ts
- packages/snaps-sdk/src/types/handlers/client-request.ts
- packages/snaps-sdk/src/types/handlers/index.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/handlers/exports.test.ts
- packages/snaps-utils/src/handlers/exports.ts
- packages/snaps-utils/src/handlers/types.ts
Introduces the `onClientRequest` handler as specified in SIP-31. This handler can only be called by MetaMask and is available to all Snaps without permission. It can be used for general purpose communication that must not be exposed to dapps (as `onRpcRequest`).
This handler is enforced to only be callable by the `metamask` origin, as part of this PR this same validation is applied to all handlers in `CLIENT_ONLY_HANDLERS`.
Closes https://github.com/MetaMask/snaps/issues/3392
> feat: Implement SIP-31

- packages/examples/packages/manage-state/src/index.test.ts
Use the simulation option to specify the initial state for the manage state example Snap tests.
> test: Use simulation options for initial state

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
Add a `isMinimumPlatformVersion` action which can be used to determine if a given Snap supports a minimum version specified in its `platformVersion`. For now, if the Snap hasn't specified this we default to false.
> feat: Add `isMinimumPlatformVersion` action

- packages/examples/packages/ethereum-provider/snap.manifest.json
- packages/examples/packages/ethereum-provider/src/index.test.ts
- packages/examples/packages/ethereum-provider/src/index.ts
- packages/test-snaps/src/features/snaps/ethereum-provider/EthereumProvider.tsx
`net_version` seems to be mocked in the extension E2E environment, so we can't use it to test the switch functionality.
> feat: Add `getChainId` method to Ethereum provider example

- packages/examples/packages/background-events/CHANGELOG.md
The changelog was missing the "Unreleased" reference.
> chore: Fix background events example changelog

- packages/test-snaps/CHANGELOG.md
- packages/test-snaps/src/features/snaps/background-events/components/CancelBackgroundEvent.tsx
- packages/test-snaps/src/features/snaps/background-events/components/ScheduleBackgroundEvent.tsx
We had the wrong method names in the click handlers for background-events in test-snaps.
> fix: use correct method names for background event snap in test-snaps

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/services/AbstractExecutionService.test.ts
- packages/snaps-controllers/src/services/AbstractExecutionService.ts
- packages/snaps-controllers/src/services/iframe/IframeExecutionService.ts
- packages/snaps-controllers/src/services/offscreen/OffscreenExecutionService.ts
- packages/snaps-controllers/src/services/proxy/ProxyExecutionService.ts
- packages/snaps-controllers/src/services/webview/WebViewExecutionService.ts
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/test-utils/execution-environment.ts
Remove the extra abstraction for "jobs" in the execution service. Instead, just map each Snap ID to one job. Additionally stop storing an RPC hook for each job as it is unnecessary. Also make all properties hash private and remove some dead branches that were untested and not reachable in practice
> refactor: Simplify AbstractExecutionService

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/cronjob/CronjobController.test.ts
- packages/snaps-controllers/src/cronjob/CronjobController.ts
- packages/snaps-rpc-methods/jest.config.js
- packages/snaps-rpc-methods/src/permitted/scheduleBackgroundEvent.test.ts
- packages/snaps-rpc-methods/src/permitted/scheduleBackgroundEvent.ts
- packages/snaps-utils/src/time.test.ts
- packages/snaps-utils/src/time.ts
This PR fixes an issue with scheduling background events using durations. Since we were truncating durations to remove milliseconds we would effectively allow scheduling events less than 1 second into the future.
To work around this, durations are now allowed to be a minimum of 1 second and are untruncated. The execution date will still be truncated when the Snap requests it to prevent leakage of millisecond precision.
> fix: Prevent scheduling background events less than 1 second in the future

- package.json
- packages/snaps-controllers/CHANGELOG.md
- packages/snaps-controllers/package.json
Addition to the previous release to get a patch out for a `snaps-controllers` issue.
> Release 111.0.0

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
The current behavior for stopping Snaps (in case of crashes or idling) was prone to race conditions when requests to the Snap were dispatched around the time that the Snap crashed. 
We saw this in production here: https://github.com/MetaMask/metamask-extension/issues/33411
To prevent this, we can turn the `stopping` flag into a promise that we can await in case of multiple calls to `stopSnap`, but also before considering whether the Snap is started for a subsequent request.
> fix: Recover from a crash more gracefully

- packages/snaps-controllers/src/snaps/SnapController.ts
Log errors that cause the Snap to crash for debugging purposes. Sometimes the caller may be swallowing the error, so its important that we log it directly.
> fix: Log errors that cause a crash

- packages/snaps-controllers/coverage.json
- packages/snaps-controllers/package.json
- packages/snaps-controllers/src/cronjob/CronjobController.test.ts
- packages/snaps-controllers/src/cronjob/CronjobController.ts
- packages/snaps-controllers/src/cronjob/utils.test.ts
- packages/snaps-controllers/src/cronjob/utils.ts
- packages/snaps-controllers/src/test-utils/cronjob.ts
- packages/snaps-rpc-methods/jest.config.js
- packages/snaps-rpc-methods/package.json
- packages/snaps-rpc-methods/src/permitted/scheduleBackgroundEvent.test.ts
- packages/snaps-rpc-methods/src/permitted/scheduleBackgroundEvent.ts
- packages/snaps-sdk/src/types/methods/get-background-events.ts
- packages/snaps-sdk/src/types/permissions.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/cronjob.test.ts
- packages/snaps-utils/src/cronjob.ts
- packages/snaps-utils/src/time.ts
- yarn.lock
The cronjob controller contained a lot of essentially duplicated logic after the addition of background events. To resolve this, I've refactored the cronjob controller to treat cronjobs as recurring background events. This means:
- Cronjobs and background events are now (re)scheduled and executed using the same logic.
- Cronjobs are stored in state just like background events.
- I removed the `lastRun` property in favour of a `date` property. We can now simply check if the current date is past the scheduled date to know if a cronjob should be executed immediately.
- This simplifies the logic for rescheduling cronjobs significantly.
- Cronjobs can now use ISO 8601 durations as well as the usual cron expression.
- The logic for getting all cronjobs from all Snaps was removed, since the full …
> refactor!: Refactor cronjob controller to reduce duplication

- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/manifest/validators/unused-exports.test.ts
- packages/snaps-utils/src/manifest/validators/unused-exports.ts
This fixes an edge case in the unused permission detection, for endowments that can have multiple handlers. For example, `endowment:lifecycle-hooks` enables two (optional) handlers, `onInstall` and `onUpdate`. Previously the endowment would be detected as unused, even if one of the two was exported.
After this change, either can be specified, and the endowment will be considered used.
> fix: Fix unused permission detection for endowments with multiple handlers

- packages/snaps-rpc-methods/src/permitted/openWebSocket.test.ts
- packages/snaps-rpc-methods/src/permitted/openWebSocket.ts
- packages/snaps-sdk/src/types/methods/methods.ts
- packages/snaps-utils/coverage.json
- packages/snaps-utils/src/types.ts
Fixes a couple of issues after the merge of the WebSockets PR. Adds the proper types for the RPC methods and allows local WebSocket URLs in `snap_openWebSocket`.
Also fixes the formatting for Uri validation errors.
Closes https://github.com/MetaMask/snaps/issues/3457
> fix: Add missing WS types and allow local URLs

- packages/examples/README.md
- packages/examples/packages/cronjob-duration/.depcheckrc.json
- packages/examples/packages/cronjob-duration/CHANGELOG.md
- packages/examples/packages/cronjob-duration/LICENSE.APACHE2
- packages/examples/packages/cronjob-duration/LICENSE.MIT0
- packages/examples/packages/cronjob-duration/README.md
- packages/examples/packages/cronjob-duration/jest.config.js
- packages/examples/packages/cronjob-duration/package.json
- packages/examples/packages/cronjob-duration/snap.config.ts
- packages/examples/packages/cronjob-duration/snap.manifest.json
- packages/examples/packages/cronjob-duration/src/index.test.ts
- packages/examples/packages/cronjob-duration/src/index.ts
- packages/examples/packages/cronjob-duration/tsconfig.json
- packages/test-snaps/package.json
- packages/test-snaps/src/features/snaps/cronjob-duration/CronjobDuration.tsx
- packages/test-snaps/src/features/snaps/cronjob-duration/constants.ts
- packages/test-snaps/src/features/snaps/cronjob-duration/index.ts
- packages/test-snaps/src/features/snaps/index.ts
- yarn.lock
This adds a new example Snap demonstrating cronjobs with ISO 8601 durations instead of cron expressions.
> feat: Add cronjob duration example

- packages/examples/packages/network-access/README.md
- packages/examples/packages/network-access/snap.manifest.json
- packages/examples/packages/network-access/src/index.ts
- packages/examples/packages/network-access/src/types.ts
- packages/test-snaps/src/features/snaps/network-access/NetworkAccess.tsx
Expands the network access Snap to support opening a WebSocket connection and subscribing to block updates from a local Ethereum node. Additionally fixes some mistakes made in the original WebSocket PR.
Closes https://github.com/MetaMask/snaps/issues/3456
> feat: Add WebSocket logic to network access Snap

- package.json
- packages/test-snaps/package.json
- yarn.lock
This bumps `favicons` from `^7.1.2` to `^7.2.0` to remove a vulnerable dependency `tar-fs`.
> chore(dev-deps): Bump `favicons` from `^7.1.2` to `^7.2.0`

- packages/test-snaps/src/features/snaps/network-access/NetworkAccess.tsx
Add WebSocket URL input to test-snaps for configuring the WebSocket URL.
The Snap already supports this but was previously always using the default URL.
> feat: Add WebSocket URL input

- packages/snaps-controllers/src/cronjob/CronjobController.test.ts
- packages/snaps-controllers/src/cronjob/CronjobController.ts
Move `CronjobController` init to separate function so we don't have side-effects in the constructor. This will make it easier for us to fix issues with `SnapController` events not having a registered handler in time.
> feat!: Move `CronjobController` init to separate function

- .github/workflows/build-lint-test.yml
- packages/examples/package.json
- packages/examples/packages/invoke-snap/package.json
- yarn.config.cjs
Seems that we unintentionally stopped validating changelogs in CI at some point. This adds a step to start validating them again.
> ci: Lint changelogs in CI

- packages/snaps-controllers/src/cronjob/CronjobController.test.ts
- packages/snaps-controllers/src/cronjob/CronjobController.ts
Clear cronjobs when installing Snaps, this fixes an issue with local Snaps.
Fixes #3513
> fix: Clear cronjobs when installing a Snap

- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
Show a different error message for cancelled requests when the Snap is stopped. Right now, we show the generic "failed to respond in time" message, which is very confusing.
> fix: Show different error message for cancelled requests when Snap is stopped

- packages/snaps-controllers/src/services/AbstractExecutionService.ts
Ensure that the Snap gets at least half the allocated time for initialization, preventing a potential problem where a slowly loading execution environment would cause error messages that indicate that the Snap is slow.
> fix: Ensure Snap gets half of allocated init time

- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-execution-environments/src/common/validation.test.ts
- packages/snaps-execution-environments/src/common/validation.ts
- packages/snaps-sdk/src/types/handlers/assets-lookup.test.ts
- packages/snaps-sdk/src/types/handlers/assets-lookup.ts
- packages/snaps-sdk/src/types/handlers/assets-market-data.ts
- packages/snaps-utils/src/handlers/assets-market-data.test.ts
- packages/snaps-utils/src/handlers/assets-market-data.ts
This PR adds the support for non-fungible assets (NFTs) to `onAssetsLookup` and `onAssetsMarketData` handlers of `endowment:assets`
fixes: #3314
> feat: Add non-fungible assets support to `endowment:assets`

- packages/snaps-cli/src/cli.test.ts
- packages/snaps-cli/src/cli.ts
Display minimum version range when the CLI is using an unsupported Node version. Previously it would recommend Node 20 or later which would be incorrect for Node 21.
> fix: Display CLI minimum version range

- packages/examples/packages/lifecycle-hooks/snap.manifest.json
- packages/examples/packages/lifecycle-hooks/src/index.tsx
- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
- packages/snaps-execution-environments/src/common/BaseSnapExecutor.test.browser.ts
- packages/snaps-execution-environments/src/common/commands.ts
- packages/snaps-rpc-methods/src/endowments/index.ts
- packages/snaps-sdk/src/types/handlers/lifecycle.ts
- packages/snaps-utils/src/handlers/exports.test.ts
- packages/snaps-utils/src/handlers/exports.ts
- packages/snaps-utils/src/handlers/types.ts
This adds support for the `onActive` and `onInactive` lifecycle hooks. It's accomplished by exposing a new `setActive` action in the Snap controller, which should be called by the clients when the active status changes.
Related to #3541.
> feat: Add `onActive` and `onInactive` lifecycle hooks

- .github/CODEOWNERS
This updates the codeowners to `@MetaMask/core-platform`.
> chore: Update codeowners to `@MetaMask/core-platform`

- packages/snaps-controllers/src/services/AbstractExecutionService.test.ts
- packages/snaps-controllers/src/services/AbstractExecutionService.ts
When a Snap fails to start we call `terminateSnap` (https://github.com/MetaMask/snaps/blob/main/packages/snaps-controllers/src/snaps/SnapController.ts#L3162), but this may fail if the Snap has not fully started.
To prevent logging unnecessary errors to Sentry, this PR allows calls to `terminateSnap` even if the Snap is not currently executing, if no job is found the we just return early.
> fix: Ignore terminate calls to not executing Snaps

- docs/internals/platform/snaps-registry.md
This PR removes references to the `permissionless-snaps-registry` repository which has been deprecated.
> chore: Remove deprecated permissionless-snaps-registry link

- packages/snaps-controllers/src/cronjob/CronjobController.test.ts
- packages/snaps-controllers/src/cronjob/CronjobController.ts
Fixes two issues with the `CronjobController`. We were double scheduling events that had not run since last boot since `#execute` also schedules the next call. Additionally we were not correctly scheduling events that run for longer than 24 hours, since the daily timer would re-calculate the execution date every day.
> fix: Prevent double scheduling events and ensure long-running events work correctly

- packages/snaps-controllers/src/snaps/location/npm.test.ts
- packages/snaps-controllers/src/snaps/location/npm.ts
Throw a different error when NPM returns 404 to make it easier to distinguish this failure mode from others.
> fix: Throw clearer error when the NPM registry returns 404

- packages/snaps-rpc-methods/src/permitted/sendWebSocketMessage.test.ts
- packages/snaps-rpc-methods/src/permitted/sendWebSocketMessage.ts
The type for the `sendWebSocketMessage` hook was wrong. The function returns a promise and must be awaited, previously this would result in unhandled rejections.
> fix: Await `sendWebSocketMessage` promise

- packages/snaps-controllers/src/snaps/SnapController.test.tsx
- packages/snaps-controllers/src/snaps/SnapController.ts
Allow updating preinstalled Snaps by updating their entry in the registry. This is accomplished by searching the registry for updates whenever `updateRegistry` is called and triggering `#updateSnap`. As part of this PR the previously named `updateBlockedSnaps` has been renamed to `updateRegistry` and a flag to allow automatic updates has been added to `#updateSnap`.
When an update is automatic, the permissions requested by the Snap are applied automatically similarly to how a preinstalled Snap is initialized. Preinstalled Snaps can still be installed and updated via the constructor. In case of any errors applying the update, the Snap is rolled back to its previous state.
This behavior is put behind a feature flag that we can decide to enable at a later date.
Closes …
> feat!: Allow updating preinstalled Snaps via the registry

- packages/snaps-sdk/src/internals/structs.test.ts
- packages/snaps-sdk/src/jsx/validation.ts
Improve a couple of error messages when validating UI components that use the `children` utility method.
> fix: Improve a couple of error messages for UI components
